# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""One handle per §27 namespace, and the accessors that reach them.

§27.2 makes this namespacing normative rather than stylistic: twenty namespaces
have a ``list`` and fourteen a ``get``, so flattening 147 operations onto the
client would need a disambiguating prefix invented once per operation -- and
would bury the eight §1 methods most callers actually want under five times as
many they do not.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, cast

from axiam_sdk.management.ops.audit import AsyncAuditApi, AuditApi
from axiam_sdk.management.ops.ca_certificates import AsyncCaCertificatesApi, CaCertificatesApi
from axiam_sdk.management.ops.certificates import AsyncCertificatesApi, CertificatesApi
from axiam_sdk.management.ops.email_config import AsyncEmailConfigApi, EmailConfigApi
from axiam_sdk.management.ops.federation import AsyncFederationApi, FederationApi
from axiam_sdk.management.ops.groups import AsyncGroupsApi, GroupsApi
from axiam_sdk.management.ops.notification_rules import (
    AsyncNotificationRulesApi,
    NotificationRulesApi,
)
from axiam_sdk.management.ops.oauth2_clients import AsyncOauth2ClientsApi, Oauth2ClientsApi
from axiam_sdk.management.ops.organizations import AsyncOrganizationsApi, OrganizationsApi
from axiam_sdk.management.ops.permissions import AsyncPermissionsApi, PermissionsApi
from axiam_sdk.management.ops.pgp_keys import AsyncPgpKeysApi, PgpKeysApi
from axiam_sdk.management.ops.platform import AsyncPlatformApi, PlatformApi
from axiam_sdk.management.ops.privacy import AsyncPrivacyApi, PrivacyApi
from axiam_sdk.management.ops.reactors import AsyncReactorsApi, ReactorsApi
from axiam_sdk.management.ops.resources import AsyncResourcesApi, ResourcesApi
from axiam_sdk.management.ops.roles import AsyncRolesApi, RolesApi
from axiam_sdk.management.ops.scim_tokens import AsyncScimTokensApi, ScimTokensApi
from axiam_sdk.management.ops.scopes import AsyncScopesApi, ScopesApi
from axiam_sdk.management.ops.service_accounts import AsyncServiceAccountsApi, ServiceAccountsApi
from axiam_sdk.management.ops.settings import AsyncSettingsApi, SettingsApi
from axiam_sdk.management.ops.tenants import AsyncTenantsApi, TenantsApi
from axiam_sdk.management.ops.users import AsyncUsersApi, UsersApi
from axiam_sdk.management.ops.webauthn_policy import AsyncWebauthnPolicyApi, WebauthnPolicyApi
from axiam_sdk.management.ops.webhooks import AsyncWebhooksApi, WebhooksApi

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient
    from axiam_sdk.management.manifest import AsyncManifestApi, ManifestApi

__all__ = [
    "AsyncOrganizationsApi",
    "OrganizationsApi",
    "AsyncTenantsApi",
    "TenantsApi",
    "AsyncUsersApi",
    "UsersApi",
    "AsyncGroupsApi",
    "GroupsApi",
    "AsyncRolesApi",
    "RolesApi",
    "AsyncPermissionsApi",
    "PermissionsApi",
    "AsyncResourcesApi",
    "ResourcesApi",
    "AsyncScopesApi",
    "ScopesApi",
    "AsyncServiceAccountsApi",
    "ServiceAccountsApi",
    "AsyncCertificatesApi",
    "CertificatesApi",
    "AsyncCaCertificatesApi",
    "CaCertificatesApi",
    "AsyncPgpKeysApi",
    "PgpKeysApi",
    "AsyncWebhooksApi",
    "WebhooksApi",
    "AsyncOauth2ClientsApi",
    "Oauth2ClientsApi",
    "AsyncFederationApi",
    "FederationApi",
    "AsyncNotificationRulesApi",
    "NotificationRulesApi",
    "AsyncEmailConfigApi",
    "EmailConfigApi",
    "AsyncSettingsApi",
    "SettingsApi",
    "AsyncScimTokensApi",
    "ScimTokensApi",
    "AsyncReactorsApi",
    "ReactorsApi",
    "AsyncWebauthnPolicyApi",
    "WebauthnPolicyApi",
    "AsyncAuditApi",
    "AuditApi",
    "AsyncPrivacyApi",
    "PrivacyApi",
    "AsyncPlatformApi",
    "PlatformApi",
    "AsyncManagementApi",
    "AsyncManagementNamespaces",
    "ManagementApi",
    "ManagementNamespaces",
]


class ManagementApi:
    """The §27 management surface, grouped by namespace.

    Reached as ``client.management``. Every namespace is also reachable
    directly on the client -- ``client.users`` and
    ``client.management.users`` are the same handle.
    """

    def __init__(self, client: AxiamClient) -> None:
        """Bind the surface to ``client``."""
        self._client = client

    @property
    def organizations(self) -> OrganizationsApi:
        """Organizations an SDK client may read and configure. Creation and
        deletion are outside the SDK boundary (§27.0).
        """
        return OrganizationsApi(self._client)

    @property
    def tenants(self) -> TenantsApi:
        """Tenants within an organization -- the isolation boundary every other
        namespace is scoped to.
        """
        return TenantsApi(self._client)

    @property
    def users(self) -> UsersApi:
        """Users within the client's tenant, and the administrative side of
        their second factor and lockout state.
        """
        return UsersApi(self._client)

    @property
    def groups(self) -> GroupsApi:
        """Named collections of users. Roles assigned to a group are inherited
        by every member.
        """
        return GroupsApi(self._client)

    @property
    def roles(self) -> RolesApi:
        """Roles, their permission sets, and their assignment to users and
        groups.
        """
        return RolesApi(self._client)

    @property
    def permissions(self) -> PermissionsApi:
        """Permissions -- an action on a resource, optionally narrowed by a
        scope.
        """
        return PermissionsApi(self._client)

    @property
    def resources(self) -> ResourcesApi:
        """The resource hierarchy role assignments cascade down."""
        return ResourcesApi(self._client)

    @property
    def scopes(self) -> ScopesApi:
        """Sub-resource granularity, always addressed under their resource."""
        return ScopesApi(self._client)

    @property
    def service_accounts(self) -> ServiceAccountsApi:
        """Machine identities, their secrets, and the certificate a
        device-bound one authenticates with.
        """
        return ServiceAccountsApi(self._client)

    @property
    def certificates(self) -> CertificatesApi:
        """End-entity X.509 certificates -- the ones issued to users, services
        and IoT devices.
        """
        return CertificatesApi(self._client)

    @property
    def ca_certificates(self) -> CaCertificatesApi:
        """Organization CAs and the per-tenant signing CAs chained beneath
        them.
        """
        return CaCertificatesApi(self._client)

    @property
    def pgp_keys(self) -> PgpKeysApi:
        """OpenPGP keys used for audit signing and encrypted data export."""
        return PgpKeysApi(self._client)

    @property
    def webhooks(self) -> WebhooksApi:
        """Outbound event notifications. Delivery signatures are verified with
        the §13 helper, which this namespace configures.
        """
        return WebhooksApi(self._client)

    @property
    def oauth2_clients(self) -> Oauth2ClientsApi:
        """Registered OAuth2/OIDC clients -- the registration half of what §12,
        §21 and §26 then speak to.
        """
        return Oauth2ClientsApi(self._client)

    @property
    def federation(self) -> FederationApi:
        """Upstream IdP configuration and the per-user links it produces."""
        return FederationApi(self._client)

    @property
    def notification_rules(self) -> NotificationRulesApi:
        """Which events raise a notification, and to whom."""
        return NotificationRulesApi(self._client)

    @property
    def email_config(self) -> EmailConfigApi:
        """Transactional-mail transport, configurable at organization level and
        overridable per tenant.
        """
        return EmailConfigApi(self._client)

    @property
    def settings(self) -> SettingsApi:
        """Effective settings, and the organization/tenant layers they resolve
        from.
        """
        return SettingsApi(self._client)

    @property
    def scim_tokens(self) -> ScimTokensApi:
        """Bearer tokens for the SCIM 2.0 provisioning endpoint."""
        return ScimTokensApi(self._client)

    @property
    def reactors(self) -> ReactorsApi:
        """Registration of §22 AMQP extension actors -- the admin surface §22.9
        describes, which no SDK could previously reach.
        """
        return ReactorsApi(self._client)

    @property
    def webauthn_policy(self) -> WebauthnPolicyApi:
        """Per-tenant attestation policy governing the §24 ceremonies, and the
        compliance report over it.
        """
        return WebauthnPolicyApi(self._client)

    @property
    def audit(self) -> AuditApi:
        """Append-only audit log, read-only by construction."""
        return AuditApi(self._client)

    @property
    def privacy(self) -> PrivacyApi:
        """GDPR self-service: the authenticated account's own export and
        erasure. Scoped to the caller, never to another user.
        """
        return PrivacyApi(self._client)

    @property
    def platform(self) -> PlatformApi:
        """Deployment-level probes and FIDO metadata state. Unauthenticated
        where the server leaves them so.
        """
        return PlatformApi(self._client)

    @property
    def manifest(self) -> ManifestApi:
        """The declarative layer (§27.6): ``plan`` what a manifest would
        change, ``apply`` it.
        """
        from axiam_sdk.management.manifest import ManifestApi

        return ManifestApi(self._client)


class ManagementNamespaces:
    """The §27 accessors mixed into :class:`~axiam_sdk.AxiamClient`.

    Each property builds its handle on access and performs no I/O (§27.2
    rule 1), so holding one costs nothing and none of them runs at
    construction.
    """

    @property
    def management(self) -> ManagementApi:
        """The whole §27 surface, grouped by namespace."""
        return ManagementApi(cast("AxiamClient", self))

    @property
    def manifest(self) -> ManifestApi:
        """The declarative layer (§27.6): ``plan`` what a manifest would
        change, ``apply`` it.
        """
        return self.management.manifest

    @property
    def organizations(self) -> OrganizationsApi:
        """Organizations an SDK client may read and configure. Creation and
        deletion are outside the SDK boundary (§27.0).
        """
        return self.management.organizations

    @property
    def tenants(self) -> TenantsApi:
        """Tenants within an organization -- the isolation boundary every other
        namespace is scoped to.
        """
        return self.management.tenants

    @property
    def users(self) -> UsersApi:
        """Users within the client's tenant, and the administrative side of
        their second factor and lockout state.
        """
        return self.management.users

    @property
    def groups(self) -> GroupsApi:
        """Named collections of users. Roles assigned to a group are inherited
        by every member.
        """
        return self.management.groups

    @property
    def roles(self) -> RolesApi:
        """Roles, their permission sets, and their assignment to users and
        groups.
        """
        return self.management.roles

    @property
    def permissions(self) -> PermissionsApi:
        """Permissions -- an action on a resource, optionally narrowed by a
        scope.
        """
        return self.management.permissions

    @property
    def resources(self) -> ResourcesApi:
        """The resource hierarchy role assignments cascade down."""
        return self.management.resources

    @property
    def scopes(self) -> ScopesApi:
        """Sub-resource granularity, always addressed under their resource."""
        return self.management.scopes

    @property
    def service_accounts(self) -> ServiceAccountsApi:
        """Machine identities, their secrets, and the certificate a
        device-bound one authenticates with.
        """
        return self.management.service_accounts

    @property
    def certificates(self) -> CertificatesApi:
        """End-entity X.509 certificates -- the ones issued to users, services
        and IoT devices.
        """
        return self.management.certificates

    @property
    def ca_certificates(self) -> CaCertificatesApi:
        """Organization CAs and the per-tenant signing CAs chained beneath
        them.
        """
        return self.management.ca_certificates

    @property
    def pgp_keys(self) -> PgpKeysApi:
        """OpenPGP keys used for audit signing and encrypted data export."""
        return self.management.pgp_keys

    @property
    def webhooks(self) -> WebhooksApi:
        """Outbound event notifications. Delivery signatures are verified with
        the §13 helper, which this namespace configures.
        """
        return self.management.webhooks

    @property
    def oauth2_clients(self) -> Oauth2ClientsApi:
        """Registered OAuth2/OIDC clients -- the registration half of what §12,
        §21 and §26 then speak to.
        """
        return self.management.oauth2_clients

    @property
    def federation(self) -> FederationApi:
        """Upstream IdP configuration and the per-user links it produces."""
        return self.management.federation

    @property
    def notification_rules(self) -> NotificationRulesApi:
        """Which events raise a notification, and to whom."""
        return self.management.notification_rules

    @property
    def email_config(self) -> EmailConfigApi:
        """Transactional-mail transport, configurable at organization level and
        overridable per tenant.
        """
        return self.management.email_config

    @property
    def settings(self) -> SettingsApi:
        """Effective settings, and the organization/tenant layers they resolve
        from.
        """
        return self.management.settings

    @property
    def scim_tokens(self) -> ScimTokensApi:
        """Bearer tokens for the SCIM 2.0 provisioning endpoint."""
        return self.management.scim_tokens

    @property
    def reactors(self) -> ReactorsApi:
        """Registration of §22 AMQP extension actors -- the admin surface §22.9
        describes, which no SDK could previously reach.
        """
        return self.management.reactors

    @property
    def webauthn_policy(self) -> WebauthnPolicyApi:
        """Per-tenant attestation policy governing the §24 ceremonies, and the
        compliance report over it.
        """
        return self.management.webauthn_policy

    @property
    def audit(self) -> AuditApi:
        """Append-only audit log, read-only by construction."""
        return self.management.audit

    @property
    def privacy(self) -> PrivacyApi:
        """GDPR self-service: the authenticated account's own export and
        erasure. Scoped to the caller, never to another user.
        """
        return self.management.privacy

    @property
    def platform(self) -> PlatformApi:
        """Deployment-level probes and FIDO metadata state. Unauthenticated
        where the server leaves them so.
        """
        return self.management.platform


class AsyncManagementApi:
    """The §27 management surface, async form, grouped by namespace.

    Reached as ``client.management``. Every namespace is also reachable
    directly on the client -- ``client.users`` and
    ``client.management.users`` are the same handle.
    """

    def __init__(self, client: AsyncAxiamClient) -> None:
        """Bind the surface to ``client``."""
        self._client = client

    @property
    def organizations(self) -> AsyncOrganizationsApi:
        """Organizations an SDK client may read and configure. Creation and
        deletion are outside the SDK boundary (§27.0).
        """
        return AsyncOrganizationsApi(self._client)

    @property
    def tenants(self) -> AsyncTenantsApi:
        """Tenants within an organization -- the isolation boundary every other
        namespace is scoped to.
        """
        return AsyncTenantsApi(self._client)

    @property
    def users(self) -> AsyncUsersApi:
        """Users within the client's tenant, and the administrative side of
        their second factor and lockout state.
        """
        return AsyncUsersApi(self._client)

    @property
    def groups(self) -> AsyncGroupsApi:
        """Named collections of users. Roles assigned to a group are inherited
        by every member.
        """
        return AsyncGroupsApi(self._client)

    @property
    def roles(self) -> AsyncRolesApi:
        """Roles, their permission sets, and their assignment to users and
        groups.
        """
        return AsyncRolesApi(self._client)

    @property
    def permissions(self) -> AsyncPermissionsApi:
        """Permissions -- an action on a resource, optionally narrowed by a
        scope.
        """
        return AsyncPermissionsApi(self._client)

    @property
    def resources(self) -> AsyncResourcesApi:
        """The resource hierarchy role assignments cascade down."""
        return AsyncResourcesApi(self._client)

    @property
    def scopes(self) -> AsyncScopesApi:
        """Sub-resource granularity, always addressed under their resource."""
        return AsyncScopesApi(self._client)

    @property
    def service_accounts(self) -> AsyncServiceAccountsApi:
        """Machine identities, their secrets, and the certificate a
        device-bound one authenticates with.
        """
        return AsyncServiceAccountsApi(self._client)

    @property
    def certificates(self) -> AsyncCertificatesApi:
        """End-entity X.509 certificates -- the ones issued to users, services
        and IoT devices.
        """
        return AsyncCertificatesApi(self._client)

    @property
    def ca_certificates(self) -> AsyncCaCertificatesApi:
        """Organization CAs and the per-tenant signing CAs chained beneath
        them.
        """
        return AsyncCaCertificatesApi(self._client)

    @property
    def pgp_keys(self) -> AsyncPgpKeysApi:
        """OpenPGP keys used for audit signing and encrypted data export."""
        return AsyncPgpKeysApi(self._client)

    @property
    def webhooks(self) -> AsyncWebhooksApi:
        """Outbound event notifications. Delivery signatures are verified with
        the §13 helper, which this namespace configures.
        """
        return AsyncWebhooksApi(self._client)

    @property
    def oauth2_clients(self) -> AsyncOauth2ClientsApi:
        """Registered OAuth2/OIDC clients -- the registration half of what §12,
        §21 and §26 then speak to.
        """
        return AsyncOauth2ClientsApi(self._client)

    @property
    def federation(self) -> AsyncFederationApi:
        """Upstream IdP configuration and the per-user links it produces."""
        return AsyncFederationApi(self._client)

    @property
    def notification_rules(self) -> AsyncNotificationRulesApi:
        """Which events raise a notification, and to whom."""
        return AsyncNotificationRulesApi(self._client)

    @property
    def email_config(self) -> AsyncEmailConfigApi:
        """Transactional-mail transport, configurable at organization level and
        overridable per tenant.
        """
        return AsyncEmailConfigApi(self._client)

    @property
    def settings(self) -> AsyncSettingsApi:
        """Effective settings, and the organization/tenant layers they resolve
        from.
        """
        return AsyncSettingsApi(self._client)

    @property
    def scim_tokens(self) -> AsyncScimTokensApi:
        """Bearer tokens for the SCIM 2.0 provisioning endpoint."""
        return AsyncScimTokensApi(self._client)

    @property
    def reactors(self) -> AsyncReactorsApi:
        """Registration of §22 AMQP extension actors -- the admin surface §22.9
        describes, which no SDK could previously reach.
        """
        return AsyncReactorsApi(self._client)

    @property
    def webauthn_policy(self) -> AsyncWebauthnPolicyApi:
        """Per-tenant attestation policy governing the §24 ceremonies, and the
        compliance report over it.
        """
        return AsyncWebauthnPolicyApi(self._client)

    @property
    def audit(self) -> AsyncAuditApi:
        """Append-only audit log, read-only by construction."""
        return AsyncAuditApi(self._client)

    @property
    def privacy(self) -> AsyncPrivacyApi:
        """GDPR self-service: the authenticated account's own export and
        erasure. Scoped to the caller, never to another user.
        """
        return AsyncPrivacyApi(self._client)

    @property
    def platform(self) -> AsyncPlatformApi:
        """Deployment-level probes and FIDO metadata state. Unauthenticated
        where the server leaves them so.
        """
        return AsyncPlatformApi(self._client)

    @property
    def manifest(self) -> AsyncManifestApi:
        """The declarative layer (§27.6): ``plan`` what a manifest would
        change, ``apply`` it.
        """
        from axiam_sdk.management.manifest import AsyncManifestApi

        return AsyncManifestApi(self._client)


class AsyncManagementNamespaces:
    """The §27 accessors mixed into :class:`~axiam_sdk.AsyncAxiamClient`.

    Each property builds its handle on access and performs no I/O (§27.2
    rule 1), so holding one costs nothing and none of them runs at
    construction.
    """

    @property
    def management(self) -> AsyncManagementApi:
        """The whole §27 surface, grouped by namespace."""
        return AsyncManagementApi(cast("AsyncAxiamClient", self))

    @property
    def manifest(self) -> AsyncManifestApi:
        """The declarative layer (§27.6): ``plan`` what a manifest would
        change, ``apply`` it.
        """
        return self.management.manifest

    @property
    def organizations(self) -> AsyncOrganizationsApi:
        """Organizations an SDK client may read and configure. Creation and
        deletion are outside the SDK boundary (§27.0).
        """
        return self.management.organizations

    @property
    def tenants(self) -> AsyncTenantsApi:
        """Tenants within an organization -- the isolation boundary every other
        namespace is scoped to.
        """
        return self.management.tenants

    @property
    def users(self) -> AsyncUsersApi:
        """Users within the client's tenant, and the administrative side of
        their second factor and lockout state.
        """
        return self.management.users

    @property
    def groups(self) -> AsyncGroupsApi:
        """Named collections of users. Roles assigned to a group are inherited
        by every member.
        """
        return self.management.groups

    @property
    def roles(self) -> AsyncRolesApi:
        """Roles, their permission sets, and their assignment to users and
        groups.
        """
        return self.management.roles

    @property
    def permissions(self) -> AsyncPermissionsApi:
        """Permissions -- an action on a resource, optionally narrowed by a
        scope.
        """
        return self.management.permissions

    @property
    def resources(self) -> AsyncResourcesApi:
        """The resource hierarchy role assignments cascade down."""
        return self.management.resources

    @property
    def scopes(self) -> AsyncScopesApi:
        """Sub-resource granularity, always addressed under their resource."""
        return self.management.scopes

    @property
    def service_accounts(self) -> AsyncServiceAccountsApi:
        """Machine identities, their secrets, and the certificate a
        device-bound one authenticates with.
        """
        return self.management.service_accounts

    @property
    def certificates(self) -> AsyncCertificatesApi:
        """End-entity X.509 certificates -- the ones issued to users, services
        and IoT devices.
        """
        return self.management.certificates

    @property
    def ca_certificates(self) -> AsyncCaCertificatesApi:
        """Organization CAs and the per-tenant signing CAs chained beneath
        them.
        """
        return self.management.ca_certificates

    @property
    def pgp_keys(self) -> AsyncPgpKeysApi:
        """OpenPGP keys used for audit signing and encrypted data export."""
        return self.management.pgp_keys

    @property
    def webhooks(self) -> AsyncWebhooksApi:
        """Outbound event notifications. Delivery signatures are verified with
        the §13 helper, which this namespace configures.
        """
        return self.management.webhooks

    @property
    def oauth2_clients(self) -> AsyncOauth2ClientsApi:
        """Registered OAuth2/OIDC clients -- the registration half of what §12,
        §21 and §26 then speak to.
        """
        return self.management.oauth2_clients

    @property
    def federation(self) -> AsyncFederationApi:
        """Upstream IdP configuration and the per-user links it produces."""
        return self.management.federation

    @property
    def notification_rules(self) -> AsyncNotificationRulesApi:
        """Which events raise a notification, and to whom."""
        return self.management.notification_rules

    @property
    def email_config(self) -> AsyncEmailConfigApi:
        """Transactional-mail transport, configurable at organization level and
        overridable per tenant.
        """
        return self.management.email_config

    @property
    def settings(self) -> AsyncSettingsApi:
        """Effective settings, and the organization/tenant layers they resolve
        from.
        """
        return self.management.settings

    @property
    def scim_tokens(self) -> AsyncScimTokensApi:
        """Bearer tokens for the SCIM 2.0 provisioning endpoint."""
        return self.management.scim_tokens

    @property
    def reactors(self) -> AsyncReactorsApi:
        """Registration of §22 AMQP extension actors -- the admin surface §22.9
        describes, which no SDK could previously reach.
        """
        return self.management.reactors

    @property
    def webauthn_policy(self) -> AsyncWebauthnPolicyApi:
        """Per-tenant attestation policy governing the §24 ceremonies, and the
        compliance report over it.
        """
        return self.management.webauthn_policy

    @property
    def audit(self) -> AsyncAuditApi:
        """Append-only audit log, read-only by construction."""
        return self.management.audit

    @property
    def privacy(self) -> AsyncPrivacyApi:
        """GDPR self-service: the authenticated account's own export and
        erasure. Scoped to the caller, never to another user.
        """
        return self.management.privacy

    @property
    def platform(self) -> AsyncPlatformApi:
        """Deployment-level probes and FIDO metadata state. Unauthenticated
        where the server leaves them so.
        """
        return self.management.platform
