# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``audit`` management namespace (CONTRACT §27.1).

Append-only audit log, read-only by construction.
"""

from __future__ import annotations

import builtins
from dataclasses import dataclass
from typing import TYPE_CHECKING

from axiam_sdk.management import models
from axiam_sdk.management._page import (
    Page,
    PageRequest,
    collect_pages,
    collect_pages_async,
    page_of,
    page_query,
)
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


@dataclass(frozen=True)
class AuditListFilter:
    """Optional filters for ``audit.list``.

    Six loose optional arguments is a call site a reader cannot check and a
    refactor silently reorders, so they travel as one object.
    """

    actor_id: str | None = None
    """Filter on ``actor_id``."""

    action: str | None = None
    """Filter on ``action``."""

    outcome: str | None = None
    """Filter on ``outcome``."""

    resource_id: str | None = None
    """Filter on ``resource_id``."""

    from_: str | None = None
    """Filter on ``from``."""

    to: str | None = None
    """Filter on ``to``."""


@dataclass(frozen=True)
class AuditListSystemFilter:
    """Optional filters for ``audit.list_system``.

    Six loose optional arguments is a call site a reader cannot check and a
    refactor silently reorders, so they travel as one object.
    """

    actor_id: str | None = None
    """Filter on ``actor_id``."""

    action: str | None = None
    """Filter on ``action``."""

    outcome: str | None = None
    """Filter on ``outcome``."""

    resource_id: str | None = None
    """Filter on ``resource_id``."""

    from_: str | None = None
    """Filter on ``from``."""

    to: str | None = None
    """Filter on ``to``."""


def _call_list(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    filter: AuditListFilter | None = None,
    page: PageRequest | None = None,
) -> ManagementCall:
    """Build the ``audit.list`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="audit.list",
        method="GET",
        path_template="/api/v1/audit-logs",
        path="/api/v1/audit-logs",
        query={
            **page_query(page),
            "actor_id": (filter.actor_id if filter else None),
            "action": (filter.action if filter else None),
            "outcome": (filter.outcome if filter else None),
            "resource_id": (filter.resource_id if filter else None),
            "from": (filter.from_ if filter else None),
            "to": (filter.to if filter else None),
        },
    )


def _call_list_system(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    filter: AuditListSystemFilter | None = None,
    page: PageRequest | None = None,
) -> ManagementCall:
    """Build the ``audit.list_system`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="audit.list_system",
        method="GET",
        path_template="/api/v1/audit-logs/system",
        path="/api/v1/audit-logs/system",
        query={
            **page_query(page),
            "actor_id": (filter.actor_id if filter else None),
            "action": (filter.action if filter else None),
            "outcome": (filter.outcome if filter else None),
            "resource_id": (filter.resource_id if filter else None),
            "from": (filter.from_ if filter else None),
            "to": (filter.to if filter else None),
        },
    )


class AuditApi:
    """The ``audit`` namespace handle.

    Append-only audit log, read-only by construction.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def list(
        self,
        filter: AuditListFilter | None = None,
        page: PageRequest | None = None,
    ) -> Page[models.AuditLogEntry]:
        """``GET /api/v1/audit-logs``"""
        raw = send_management(
            self._client,
            _call_list(self._client, self._scope, filter, page),
        )
        return page_of(raw, models.AuditLogEntry)

    def list_all(
        self,
        filter: AuditListFilter | None = None,
        start: PageRequest | None = None,
    ) -> builtins.list[models.AuditLogEntry]:
        """Walk ``audit.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return collect_pages(start, lambda p: self.list(filter, p))

    def list_system(
        self,
        filter: AuditListSystemFilter | None = None,
        page: PageRequest | None = None,
    ) -> Page[models.AuditLogEntry]:
        """``GET /api/v1/audit-logs/system``"""
        raw = send_management(
            self._client,
            _call_list_system(self._client, self._scope, filter, page),
        )
        return page_of(raw, models.AuditLogEntry)

    def list_system_all(
        self,
        filter: AuditListSystemFilter | None = None,
        start: PageRequest | None = None,
    ) -> builtins.list[models.AuditLogEntry]:
        """Walk ``audit.list_system`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return collect_pages(start, lambda p: self.list_system(filter, p))


class AsyncAuditApi:
    """The ``audit`` namespace handle, async form.

    Append-only audit log, read-only by construction.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    async def list(
        self,
        filter: AuditListFilter | None = None,
        page: PageRequest | None = None,
    ) -> Page[models.AuditLogEntry]:
        """``GET /api/v1/audit-logs``"""
        raw = await send_management_async(
            self._client,
            _call_list(self._client, self._scope, filter, page),
        )
        return page_of(raw, models.AuditLogEntry)

    async def list_all(
        self,
        filter: AuditListFilter | None = None,
        start: PageRequest | None = None,
    ) -> builtins.list[models.AuditLogEntry]:
        """Walk ``audit.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return await collect_pages_async(start, lambda p: self.list(filter, p))

    async def list_system(
        self,
        filter: AuditListSystemFilter | None = None,
        page: PageRequest | None = None,
    ) -> Page[models.AuditLogEntry]:
        """``GET /api/v1/audit-logs/system``"""
        raw = await send_management_async(
            self._client,
            _call_list_system(self._client, self._scope, filter, page),
        )
        return page_of(raw, models.AuditLogEntry)

    async def list_system_all(
        self,
        filter: AuditListSystemFilter | None = None,
        start: PageRequest | None = None,
    ) -> builtins.list[models.AuditLogEntry]:
        """Walk ``audit.list_system`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return await collect_pages_async(start, lambda p: self.list_system(filter, p))
