# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``certificates`` management namespace (CONTRACT §27.1).

End-entity X.509 certificates -- the ones issued to users, services and IoT
devices.
"""

from __future__ import annotations

import builtins
from typing import TYPE_CHECKING

from axiam_sdk.management import models
from axiam_sdk.management._page import (
    Page,
    PageRequest,
    collect_pages,
    collect_pages_async,
    page_of,
    page_query,
)
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
    require_uuid,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_list(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    page: PageRequest | None = None,
) -> ManagementCall:
    """Build the ``certificates.list`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="certificates.list",
        method="GET",
        path_template="/api/v1/certificates",
        path="/api/v1/certificates",
        query={**page_query(page)},
    )


def _call_generate(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.CreateCertificateRequest,
) -> ManagementCall:
    """Build the ``certificates.generate`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="certificates.generate",
        method="POST",
        path_template="/api/v1/certificates",
        path="/api/v1/certificates",
        body=body.to_wire(),
    )


def _call_get(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    id: str,
) -> ManagementCall:
    """Build the ``certificates.get`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    id = require_uuid(id, "id", "certificates.get")
    return ManagementCall(
        operation="certificates.get",
        method="GET",
        path_template="/api/v1/certificates/{id}",
        path=f"/api/v1/certificates/{id}",
    )


def _call_revoke(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    id: str,
) -> ManagementCall:
    """Build the ``certificates.revoke`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    id = require_uuid(id, "id", "certificates.revoke")
    return ManagementCall(
        operation="certificates.revoke",
        method="POST",
        path_template="/api/v1/certificates/{id}/revoke",
        path=f"/api/v1/certificates/{id}/revoke",
    )


class CertificatesApi:
    """The ``certificates`` namespace handle.

    End-entity X.509 certificates -- the ones issued to users, services and
    IoT devices.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def list(self, page: PageRequest | None = None) -> Page[models.Certificate]:
        """``GET /api/v1/certificates``"""
        raw = send_management(
            self._client,
            _call_list(self._client, self._scope, page),
        )
        return page_of(raw, models.Certificate)

    def list_all(self, start: PageRequest | None = None) -> builtins.list[models.Certificate]:
        """Walk ``certificates.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return collect_pages(start, lambda p: self.list(p))

    def generate(self, body: models.CreateCertificateRequest) -> models.GeneratedCertificate:
        """``POST /api/v1/certificates``

        **Returns secret material, once.** ``private_key_pem`` is returned
        by this call and by no other; no later ``get`` will return it again,
        and the ``get`` projection has no field where it was. Discarding the
        result destroys the credential (§27.5 rule 3).

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_generate(self._client, self._scope, body),
        )
        return models.GeneratedCertificate.model_validate(raw)

    def get(self, id: str) -> models.Certificate:
        """``GET /api/v1/certificates/{id}``"""
        raw = send_management(
            self._client,
            _call_get(self._client, self._scope, id),
        )
        return models.Certificate.model_validate(raw)

    def revoke(self, id: str) -> None:
        """``POST /api/v1/certificates/{id}/revoke``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_revoke(self._client, self._scope, id),
        )


class AsyncCertificatesApi:
    """The ``certificates`` namespace handle, async form.

    End-entity X.509 certificates -- the ones issued to users, services and
    IoT devices.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    async def list(self, page: PageRequest | None = None) -> Page[models.Certificate]:
        """``GET /api/v1/certificates``"""
        raw = await send_management_async(
            self._client,
            _call_list(self._client, self._scope, page),
        )
        return page_of(raw, models.Certificate)

    async def list_all(self, start: PageRequest | None = None) -> builtins.list[models.Certificate]:
        """Walk ``certificates.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return await collect_pages_async(start, lambda p: self.list(p))

    async def generate(self, body: models.CreateCertificateRequest) -> models.GeneratedCertificate:
        """``POST /api/v1/certificates``

        **Returns secret material, once.** ``private_key_pem`` is returned
        by this call and by no other; no later ``get`` will return it again,
        and the ``get`` projection has no field where it was. Discarding the
        result destroys the credential (§27.5 rule 3).

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_generate(self._client, self._scope, body),
        )
        return models.GeneratedCertificate.model_validate(raw)

    async def get(self, id: str) -> models.Certificate:
        """``GET /api/v1/certificates/{id}``"""
        raw = await send_management_async(
            self._client,
            _call_get(self._client, self._scope, id),
        )
        return models.Certificate.model_validate(raw)

    async def revoke(self, id: str) -> None:
        """``POST /api/v1/certificates/{id}/revoke``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_revoke(self._client, self._scope, id),
        )
