# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``directory`` management namespace (CONTRACT §27.1).

A tenant's LDAP / Active Directory identity source (CONTRACT §30): the one
configuration, the explicit act that links an existing local account to its
directory entry, and a read-only view of the sync job. Signing in needs
nothing new -- a directory account calls the same §1 `login`.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from axiam_sdk.management import models
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
    resolve_tenant,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_get(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``directory.get`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "directory.get")
    return ManagementCall(
        operation="directory.get",
        method="GET",
        path_template="/api/v1/tenants/{tenant_id}/directory",
        path=f"/api/v1/tenants/{tenant_id}/directory",
    )


def _call_set(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.SetDirectoryConfig,
) -> ManagementCall:
    """Build the ``directory.set`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "directory.set")
    return ManagementCall(
        operation="directory.set",
        method="PUT",
        path_template="/api/v1/tenants/{tenant_id}/directory",
        path=f"/api/v1/tenants/{tenant_id}/directory",
        body=body.to_wire(),
    )


def _call_update(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.UpdateDirectoryConfig,
) -> ManagementCall:
    """Build the ``directory.update`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "directory.update")
    return ManagementCall(
        operation="directory.update",
        method="PATCH",
        path_template="/api/v1/tenants/{tenant_id}/directory",
        path=f"/api/v1/tenants/{tenant_id}/directory",
        body=body.to_wire(),
    )


def _call_delete(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``directory.delete`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "directory.delete")
    return ManagementCall(
        operation="directory.delete",
        method="DELETE",
        path_template="/api/v1/tenants/{tenant_id}/directory",
        path=f"/api/v1/tenants/{tenant_id}/directory",
    )


def _call_link_account(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.LinkDirectoryAccount,
) -> ManagementCall:
    """Build the ``directory.link_account`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "directory.link_account")
    return ManagementCall(
        operation="directory.link_account",
        method="POST",
        path_template="/api/v1/tenants/{tenant_id}/directory/links",
        path=f"/api/v1/tenants/{tenant_id}/directory/links",
        body=body.to_wire(),
    )


def _call_get_sync_status(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``directory.get_sync_status`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "directory.get_sync_status")
    return ManagementCall(
        operation="directory.get_sync_status",
        method="GET",
        path_template="/api/v1/tenants/{tenant_id}/directory/sync-status",
        path=f"/api/v1/tenants/{tenant_id}/directory/sync-status",
    )


class DirectoryApi:
    """The ``directory`` namespace handle.

    A tenant's LDAP / Active Directory identity source (CONTRACT §30): the
    one configuration, the explicit act that links an existing local account
    to its directory entry, and a read-only view of the sync job. Signing in
    needs nothing new -- a directory account calls the same §1 `login`.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def for_tenant(self, tenant_id: str) -> DirectoryApi:
        """Address a different tenant than the client's own (§27.4 rule 3).

        Returns a new handle; the original is unchanged.
        """
        return DirectoryApi(self._client, self._scope.with_tenant(tenant_id))

    def get(self) -> models.DirectoryConfig:
        """``GET /api/v1/tenants/{tenant_id}/directory``"""
        raw = send_management(
            self._client,
            _call_get(self._client, self._scope),
        )
        return models.DirectoryConfig.model_validate(raw)

    def set(self, body: models.SetDirectoryConfig) -> models.DirectoryConfig:
        """``PUT /api/v1/tenants/{tenant_id}/directory``

        **Moving the connection requires the secret again** (§30.3 rule 2):
        a ``set`` that changes ``url``, ``start_tls``, ``bind_dn`` or
        ``trust_anchors_pem`` without ``bind_secret`` is refused ``400`` and
        changes nothing. The SDK holds no copy of the secret and cannot
        re-send one for you. ``bind_secret`` is required while the tenant
        has no configuration; otherwise absent keeps the stored secret.
        Every other optional member left out is **reset to its default**. An
        enabled directory and an effective ``opaque_mode = required`` never
        coexist (``409``); without the deployment's directory key a write
        carrying a secret is ``503``.

        **This is a replacement, not a patch** (§27.4 rule 5). Every field
        of the body is required, and what you do not carry over from a prior
        read is not preserved -- it is overwritten. Read first, change the
        field you mean, send the whole thing back.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_set(self._client, self._scope, body),
        )
        return models.DirectoryConfig.model_validate(raw)

    def update(self, body: models.UpdateDirectoryConfig) -> models.DirectoryConfig:
        """``PATCH /api/v1/tenants/{tenant_id}/directory``

        **Moving the connection requires the secret again** (§30.3 rule 2):
        an ``update`` that changes ``url``, ``start_tls``, ``bind_dn`` or
        ``trust_anchors_pem`` without ``bind_secret`` is refused ``400`` and
        changes nothing; the SDK holds no copy of the secret to re-send. A
        member left unset is not sent and stays as stored; ``group_base_dn``
        / ``group_filter`` set explicitly to ``None`` are sent as ``null``
        and clear the value. An enabled directory and an effective
        ``opaque_mode = required`` never coexist (``409``).

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_update(self._client, self._scope, body),
        )
        return models.DirectoryConfig.model_validate(raw)

    def delete(self) -> None:
        """``DELETE /api/v1/tenants/{tenant_id}/directory``

        **Deleting stops the directory, and only that** (§30.3 rule 5):
        directory accounts can no longer sign in with a password -- there is
        no fallback to a local hash -- and the sync stops. Sessions, refresh
        tokens and passkeys those accounts already hold keep working until
        they expire or the accounts are deactivated. There is no unlink: a
        linked account stays a directory account.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_delete(self._client, self._scope),
        )

    def link_account(self, body: models.LinkDirectoryAccount) -> models.DirectoryLinkResult:
        """``POST /api/v1/tenants/{tenant_id}/directory/links``

        **Signs the account's owner out everywhere** (§30.3 rule 6): linking
        deletes the account's WebAuthn credentials and federation links,
        revokes its ``User`` certificates, all its sessions and its OAuth2
        refresh tokens (TOTP is kept). The entry is found by the account's
        own username; a repeat on an already-linked account answers
        ``was_already_linked`` and repeats the revocations.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_link_account(self._client, self._scope, body),
        )
        return models.DirectoryLinkResult.model_validate(raw)

    def get_sync_status(self) -> models.DirectorySyncStatus:
        """``GET /api/v1/tenants/{tenant_id}/directory/sync-status``"""
        raw = send_management(
            self._client,
            _call_get_sync_status(self._client, self._scope),
        )
        return models.DirectorySyncStatus.model_validate(raw)


class AsyncDirectoryApi:
    """The ``directory`` namespace handle, async form.

    A tenant's LDAP / Active Directory identity source (CONTRACT §30): the
    one configuration, the explicit act that links an existing local account
    to its directory entry, and a read-only view of the sync job. Signing in
    needs nothing new -- a directory account calls the same §1 `login`.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def for_tenant(self, tenant_id: str) -> AsyncDirectoryApi:
        """Address a different tenant than the client's own (§27.4 rule 3).

        Returns a new handle; the original is unchanged.
        """
        return AsyncDirectoryApi(self._client, self._scope.with_tenant(tenant_id))

    async def get(self) -> models.DirectoryConfig:
        """``GET /api/v1/tenants/{tenant_id}/directory``"""
        raw = await send_management_async(
            self._client,
            _call_get(self._client, self._scope),
        )
        return models.DirectoryConfig.model_validate(raw)

    async def set(self, body: models.SetDirectoryConfig) -> models.DirectoryConfig:
        """``PUT /api/v1/tenants/{tenant_id}/directory``

        **Moving the connection requires the secret again** (§30.3 rule 2):
        a ``set`` that changes ``url``, ``start_tls``, ``bind_dn`` or
        ``trust_anchors_pem`` without ``bind_secret`` is refused ``400`` and
        changes nothing. The SDK holds no copy of the secret and cannot
        re-send one for you. ``bind_secret`` is required while the tenant
        has no configuration; otherwise absent keeps the stored secret.
        Every other optional member left out is **reset to its default**. An
        enabled directory and an effective ``opaque_mode = required`` never
        coexist (``409``); without the deployment's directory key a write
        carrying a secret is ``503``.

        **This is a replacement, not a patch** (§27.4 rule 5). Every field
        of the body is required, and what you do not carry over from a prior
        read is not preserved -- it is overwritten. Read first, change the
        field you mean, send the whole thing back.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_set(self._client, self._scope, body),
        )
        return models.DirectoryConfig.model_validate(raw)

    async def update(self, body: models.UpdateDirectoryConfig) -> models.DirectoryConfig:
        """``PATCH /api/v1/tenants/{tenant_id}/directory``

        **Moving the connection requires the secret again** (§30.3 rule 2):
        an ``update`` that changes ``url``, ``start_tls``, ``bind_dn`` or
        ``trust_anchors_pem`` without ``bind_secret`` is refused ``400`` and
        changes nothing; the SDK holds no copy of the secret to re-send. A
        member left unset is not sent and stays as stored; ``group_base_dn``
        / ``group_filter`` set explicitly to ``None`` are sent as ``null``
        and clear the value. An enabled directory and an effective
        ``opaque_mode = required`` never coexist (``409``).

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_update(self._client, self._scope, body),
        )
        return models.DirectoryConfig.model_validate(raw)

    async def delete(self) -> None:
        """``DELETE /api/v1/tenants/{tenant_id}/directory``

        **Deleting stops the directory, and only that** (§30.3 rule 5):
        directory accounts can no longer sign in with a password -- there is
        no fallback to a local hash -- and the sync stops. Sessions, refresh
        tokens and passkeys those accounts already hold keep working until
        they expire or the accounts are deactivated. There is no unlink: a
        linked account stays a directory account.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_delete(self._client, self._scope),
        )

    async def link_account(self, body: models.LinkDirectoryAccount) -> models.DirectoryLinkResult:
        """``POST /api/v1/tenants/{tenant_id}/directory/links``

        **Signs the account's owner out everywhere** (§30.3 rule 6): linking
        deletes the account's WebAuthn credentials and federation links,
        revokes its ``User`` certificates, all its sessions and its OAuth2
        refresh tokens (TOTP is kept). The entry is found by the account's
        own username; a repeat on an already-linked account answers
        ``was_already_linked`` and repeats the revocations.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_link_account(self._client, self._scope, body),
        )
        return models.DirectoryLinkResult.model_validate(raw)

    async def get_sync_status(self) -> models.DirectorySyncStatus:
        """``GET /api/v1/tenants/{tenant_id}/directory/sync-status``"""
        raw = await send_management_async(
            self._client,
            _call_get_sync_status(self._client, self._scope),
        )
        return models.DirectorySyncStatus.model_validate(raw)
