# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``email_config`` management namespace (CONTRACT §27.1).

Transactional-mail transport, configurable at organization level and
overridable per tenant.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from axiam_sdk.management import models
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
    resolve_org,
    resolve_tenant,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_get_org(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``email_config.get_org`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    org_id = resolve_org(client, scope, "email_config.get_org")
    return ManagementCall(
        operation="email_config.get_org",
        method="GET",
        path_template="/api/v1/organizations/{org_id}/email-config",
        path=f"/api/v1/organizations/{org_id}/email-config",
    )


def _call_set_org(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.SetOrgEmailConfig,
) -> ManagementCall:
    """Build the ``email_config.set_org`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    org_id = resolve_org(client, scope, "email_config.set_org")
    return ManagementCall(
        operation="email_config.set_org",
        method="PUT",
        path_template="/api/v1/organizations/{org_id}/email-config",
        path=f"/api/v1/organizations/{org_id}/email-config",
        body=body.to_wire(),
    )


def _call_delete_org(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``email_config.delete_org`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    org_id = resolve_org(client, scope, "email_config.delete_org")
    return ManagementCall(
        operation="email_config.delete_org",
        method="DELETE",
        path_template="/api/v1/organizations/{org_id}/email-config",
        path=f"/api/v1/organizations/{org_id}/email-config",
    )


def _call_test_org(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``email_config.test_org`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    org_id = resolve_org(client, scope, "email_config.test_org")
    return ManagementCall(
        operation="email_config.test_org",
        method="POST",
        path_template="/api/v1/organizations/{org_id}/email-config/test",
        path=f"/api/v1/organizations/{org_id}/email-config/test",
    )


def _call_get_tenant(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``email_config.get_tenant`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "email_config.get_tenant")
    return ManagementCall(
        operation="email_config.get_tenant",
        method="GET",
        path_template="/api/v1/tenants/{tenant_id}/email-config",
        path=f"/api/v1/tenants/{tenant_id}/email-config",
    )


def _call_set_tenant(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.EmailConfigOverride,
) -> ManagementCall:
    """Build the ``email_config.set_tenant`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "email_config.set_tenant")
    return ManagementCall(
        operation="email_config.set_tenant",
        method="PUT",
        path_template="/api/v1/tenants/{tenant_id}/email-config",
        path=f"/api/v1/tenants/{tenant_id}/email-config",
        body=body.to_wire(),
    )


def _call_delete_tenant(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``email_config.delete_tenant`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "email_config.delete_tenant")
    return ManagementCall(
        operation="email_config.delete_tenant",
        method="DELETE",
        path_template="/api/v1/tenants/{tenant_id}/email-config",
        path=f"/api/v1/tenants/{tenant_id}/email-config",
    )


def _call_test_tenant(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``email_config.test_tenant`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "email_config.test_tenant")
    return ManagementCall(
        operation="email_config.test_tenant",
        method="POST",
        path_template="/api/v1/tenants/{tenant_id}/email-config/test",
        path=f"/api/v1/tenants/{tenant_id}/email-config/test",
    )


class EmailConfigApi:
    """The ``email_config`` namespace handle.

    Transactional-mail transport, configurable at organization level and
    overridable per tenant.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def in_org(self, org_id: str) -> EmailConfigApi:
        """Address a different organization than the client's own.

        §27.4 rule 3: the client's ``org_id`` is the default, and a
        platform-admin token legitimately overrides it. Returns a new
        handle; the original is unchanged.
        """
        return EmailConfigApi(self._client, self._scope.with_org(org_id))

    def for_tenant(self, tenant_id: str) -> EmailConfigApi:
        """Address a different tenant than the client's own (§27.4 rule 3).

        Returns a new handle; the original is unchanged.
        """
        return EmailConfigApi(self._client, self._scope.with_tenant(tenant_id))

    def get_org(self) -> models.EmailConfig:
        """``GET /api/v1/organizations/{org_id}/email-config``"""
        raw = send_management(
            self._client,
            _call_get_org(self._client, self._scope),
        )
        return models.EmailConfig.model_validate(raw)

    def set_org(self, body: models.SetOrgEmailConfig) -> models.EmailConfig:
        """``PUT /api/v1/organizations/{org_id}/email-config``

        **This is a replacement, not a patch** (§27.4 rule 5). Every field
        of the body is required, and what you do not carry over from a prior
        read is not preserved -- it is overwritten. Read first, change the
        field you mean, send the whole thing back.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_set_org(self._client, self._scope, body),
        )
        return models.EmailConfig.model_validate(raw)

    def delete_org(self) -> None:
        """``DELETE /api/v1/organizations/{org_id}/email-config``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_delete_org(self._client, self._scope),
        )

    def test_org(self) -> models.EmailTestResult:
        """``POST /api/v1/organizations/{org_id}/email-config/test``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_test_org(self._client, self._scope),
        )
        return models.EmailTestResult.model_validate(raw)

    def get_tenant(self) -> models.EmailConfigOverride:
        """``GET /api/v1/tenants/{tenant_id}/email-config``"""
        raw = send_management(
            self._client,
            _call_get_tenant(self._client, self._scope),
        )
        return models.EmailConfigOverride.model_validate(raw)

    def set_tenant(self, body: models.EmailConfigOverride) -> models.EmailConfigOverride:
        """``PUT /api/v1/tenants/{tenant_id}/email-config``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_set_tenant(self._client, self._scope, body),
        )
        return models.EmailConfigOverride.model_validate(raw)

    def delete_tenant(self) -> None:
        """``DELETE /api/v1/tenants/{tenant_id}/email-config``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_delete_tenant(self._client, self._scope),
        )

    def test_tenant(self) -> models.EmailTestResult:
        """``POST /api/v1/tenants/{tenant_id}/email-config/test``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_test_tenant(self._client, self._scope),
        )
        return models.EmailTestResult.model_validate(raw)


class AsyncEmailConfigApi:
    """The ``email_config`` namespace handle, async form.

    Transactional-mail transport, configurable at organization level and
    overridable per tenant.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def in_org(self, org_id: str) -> AsyncEmailConfigApi:
        """Address a different organization than the client's own.

        §27.4 rule 3: the client's ``org_id`` is the default, and a
        platform-admin token legitimately overrides it. Returns a new
        handle; the original is unchanged.
        """
        return AsyncEmailConfigApi(self._client, self._scope.with_org(org_id))

    def for_tenant(self, tenant_id: str) -> AsyncEmailConfigApi:
        """Address a different tenant than the client's own (§27.4 rule 3).

        Returns a new handle; the original is unchanged.
        """
        return AsyncEmailConfigApi(self._client, self._scope.with_tenant(tenant_id))

    async def get_org(self) -> models.EmailConfig:
        """``GET /api/v1/organizations/{org_id}/email-config``"""
        raw = await send_management_async(
            self._client,
            _call_get_org(self._client, self._scope),
        )
        return models.EmailConfig.model_validate(raw)

    async def set_org(self, body: models.SetOrgEmailConfig) -> models.EmailConfig:
        """``PUT /api/v1/organizations/{org_id}/email-config``

        **This is a replacement, not a patch** (§27.4 rule 5). Every field
        of the body is required, and what you do not carry over from a prior
        read is not preserved -- it is overwritten. Read first, change the
        field you mean, send the whole thing back.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_set_org(self._client, self._scope, body),
        )
        return models.EmailConfig.model_validate(raw)

    async def delete_org(self) -> None:
        """``DELETE /api/v1/organizations/{org_id}/email-config``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_delete_org(self._client, self._scope),
        )

    async def test_org(self) -> models.EmailTestResult:
        """``POST /api/v1/organizations/{org_id}/email-config/test``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_test_org(self._client, self._scope),
        )
        return models.EmailTestResult.model_validate(raw)

    async def get_tenant(self) -> models.EmailConfigOverride:
        """``GET /api/v1/tenants/{tenant_id}/email-config``"""
        raw = await send_management_async(
            self._client,
            _call_get_tenant(self._client, self._scope),
        )
        return models.EmailConfigOverride.model_validate(raw)

    async def set_tenant(self, body: models.EmailConfigOverride) -> models.EmailConfigOverride:
        """``PUT /api/v1/tenants/{tenant_id}/email-config``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_set_tenant(self._client, self._scope, body),
        )
        return models.EmailConfigOverride.model_validate(raw)

    async def delete_tenant(self) -> None:
        """``DELETE /api/v1/tenants/{tenant_id}/email-config``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_delete_tenant(self._client, self._scope),
        )

    async def test_tenant(self) -> models.EmailTestResult:
        """``POST /api/v1/tenants/{tenant_id}/email-config/test``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_test_tenant(self._client, self._scope),
        )
        return models.EmailTestResult.model_validate(raw)
