# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``groups`` management namespace (CONTRACT §27.1).

Named collections of users. Roles assigned to a group are inherited by every
member.
"""

from __future__ import annotations

import builtins
from typing import TYPE_CHECKING

from axiam_sdk.management import models
from axiam_sdk.management._page import (
    Page,
    PageRequest,
    collect_pages,
    collect_pages_async,
    page_of,
    page_query,
)
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
    require_uuid,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_list(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    page: PageRequest | None = None,
) -> ManagementCall:
    """Build the ``groups.list`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="groups.list",
        method="GET",
        path_template="/api/v1/groups",
        path="/api/v1/groups",
        query={**page_query(page)},
    )


def _call_create(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.CreateGroupRequest,
) -> ManagementCall:
    """Build the ``groups.create`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="groups.create",
        method="POST",
        path_template="/api/v1/groups",
        path="/api/v1/groups",
        body=body.to_wire(),
    )


def _call_get(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    group_id: str,
) -> ManagementCall:
    """Build the ``groups.get`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    group_id = require_uuid(group_id, "group_id", "groups.get")
    return ManagementCall(
        operation="groups.get",
        method="GET",
        path_template="/api/v1/groups/{group_id}",
        path=f"/api/v1/groups/{group_id}",
    )


def _call_update(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    group_id: str,
    body: models.UpdateGroup,
) -> ManagementCall:
    """Build the ``groups.update`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    group_id = require_uuid(group_id, "group_id", "groups.update")
    return ManagementCall(
        operation="groups.update",
        method="PUT",
        path_template="/api/v1/groups/{group_id}",
        path=f"/api/v1/groups/{group_id}",
        body=body.to_wire(),
    )


def _call_delete(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    group_id: str,
) -> ManagementCall:
    """Build the ``groups.delete`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    group_id = require_uuid(group_id, "group_id", "groups.delete")
    return ManagementCall(
        operation="groups.delete",
        method="DELETE",
        path_template="/api/v1/groups/{group_id}",
        path=f"/api/v1/groups/{group_id}",
    )


def _call_list_members(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    group_id: str,
    page: PageRequest | None = None,
) -> ManagementCall:
    """Build the ``groups.list_members`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    group_id = require_uuid(group_id, "group_id", "groups.list_members")
    return ManagementCall(
        operation="groups.list_members",
        method="GET",
        path_template="/api/v1/groups/{group_id}/members",
        path=f"/api/v1/groups/{group_id}/members",
        query={**page_query(page)},
    )


def _call_add_member(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    group_id: str,
    body: models.AddMemberRequest,
) -> ManagementCall:
    """Build the ``groups.add_member`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    group_id = require_uuid(group_id, "group_id", "groups.add_member")
    return ManagementCall(
        operation="groups.add_member",
        method="POST",
        path_template="/api/v1/groups/{group_id}/members",
        path=f"/api/v1/groups/{group_id}/members",
        body=body.to_wire(),
    )


def _call_remove_member(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    group_id: str,
    user_id: str,
) -> ManagementCall:
    """Build the ``groups.remove_member`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    group_id = require_uuid(group_id, "group_id", "groups.remove_member")
    user_id = require_uuid(user_id, "user_id", "groups.remove_member")
    return ManagementCall(
        operation="groups.remove_member",
        method="DELETE",
        path_template="/api/v1/groups/{group_id}/members/{user_id}",
        path=f"/api/v1/groups/{group_id}/members/{user_id}",
    )


def _call_list_roles(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    group_id: str,
) -> ManagementCall:
    """Build the ``groups.list_roles`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    group_id = require_uuid(group_id, "group_id", "groups.list_roles")
    return ManagementCall(
        operation="groups.list_roles",
        method="GET",
        path_template="/api/v1/groups/{group_id}/roles",
        path=f"/api/v1/groups/{group_id}/roles",
    )


class GroupsApi:
    """The ``groups`` namespace handle.

    Named collections of users. Roles assigned to a group are inherited by
    every member.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def list(self, page: PageRequest | None = None) -> Page[models.Group]:
        """``GET /api/v1/groups``"""
        raw = send_management(
            self._client,
            _call_list(self._client, self._scope, page),
        )
        return page_of(raw, models.Group)

    def list_all(self, start: PageRequest | None = None) -> builtins.list[models.Group]:
        """Walk ``groups.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return collect_pages(start, lambda p: self.list(p))

    def create(self, body: models.CreateGroupRequest) -> models.Group:
        """``POST /api/v1/groups``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_create(self._client, self._scope, body),
        )
        return models.Group.model_validate(raw)

    def get(self, group_id: str) -> models.Group:
        """``GET /api/v1/groups/{group_id}``"""
        raw = send_management(
            self._client,
            _call_get(self._client, self._scope, group_id),
        )
        return models.Group.model_validate(raw)

    def update(self, group_id: str, body: models.UpdateGroup) -> models.Group:
        """``PUT /api/v1/groups/{group_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_update(self._client, self._scope, group_id, body),
        )
        return models.Group.model_validate(raw)

    def delete(self, group_id: str) -> None:
        """``DELETE /api/v1/groups/{group_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_delete(self._client, self._scope, group_id),
        )

    def list_members(
        self,
        group_id: str,
        page: PageRequest | None = None,
    ) -> Page[models.UserResponse]:
        """``GET /api/v1/groups/{group_id}/members``"""
        raw = send_management(
            self._client,
            _call_list_members(self._client, self._scope, group_id, page),
        )
        return page_of(raw, models.UserResponse)

    def list_members_all(
        self,
        group_id: str,
        start: PageRequest | None = None,
    ) -> builtins.list[models.UserResponse]:
        """Walk ``groups.list_members`` to exhaustion, concatenating every
        page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return collect_pages(start, lambda p: self.list_members(group_id, p))

    def add_member(self, group_id: str, body: models.AddMemberRequest) -> None:
        """``POST /api/v1/groups/{group_id}/members``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_add_member(self._client, self._scope, group_id, body),
        )

    def remove_member(self, group_id: str, user_id: str) -> None:
        """``DELETE /api/v1/groups/{group_id}/members/{user_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_remove_member(self._client, self._scope, group_id, user_id),
        )

    def list_roles(self, group_id: str) -> builtins.list[models.RoleAssignment]:
        """``GET /api/v1/groups/{group_id}/roles``"""
        raw = send_management(
            self._client,
            _call_list_roles(self._client, self._scope, group_id),
        )
        return [models.RoleAssignment.model_validate(item) for item in raw or []]


class AsyncGroupsApi:
    """The ``groups`` namespace handle, async form.

    Named collections of users. Roles assigned to a group are inherited by
    every member.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    async def list(self, page: PageRequest | None = None) -> Page[models.Group]:
        """``GET /api/v1/groups``"""
        raw = await send_management_async(
            self._client,
            _call_list(self._client, self._scope, page),
        )
        return page_of(raw, models.Group)

    async def list_all(self, start: PageRequest | None = None) -> builtins.list[models.Group]:
        """Walk ``groups.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return await collect_pages_async(start, lambda p: self.list(p))

    async def create(self, body: models.CreateGroupRequest) -> models.Group:
        """``POST /api/v1/groups``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_create(self._client, self._scope, body),
        )
        return models.Group.model_validate(raw)

    async def get(self, group_id: str) -> models.Group:
        """``GET /api/v1/groups/{group_id}``"""
        raw = await send_management_async(
            self._client,
            _call_get(self._client, self._scope, group_id),
        )
        return models.Group.model_validate(raw)

    async def update(self, group_id: str, body: models.UpdateGroup) -> models.Group:
        """``PUT /api/v1/groups/{group_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_update(self._client, self._scope, group_id, body),
        )
        return models.Group.model_validate(raw)

    async def delete(self, group_id: str) -> None:
        """``DELETE /api/v1/groups/{group_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_delete(self._client, self._scope, group_id),
        )

    async def list_members(
        self,
        group_id: str,
        page: PageRequest | None = None,
    ) -> Page[models.UserResponse]:
        """``GET /api/v1/groups/{group_id}/members``"""
        raw = await send_management_async(
            self._client,
            _call_list_members(self._client, self._scope, group_id, page),
        )
        return page_of(raw, models.UserResponse)

    async def list_members_all(
        self,
        group_id: str,
        start: PageRequest | None = None,
    ) -> builtins.list[models.UserResponse]:
        """Walk ``groups.list_members`` to exhaustion, concatenating every
        page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return await collect_pages_async(start, lambda p: self.list_members(group_id, p))

    async def add_member(self, group_id: str, body: models.AddMemberRequest) -> None:
        """``POST /api/v1/groups/{group_id}/members``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_add_member(self._client, self._scope, group_id, body),
        )

    async def remove_member(self, group_id: str, user_id: str) -> None:
        """``DELETE /api/v1/groups/{group_id}/members/{user_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_remove_member(self._client, self._scope, group_id, user_id),
        )

    async def list_roles(self, group_id: str) -> builtins.list[models.RoleAssignment]:
        """``GET /api/v1/groups/{group_id}/roles``"""
        raw = await send_management_async(
            self._client,
            _call_list_roles(self._client, self._scope, group_id),
        )
        return [models.RoleAssignment.model_validate(item) for item in raw or []]
