# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``organizations`` management namespace (CONTRACT §27.1).

Organizations an SDK client may read and configure. Creation and deletion
are outside the SDK boundary (§27.0).
"""

from __future__ import annotations

import builtins
from typing import TYPE_CHECKING

from axiam_sdk.management import models
from axiam_sdk.management._page import (
    Page,
    PageRequest,
    collect_pages,
    collect_pages_async,
    page_of,
    page_query,
)
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
    resolve_org,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_list(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    page: PageRequest | None = None,
) -> ManagementCall:
    """Build the ``organizations.list`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="organizations.list",
        method="GET",
        path_template="/api/v1/organizations",
        path="/api/v1/organizations",
        query={**page_query(page)},
    )


def _call_get(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``organizations.get`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    org_id = resolve_org(client, scope, "organizations.get")
    return ManagementCall(
        operation="organizations.get",
        method="GET",
        path_template="/api/v1/organizations/{org_id}",
        path=f"/api/v1/organizations/{org_id}",
    )


def _call_update(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.UpdateOrganizationRequest,
) -> ManagementCall:
    """Build the ``organizations.update`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    org_id = resolve_org(client, scope, "organizations.update")
    return ManagementCall(
        operation="organizations.update",
        method="PUT",
        path_template="/api/v1/organizations/{org_id}",
        path=f"/api/v1/organizations/{org_id}",
        body=body.to_wire(),
    )


class OrganizationsApi:
    """The ``organizations`` namespace handle.

    Organizations an SDK client may read and configure. Creation and
    deletion are outside the SDK boundary (§27.0).

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def in_org(self, org_id: str) -> OrganizationsApi:
        """Address a different organization than the client's own.

        §27.4 rule 3: the client's ``org_id`` is the default, and a
        platform-admin token legitimately overrides it. Returns a new
        handle; the original is unchanged.
        """
        return OrganizationsApi(self._client, self._scope.with_org(org_id))

    def list(self, page: PageRequest | None = None) -> Page[models.Organization]:
        """``GET /api/v1/organizations``"""
        raw = send_management(
            self._client,
            _call_list(self._client, self._scope, page),
        )
        return page_of(raw, models.Organization)

    def list_all(self, start: PageRequest | None = None) -> builtins.list[models.Organization]:
        """Walk ``organizations.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return collect_pages(start, lambda p: self.list(p))

    def get(self) -> models.Organization:
        """``GET /api/v1/organizations/{org_id}``"""
        raw = send_management(
            self._client,
            _call_get(self._client, self._scope),
        )
        return models.Organization.model_validate(raw)

    def update(self, body: models.UpdateOrganizationRequest) -> models.Organization:
        """``PUT /api/v1/organizations/{org_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_update(self._client, self._scope, body),
        )
        return models.Organization.model_validate(raw)


class AsyncOrganizationsApi:
    """The ``organizations`` namespace handle, async form.

    Organizations an SDK client may read and configure. Creation and
    deletion are outside the SDK boundary (§27.0).

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def in_org(self, org_id: str) -> AsyncOrganizationsApi:
        """Address a different organization than the client's own.

        §27.4 rule 3: the client's ``org_id`` is the default, and a
        platform-admin token legitimately overrides it. Returns a new
        handle; the original is unchanged.
        """
        return AsyncOrganizationsApi(self._client, self._scope.with_org(org_id))

    async def list(self, page: PageRequest | None = None) -> Page[models.Organization]:
        """``GET /api/v1/organizations``"""
        raw = await send_management_async(
            self._client,
            _call_list(self._client, self._scope, page),
        )
        return page_of(raw, models.Organization)

    async def list_all(
        self,
        start: PageRequest | None = None,
    ) -> builtins.list[models.Organization]:
        """Walk ``organizations.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return await collect_pages_async(start, lambda p: self.list(p))

    async def get(self) -> models.Organization:
        """``GET /api/v1/organizations/{org_id}``"""
        raw = await send_management_async(
            self._client,
            _call_get(self._client, self._scope),
        )
        return models.Organization.model_validate(raw)

    async def update(self, body: models.UpdateOrganizationRequest) -> models.Organization:
        """``PUT /api/v1/organizations/{org_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_update(self._client, self._scope, body),
        )
        return models.Organization.model_validate(raw)
