# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``pgp_keys`` management namespace (CONTRACT §27.1).

OpenPGP keys used for audit signing and encrypted data export.
"""

from __future__ import annotations

import builtins
from typing import TYPE_CHECKING

from axiam_sdk.management import models
from axiam_sdk.management._page import (
    Page,
    PageRequest,
    collect_pages,
    collect_pages_async,
    page_of,
    page_query,
)
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
    require_uuid,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_list(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    page: PageRequest | None = None,
) -> ManagementCall:
    """Build the ``pgp_keys.list`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="pgp_keys.list",
        method="GET",
        path_template="/api/v1/pgp-keys",
        path="/api/v1/pgp-keys",
        query={**page_query(page)},
    )


def _call_generate(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.CreatePgpKeyRequest,
) -> ManagementCall:
    """Build the ``pgp_keys.generate`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="pgp_keys.generate",
        method="POST",
        path_template="/api/v1/pgp-keys",
        path="/api/v1/pgp-keys",
        body=body.to_wire(),
    )


def _call_get(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    id: str,
) -> ManagementCall:
    """Build the ``pgp_keys.get`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    id = require_uuid(id, "id", "pgp_keys.get")
    return ManagementCall(
        operation="pgp_keys.get",
        method="GET",
        path_template="/api/v1/pgp-keys/{id}",
        path=f"/api/v1/pgp-keys/{id}",
    )


def _call_revoke(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    id: str,
) -> ManagementCall:
    """Build the ``pgp_keys.revoke`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    id = require_uuid(id, "id", "pgp_keys.revoke")
    return ManagementCall(
        operation="pgp_keys.revoke",
        method="POST",
        path_template="/api/v1/pgp-keys/{id}/revoke",
        path=f"/api/v1/pgp-keys/{id}/revoke",
    )


def _call_encrypt(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    id: str,
    body: models.EncryptRequest,
) -> ManagementCall:
    """Build the ``pgp_keys.encrypt`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    id = require_uuid(id, "id", "pgp_keys.encrypt")
    return ManagementCall(
        operation="pgp_keys.encrypt",
        method="POST",
        path_template="/api/v1/pgp-keys/{id}/encrypt",
        path=f"/api/v1/pgp-keys/{id}/encrypt",
        body=body.to_wire(),
    )


def _call_sign_audit_batch(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.SignAuditBatchRequest,
) -> ManagementCall:
    """Build the ``pgp_keys.sign_audit_batch`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="pgp_keys.sign_audit_batch",
        method="POST",
        path_template="/api/v1/pgp-keys/sign-audit-batch",
        path="/api/v1/pgp-keys/sign-audit-batch",
        body=body.to_wire(),
    )


class PgpKeysApi:
    """The ``pgp_keys`` namespace handle.

    OpenPGP keys used for audit signing and encrypted data export.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def list(self, page: PageRequest | None = None) -> Page[models.PgpKey]:
        """``GET /api/v1/pgp-keys``"""
        raw = send_management(
            self._client,
            _call_list(self._client, self._scope, page),
        )
        return page_of(raw, models.PgpKey)

    def list_all(self, start: PageRequest | None = None) -> builtins.list[models.PgpKey]:
        """Walk ``pgp_keys.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return collect_pages(start, lambda p: self.list(p))

    def generate(self, body: models.CreatePgpKeyRequest) -> models.GeneratedPgpKey:
        """``POST /api/v1/pgp-keys``

        **Returns secret material, once.** ``private_key_armored`` is
        returned by this call and by no other; no later ``get`` will return
        it again, and the ``get`` projection has no field where it was.
        Discarding the result destroys the credential (§27.5 rule 3).

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_generate(self._client, self._scope, body),
        )
        return models.GeneratedPgpKey.model_validate(raw)

    def get(self, id: str) -> models.PgpKey:
        """``GET /api/v1/pgp-keys/{id}``"""
        raw = send_management(
            self._client,
            _call_get(self._client, self._scope, id),
        )
        return models.PgpKey.model_validate(raw)

    def revoke(self, id: str) -> None:
        """``POST /api/v1/pgp-keys/{id}/revoke``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_revoke(self._client, self._scope, id),
        )

    def encrypt(self, id: str, body: models.EncryptRequest) -> models.EncryptedExport:
        """``POST /api/v1/pgp-keys/{id}/encrypt``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_encrypt(self._client, self._scope, id, body),
        )
        return models.EncryptedExport.model_validate(raw)

    def sign_audit_batch(self, body: models.SignAuditBatchRequest) -> models.SignedAuditBatch:
        """``POST /api/v1/pgp-keys/sign-audit-batch``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_sign_audit_batch(self._client, self._scope, body),
        )
        return models.SignedAuditBatch.model_validate(raw)


class AsyncPgpKeysApi:
    """The ``pgp_keys`` namespace handle, async form.

    OpenPGP keys used for audit signing and encrypted data export.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    async def list(self, page: PageRequest | None = None) -> Page[models.PgpKey]:
        """``GET /api/v1/pgp-keys``"""
        raw = await send_management_async(
            self._client,
            _call_list(self._client, self._scope, page),
        )
        return page_of(raw, models.PgpKey)

    async def list_all(self, start: PageRequest | None = None) -> builtins.list[models.PgpKey]:
        """Walk ``pgp_keys.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return await collect_pages_async(start, lambda p: self.list(p))

    async def generate(self, body: models.CreatePgpKeyRequest) -> models.GeneratedPgpKey:
        """``POST /api/v1/pgp-keys``

        **Returns secret material, once.** ``private_key_armored`` is
        returned by this call and by no other; no later ``get`` will return
        it again, and the ``get`` projection has no field where it was.
        Discarding the result destroys the credential (§27.5 rule 3).

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_generate(self._client, self._scope, body),
        )
        return models.GeneratedPgpKey.model_validate(raw)

    async def get(self, id: str) -> models.PgpKey:
        """``GET /api/v1/pgp-keys/{id}``"""
        raw = await send_management_async(
            self._client,
            _call_get(self._client, self._scope, id),
        )
        return models.PgpKey.model_validate(raw)

    async def revoke(self, id: str) -> None:
        """``POST /api/v1/pgp-keys/{id}/revoke``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_revoke(self._client, self._scope, id),
        )

    async def encrypt(self, id: str, body: models.EncryptRequest) -> models.EncryptedExport:
        """``POST /api/v1/pgp-keys/{id}/encrypt``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_encrypt(self._client, self._scope, id, body),
        )
        return models.EncryptedExport.model_validate(raw)

    async def sign_audit_batch(self, body: models.SignAuditBatchRequest) -> models.SignedAuditBatch:
        """``POST /api/v1/pgp-keys/sign-audit-batch``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_sign_audit_batch(self._client, self._scope, body),
        )
        return models.SignedAuditBatch.model_validate(raw)
