# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``platform`` management namespace (CONTRACT §27.1).

Deployment-level probes and FIDO metadata state. Unauthenticated where the
server leaves them so.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from axiam_sdk.management import models
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_health(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``platform.health`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="platform.health",
        method="GET",
        path_template="/health",
        path="/health",
    )


def _call_ready(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``platform.ready`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="platform.ready",
        method="GET",
        path_template="/ready",
        path="/ready",
    )


def _call_mds_status(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``platform.mds_status`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="platform.mds_status",
        method="GET",
        path_template="/api/v1/mds/status",
        path="/api/v1/mds/status",
    )


def _call_mds_refresh(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``platform.mds_refresh`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="platform.mds_refresh",
        method="POST",
        path_template="/api/v1/mds/refresh",
        path="/api/v1/mds/refresh",
    )


class PlatformApi:
    """The ``platform`` namespace handle.

    Deployment-level probes and FIDO metadata state. Unauthenticated where
    the server leaves them so.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def health(self) -> models.HealthResponse:
        """``GET /health``"""
        raw = send_management(
            self._client,
            _call_health(self._client, self._scope),
        )
        return models.HealthResponse.model_validate(raw)

    def ready(self) -> models.ReadyResponse:
        """``GET /ready``"""
        raw = send_management(
            self._client,
            _call_ready(self._client, self._scope),
        )
        return models.ReadyResponse.model_validate(raw)

    def mds_status(self) -> models.MdsStatusResponse:
        """``GET /api/v1/mds/status``"""
        raw = send_management(
            self._client,
            _call_mds_status(self._client, self._scope),
        )
        return models.MdsStatusResponse.model_validate(raw)

    def mds_refresh(self) -> models.MdsRefreshOutcome:
        """``POST /api/v1/mds/refresh``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_mds_refresh(self._client, self._scope),
        )
        return models.MdsRefreshOutcomeAdapter.validate_python(raw)


class AsyncPlatformApi:
    """The ``platform`` namespace handle, async form.

    Deployment-level probes and FIDO metadata state. Unauthenticated where
    the server leaves them so.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    async def health(self) -> models.HealthResponse:
        """``GET /health``"""
        raw = await send_management_async(
            self._client,
            _call_health(self._client, self._scope),
        )
        return models.HealthResponse.model_validate(raw)

    async def ready(self) -> models.ReadyResponse:
        """``GET /ready``"""
        raw = await send_management_async(
            self._client,
            _call_ready(self._client, self._scope),
        )
        return models.ReadyResponse.model_validate(raw)

    async def mds_status(self) -> models.MdsStatusResponse:
        """``GET /api/v1/mds/status``"""
        raw = await send_management_async(
            self._client,
            _call_mds_status(self._client, self._scope),
        )
        return models.MdsStatusResponse.model_validate(raw)

    async def mds_refresh(self) -> models.MdsRefreshOutcome:
        """``POST /api/v1/mds/refresh``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_mds_refresh(self._client, self._scope),
        )
        return models.MdsRefreshOutcomeAdapter.validate_python(raw)
