# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``privacy`` management namespace (CONTRACT §27.1).

GDPR self-service: the authenticated account's own export and erasure.
Scoped to the caller, never to another user.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any
from urllib.parse import quote

from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_request_export(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: Any,
) -> ManagementCall:
    """Build the ``privacy.request_export`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="privacy.request_export",
        method="POST",
        path_template="/api/v1/account/export",
        path="/api/v1/account/export",
        body=body,
    )


def _call_download_export(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    token: str,
) -> ManagementCall:
    """Build the ``privacy.download_export`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    token = quote(token, safe="")
    return ManagementCall(
        operation="privacy.download_export",
        method="GET",
        path_template="/api/v1/account/export/{token}",
        path=f"/api/v1/account/export/{token}",
    )


def _call_request_delete(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: Any,
) -> ManagementCall:
    """Build the ``privacy.request_delete`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="privacy.request_delete",
        method="POST",
        path_template="/api/v1/account/delete",
        path="/api/v1/account/delete",
        body=body,
    )


def _call_cancel_delete(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    token: str,
) -> ManagementCall:
    """Build the ``privacy.cancel_delete`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="privacy.cancel_delete",
        method="GET",
        path_template="/api/v1/auth/account/delete/cancel",
        path="/api/v1/auth/account/delete/cancel",
        query={"token": token},
    )


class PrivacyApi:
    """The ``privacy`` namespace handle.

    GDPR self-service: the authenticated account's own export and erasure.
    Scoped to the caller, never to another user.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def request_export(self, body: Any) -> None:
        """``POST /api/v1/account/export``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_request_export(self._client, self._scope, body),
        )

    def download_export(self, token: str) -> None:
        """``GET /api/v1/account/export/{token}``"""
        send_management(
            self._client,
            _call_download_export(self._client, self._scope, token),
        )

    def request_delete(self, body: Any) -> None:
        """``POST /api/v1/account/delete``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_request_delete(self._client, self._scope, body),
        )

    def cancel_delete(self, token: str) -> None:
        """``GET /api/v1/auth/account/delete/cancel``"""
        send_management(
            self._client,
            _call_cancel_delete(self._client, self._scope, token),
        )


class AsyncPrivacyApi:
    """The ``privacy`` namespace handle, async form.

    GDPR self-service: the authenticated account's own export and erasure.
    Scoped to the caller, never to another user.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    async def request_export(self, body: Any) -> None:
        """``POST /api/v1/account/export``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_request_export(self._client, self._scope, body),
        )

    async def download_export(self, token: str) -> None:
        """``GET /api/v1/account/export/{token}``"""
        await send_management_async(
            self._client,
            _call_download_export(self._client, self._scope, token),
        )

    async def request_delete(self, body: Any) -> None:
        """``POST /api/v1/account/delete``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_request_delete(self._client, self._scope, body),
        )

    async def cancel_delete(self, token: str) -> None:
        """``GET /api/v1/auth/account/delete/cancel``"""
        await send_management_async(
            self._client,
            _call_cancel_delete(self._client, self._scope, token),
        )
