# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``reactors`` management namespace (CONTRACT §27.1).

Registration of §22 AMQP extension actors -- the admin surface §22.9
describes, which no SDK could previously reach.
"""

from __future__ import annotations

import builtins
from typing import TYPE_CHECKING

from axiam_sdk.management import models
from axiam_sdk.management._page import (
    Page,
    PageRequest,
    collect_pages,
    collect_pages_async,
    page_of,
    page_query,
)
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
    require_uuid,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_list(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    page: PageRequest | None = None,
) -> ManagementCall:
    """Build the ``reactors.list`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="reactors.list",
        method="GET",
        path_template="/api/v1/reactors",
        path="/api/v1/reactors",
        query={**page_query(page)},
    )


def _call_create(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.CreateReactorRequest,
) -> ManagementCall:
    """Build the ``reactors.create`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="reactors.create",
        method="POST",
        path_template="/api/v1/reactors",
        path="/api/v1/reactors",
        body=body.to_wire(),
    )


def _call_get(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    id: str,
) -> ManagementCall:
    """Build the ``reactors.get`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    id = require_uuid(id, "id", "reactors.get")
    return ManagementCall(
        operation="reactors.get",
        method="GET",
        path_template="/api/v1/reactors/{id}",
        path=f"/api/v1/reactors/{id}",
    )


def _call_update(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    id: str,
    body: models.UpdateReactorRequest,
) -> ManagementCall:
    """Build the ``reactors.update`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    id = require_uuid(id, "id", "reactors.update")
    return ManagementCall(
        operation="reactors.update",
        method="PUT",
        path_template="/api/v1/reactors/{id}",
        path=f"/api/v1/reactors/{id}",
        body=body.to_wire(),
    )


def _call_delete(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    id: str,
) -> ManagementCall:
    """Build the ``reactors.delete`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    id = require_uuid(id, "id", "reactors.delete")
    return ManagementCall(
        operation="reactors.delete",
        method="DELETE",
        path_template="/api/v1/reactors/{id}",
        path=f"/api/v1/reactors/{id}",
    )


def _call_list_events(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``reactors.list_events`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="reactors.list_events",
        method="GET",
        path_template="/api/v1/reactors/events",
        path="/api/v1/reactors/events",
    )


class ReactorsApi:
    """The ``reactors`` namespace handle.

    Registration of §22 AMQP extension actors -- the admin surface §22.9
    describes, which no SDK could previously reach.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def list(self, page: PageRequest | None = None) -> Page[models.ReactorResponse]:
        """``GET /api/v1/reactors``"""
        raw = send_management(
            self._client,
            _call_list(self._client, self._scope, page),
        )
        return page_of(raw, models.ReactorResponse)

    def list_all(self, start: PageRequest | None = None) -> builtins.list[models.ReactorResponse]:
        """Walk ``reactors.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return collect_pages(start, lambda p: self.list(p))

    def create(self, body: models.CreateReactorRequest) -> models.ReactorResponse:
        """``POST /api/v1/reactors``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_create(self._client, self._scope, body),
        )
        return models.ReactorResponse.model_validate(raw)

    def get(self, id: str) -> models.ReactorResponse:
        """``GET /api/v1/reactors/{id}``"""
        raw = send_management(
            self._client,
            _call_get(self._client, self._scope, id),
        )
        return models.ReactorResponse.model_validate(raw)

    def update(self, id: str, body: models.UpdateReactorRequest) -> models.ReactorResponse:
        """``PUT /api/v1/reactors/{id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_update(self._client, self._scope, id, body),
        )
        return models.ReactorResponse.model_validate(raw)

    def delete(self, id: str) -> None:
        """``DELETE /api/v1/reactors/{id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_delete(self._client, self._scope, id),
        )

    def list_events(self) -> builtins.list[models.ReactorEventDescriptor]:
        """``GET /api/v1/reactors/events``"""
        raw = send_management(
            self._client,
            _call_list_events(self._client, self._scope),
        )
        return [models.ReactorEventDescriptor.model_validate(item) for item in raw or []]


class AsyncReactorsApi:
    """The ``reactors`` namespace handle, async form.

    Registration of §22 AMQP extension actors -- the admin surface §22.9
    describes, which no SDK could previously reach.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    async def list(self, page: PageRequest | None = None) -> Page[models.ReactorResponse]:
        """``GET /api/v1/reactors``"""
        raw = await send_management_async(
            self._client,
            _call_list(self._client, self._scope, page),
        )
        return page_of(raw, models.ReactorResponse)

    async def list_all(
        self,
        start: PageRequest | None = None,
    ) -> builtins.list[models.ReactorResponse]:
        """Walk ``reactors.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return await collect_pages_async(start, lambda p: self.list(p))

    async def create(self, body: models.CreateReactorRequest) -> models.ReactorResponse:
        """``POST /api/v1/reactors``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_create(self._client, self._scope, body),
        )
        return models.ReactorResponse.model_validate(raw)

    async def get(self, id: str) -> models.ReactorResponse:
        """``GET /api/v1/reactors/{id}``"""
        raw = await send_management_async(
            self._client,
            _call_get(self._client, self._scope, id),
        )
        return models.ReactorResponse.model_validate(raw)

    async def update(self, id: str, body: models.UpdateReactorRequest) -> models.ReactorResponse:
        """``PUT /api/v1/reactors/{id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_update(self._client, self._scope, id, body),
        )
        return models.ReactorResponse.model_validate(raw)

    async def delete(self, id: str) -> None:
        """``DELETE /api/v1/reactors/{id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_delete(self._client, self._scope, id),
        )

    async def list_events(self) -> builtins.list[models.ReactorEventDescriptor]:
        """``GET /api/v1/reactors/events``"""
        raw = await send_management_async(
            self._client,
            _call_list_events(self._client, self._scope),
        )
        return [models.ReactorEventDescriptor.model_validate(item) for item in raw or []]
