# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``resources`` management namespace (CONTRACT §27.1).

The resource hierarchy role assignments cascade down.
"""

from __future__ import annotations

import builtins
from typing import TYPE_CHECKING

from axiam_sdk.management import models
from axiam_sdk.management._page import (
    Page,
    PageRequest,
    collect_pages,
    collect_pages_async,
    page_of,
    page_query,
)
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
    require_uuid,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_list(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    page: PageRequest | None = None,
) -> ManagementCall:
    """Build the ``resources.list`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="resources.list",
        method="GET",
        path_template="/api/v1/resources",
        path="/api/v1/resources",
        query={**page_query(page)},
    )


def _call_create(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.CreateResourceRequest,
) -> ManagementCall:
    """Build the ``resources.create`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="resources.create",
        method="POST",
        path_template="/api/v1/resources",
        path="/api/v1/resources",
        body=body.to_wire(),
    )


def _call_get(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    resource_id: str,
) -> ManagementCall:
    """Build the ``resources.get`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    resource_id = require_uuid(resource_id, "resource_id", "resources.get")
    return ManagementCall(
        operation="resources.get",
        method="GET",
        path_template="/api/v1/resources/{resource_id}",
        path=f"/api/v1/resources/{resource_id}",
    )


def _call_update(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    resource_id: str,
    body: models.UpdateResourceRequest,
) -> ManagementCall:
    """Build the ``resources.update`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    resource_id = require_uuid(resource_id, "resource_id", "resources.update")
    return ManagementCall(
        operation="resources.update",
        method="PUT",
        path_template="/api/v1/resources/{resource_id}",
        path=f"/api/v1/resources/{resource_id}",
        body=body.to_wire(),
    )


def _call_delete(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    resource_id: str,
) -> ManagementCall:
    """Build the ``resources.delete`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    resource_id = require_uuid(resource_id, "resource_id", "resources.delete")
    return ManagementCall(
        operation="resources.delete",
        method="DELETE",
        path_template="/api/v1/resources/{resource_id}",
        path=f"/api/v1/resources/{resource_id}",
    )


def _call_list_children(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    resource_id: str,
) -> ManagementCall:
    """Build the ``resources.list_children`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    resource_id = require_uuid(resource_id, "resource_id", "resources.list_children")
    return ManagementCall(
        operation="resources.list_children",
        method="GET",
        path_template="/api/v1/resources/{resource_id}/children",
        path=f"/api/v1/resources/{resource_id}/children",
    )


def _call_list_ancestors(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    resource_id: str,
) -> ManagementCall:
    """Build the ``resources.list_ancestors`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    resource_id = require_uuid(resource_id, "resource_id", "resources.list_ancestors")
    return ManagementCall(
        operation="resources.list_ancestors",
        method="GET",
        path_template="/api/v1/resources/{resource_id}/ancestors",
        path=f"/api/v1/resources/{resource_id}/ancestors",
    )


class ResourcesApi:
    """The ``resources`` namespace handle.

    The resource hierarchy role assignments cascade down.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def list(self, page: PageRequest | None = None) -> Page[models.Resource]:
        """``GET /api/v1/resources``"""
        raw = send_management(
            self._client,
            _call_list(self._client, self._scope, page),
        )
        return page_of(raw, models.Resource)

    def list_all(self, start: PageRequest | None = None) -> builtins.list[models.Resource]:
        """Walk ``resources.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return collect_pages(start, lambda p: self.list(p))

    def create(self, body: models.CreateResourceRequest) -> models.Resource:
        """``POST /api/v1/resources``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_create(self._client, self._scope, body),
        )
        return models.Resource.model_validate(raw)

    def get(self, resource_id: str) -> models.Resource:
        """``GET /api/v1/resources/{resource_id}``"""
        raw = send_management(
            self._client,
            _call_get(self._client, self._scope, resource_id),
        )
        return models.Resource.model_validate(raw)

    def update(self, resource_id: str, body: models.UpdateResourceRequest) -> models.Resource:
        """``PUT /api/v1/resources/{resource_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_update(self._client, self._scope, resource_id, body),
        )
        return models.Resource.model_validate(raw)

    def delete(self, resource_id: str) -> None:
        """``DELETE /api/v1/resources/{resource_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_delete(self._client, self._scope, resource_id),
        )

    def list_children(self, resource_id: str) -> builtins.list[models.Resource]:
        """``GET /api/v1/resources/{resource_id}/children``"""
        raw = send_management(
            self._client,
            _call_list_children(self._client, self._scope, resource_id),
        )
        return [models.Resource.model_validate(item) for item in raw or []]

    def list_ancestors(self, resource_id: str) -> builtins.list[models.Resource]:
        """``GET /api/v1/resources/{resource_id}/ancestors``"""
        raw = send_management(
            self._client,
            _call_list_ancestors(self._client, self._scope, resource_id),
        )
        return [models.Resource.model_validate(item) for item in raw or []]


class AsyncResourcesApi:
    """The ``resources`` namespace handle, async form.

    The resource hierarchy role assignments cascade down.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    async def list(self, page: PageRequest | None = None) -> Page[models.Resource]:
        """``GET /api/v1/resources``"""
        raw = await send_management_async(
            self._client,
            _call_list(self._client, self._scope, page),
        )
        return page_of(raw, models.Resource)

    async def list_all(self, start: PageRequest | None = None) -> builtins.list[models.Resource]:
        """Walk ``resources.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return await collect_pages_async(start, lambda p: self.list(p))

    async def create(self, body: models.CreateResourceRequest) -> models.Resource:
        """``POST /api/v1/resources``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_create(self._client, self._scope, body),
        )
        return models.Resource.model_validate(raw)

    async def get(self, resource_id: str) -> models.Resource:
        """``GET /api/v1/resources/{resource_id}``"""
        raw = await send_management_async(
            self._client,
            _call_get(self._client, self._scope, resource_id),
        )
        return models.Resource.model_validate(raw)

    async def update(self, resource_id: str, body: models.UpdateResourceRequest) -> models.Resource:
        """``PUT /api/v1/resources/{resource_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_update(self._client, self._scope, resource_id, body),
        )
        return models.Resource.model_validate(raw)

    async def delete(self, resource_id: str) -> None:
        """``DELETE /api/v1/resources/{resource_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_delete(self._client, self._scope, resource_id),
        )

    async def list_children(self, resource_id: str) -> builtins.list[models.Resource]:
        """``GET /api/v1/resources/{resource_id}/children``"""
        raw = await send_management_async(
            self._client,
            _call_list_children(self._client, self._scope, resource_id),
        )
        return [models.Resource.model_validate(item) for item in raw or []]

    async def list_ancestors(self, resource_id: str) -> builtins.list[models.Resource]:
        """``GET /api/v1/resources/{resource_id}/ancestors``"""
        raw = await send_management_async(
            self._client,
            _call_list_ancestors(self._client, self._scope, resource_id),
        )
        return [models.Resource.model_validate(item) for item in raw or []]
