# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``saml`` management namespace (CONTRACT §27.1).

A tenant's SAML 2.0 identity provider (CONTRACT §29): the registry of
service providers, the import of an SP's metadata into a *draft*
registration (never a write), and the lifecycle of the IdP signing
credential. The protocol itself -- single sign-on, single logout, the IdP
metadata document -- is browser and SP-to-IdP surface under
/saml/v2/{tenant_id}, an SP's own SAML library speaks to it, and it is not
in this registry.
"""

from __future__ import annotations

import builtins
from typing import TYPE_CHECKING

from axiam_sdk.management import models
from axiam_sdk.management._page import (
    Page,
    PageRequest,
    collect_pages,
    collect_pages_async,
    page_of,
    page_query,
)
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
    require_uuid,
    resolve_tenant,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_get_idp(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``saml.get_idp`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "saml.get_idp")
    return ManagementCall(
        operation="saml.get_idp",
        method="GET",
        path_template="/api/v1/tenants/{tenant_id}/saml/idp",
        path=f"/api/v1/tenants/{tenant_id}/saml/idp",
    )


def _call_list_service_providers(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    page: PageRequest | None = None,
) -> ManagementCall:
    """Build the ``saml.list_service_providers`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "saml.list_service_providers")
    return ManagementCall(
        operation="saml.list_service_providers",
        method="GET",
        path_template="/api/v1/tenants/{tenant_id}/saml/service-providers",
        path=f"/api/v1/tenants/{tenant_id}/saml/service-providers",
        query={**page_query(page)},
    )


def _call_create_service_provider(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.SamlServiceProviderInput,
) -> ManagementCall:
    """Build the ``saml.create_service_provider`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "saml.create_service_provider")
    return ManagementCall(
        operation="saml.create_service_provider",
        method="POST",
        path_template="/api/v1/tenants/{tenant_id}/saml/service-providers",
        path=f"/api/v1/tenants/{tenant_id}/saml/service-providers",
        body=body.to_wire(),
    )


def _call_get_service_provider(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    sp_id: str,
) -> ManagementCall:
    """Build the ``saml.get_service_provider`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "saml.get_service_provider")
    sp_id = require_uuid(sp_id, "sp_id", "saml.get_service_provider")
    return ManagementCall(
        operation="saml.get_service_provider",
        method="GET",
        path_template="/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}",
        path=f"/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}",
    )


def _call_update_service_provider(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    sp_id: str,
    body: models.SamlServiceProviderInput,
) -> ManagementCall:
    """Build the ``saml.update_service_provider`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "saml.update_service_provider")
    sp_id = require_uuid(sp_id, "sp_id", "saml.update_service_provider")
    return ManagementCall(
        operation="saml.update_service_provider",
        method="PUT",
        path_template="/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}",
        path=f"/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}",
        body=body.to_wire(),
    )


def _call_delete_service_provider(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    sp_id: str,
) -> ManagementCall:
    """Build the ``saml.delete_service_provider`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "saml.delete_service_provider")
    sp_id = require_uuid(sp_id, "sp_id", "saml.delete_service_provider")
    return ManagementCall(
        operation="saml.delete_service_provider",
        method="DELETE",
        path_template="/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}",
        path=f"/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}",
    )


def _call_parse_sp_metadata(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.ParseSamlSpMetadata,
) -> ManagementCall:
    """Build the ``saml.parse_sp_metadata`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "saml.parse_sp_metadata")
    return ManagementCall(
        operation="saml.parse_sp_metadata",
        method="POST",
        path_template="/api/v1/tenants/{tenant_id}/saml/parse-sp-metadata",
        path=f"/api/v1/tenants/{tenant_id}/saml/parse-sp-metadata",
        body=body.to_wire(),
    )


def _call_list_idp_credentials(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``saml.list_idp_credentials`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "saml.list_idp_credentials")
    return ManagementCall(
        operation="saml.list_idp_credentials",
        method="GET",
        path_template="/api/v1/tenants/{tenant_id}/saml/idp-credentials",
        path=f"/api/v1/tenants/{tenant_id}/saml/idp-credentials",
    )


def _call_issue_idp_credential(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.IssueSamlIdpCredential,
) -> ManagementCall:
    """Build the ``saml.issue_idp_credential`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "saml.issue_idp_credential")
    return ManagementCall(
        operation="saml.issue_idp_credential",
        method="POST",
        path_template="/api/v1/tenants/{tenant_id}/saml/idp-credentials",
        path=f"/api/v1/tenants/{tenant_id}/saml/idp-credentials",
        body=body.to_wire(),
    )


def _call_promote_idp_credential(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    credential_id: str,
) -> ManagementCall:
    """Build the ``saml.promote_idp_credential`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "saml.promote_idp_credential")
    credential_id = require_uuid(credential_id, "credential_id", "saml.promote_idp_credential")
    return ManagementCall(
        operation="saml.promote_idp_credential",
        method="POST",
        path_template="/api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/promote",
        path=f"/api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/promote",
    )


def _call_retire_idp_credential(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    credential_id: str,
) -> ManagementCall:
    """Build the ``saml.retire_idp_credential`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "saml.retire_idp_credential")
    credential_id = require_uuid(credential_id, "credential_id", "saml.retire_idp_credential")
    return ManagementCall(
        operation="saml.retire_idp_credential",
        method="POST",
        path_template="/api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/retire",
        path=f"/api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/retire",
    )


class SamlApi:
    """The ``saml`` namespace handle.

    A tenant's SAML 2.0 identity provider (CONTRACT §29): the registry of
    service providers, the import of an SP's metadata into a *draft*
    registration (never a write), and the lifecycle of the IdP signing
    credential. The protocol itself -- single sign-on, single logout, the
    IdP metadata document -- is browser and SP-to-IdP surface under
    /saml/v2/{tenant_id}, an SP's own SAML library speaks to it, and it is
    not in this registry.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def for_tenant(self, tenant_id: str) -> SamlApi:
        """Address a different tenant than the client's own (§27.4 rule 3).

        Returns a new handle; the original is unchanged.
        """
        return SamlApi(self._client, self._scope.with_tenant(tenant_id))

    def get_idp(self) -> models.SamlIdpInfo:
        """``GET /api/v1/tenants/{tenant_id}/saml/idp``"""
        raw = send_management(
            self._client,
            _call_get_idp(self._client, self._scope),
        )
        return models.SamlIdpInfo.model_validate(raw)

    def list_service_providers(
        self,
        page: PageRequest | None = None,
    ) -> Page[models.SamlServiceProvider]:
        """``GET /api/v1/tenants/{tenant_id}/saml/service-providers``"""
        raw = send_management(
            self._client,
            _call_list_service_providers(self._client, self._scope, page),
        )
        return page_of(raw, models.SamlServiceProvider)

    def list_service_providers_all(
        self,
        start: PageRequest | None = None,
    ) -> builtins.list[models.SamlServiceProvider]:
        """Walk ``saml.list_service_providers`` to exhaustion, concatenating
        every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return collect_pages(start, lambda p: self.list_service_providers(p))

    def create_service_provider(
        self,
        body: models.SamlServiceProviderInput,
    ) -> models.SamlServiceProvider:
        """``POST /api/v1/tenants/{tenant_id}/saml/service-providers``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_create_service_provider(self._client, self._scope, body),
        )
        return models.SamlServiceProvider.model_validate(raw)

    def get_service_provider(self, sp_id: str) -> models.SamlServiceProvider:
        """``GET /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}``"""
        raw = send_management(
            self._client,
            _call_get_service_provider(self._client, self._scope, sp_id),
        )
        return models.SamlServiceProvider.model_validate(raw)

    def update_service_provider(
        self,
        sp_id: str,
        body: models.SamlServiceProviderInput,
    ) -> models.SamlServiceProvider:
        """``PUT /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}``

        **This is a replacement, not a patch** (§27.4 rule 5). Every field
        of the body is required, and what you do not carry over from a prior
        read is not preserved -- it is overwritten. Read first, change the
        field you mean, send the whole thing back.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_update_service_provider(self._client, self._scope, sp_id, body),
        )
        return models.SamlServiceProvider.model_validate(raw)

    def delete_service_provider(self, sp_id: str) -> None:
        """``DELETE
        /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_delete_service_provider(self._client, self._scope, sp_id),
        )

    def parse_sp_metadata(self, body: models.ParseSamlSpMetadata) -> models.SamlSpMetadataDraft:
        """``POST /api/v1/tenants/{tenant_id}/saml/parse-sp-metadata``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_parse_sp_metadata(self._client, self._scope, body),
        )
        return models.SamlSpMetadataDraft.model_validate(raw)

    def list_idp_credentials(self) -> builtins.list[models.SamlIdpCredential]:
        """``GET /api/v1/tenants/{tenant_id}/saml/idp-credentials``"""
        raw = send_management(
            self._client,
            _call_list_idp_credentials(self._client, self._scope),
        )
        return [models.SamlIdpCredential.model_validate(item) for item in raw or []]

    def issue_idp_credential(self, body: models.IssueSamlIdpCredential) -> models.SamlIdpCredential:
        """``POST /api/v1/tenants/{tenant_id}/saml/idp-credentials``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_issue_idp_credential(self._client, self._scope, body),
        )
        return models.SamlIdpCredential.model_validate(raw)

    def promote_idp_credential(self, credential_id: str) -> models.SamlIdpCredentialPromotion:
        """``POST
        /api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/promote``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_promote_idp_credential(self._client, self._scope, credential_id),
        )
        return models.SamlIdpCredentialPromotion.model_validate(raw)

    def retire_idp_credential(self, credential_id: str) -> models.SamlIdpCredential:
        """``POST
        /api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/retire``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_retire_idp_credential(self._client, self._scope, credential_id),
        )
        return models.SamlIdpCredential.model_validate(raw)


class AsyncSamlApi:
    """The ``saml`` namespace handle, async form.

    A tenant's SAML 2.0 identity provider (CONTRACT §29): the registry of
    service providers, the import of an SP's metadata into a *draft*
    registration (never a write), and the lifecycle of the IdP signing
    credential. The protocol itself -- single sign-on, single logout, the
    IdP metadata document -- is browser and SP-to-IdP surface under
    /saml/v2/{tenant_id}, an SP's own SAML library speaks to it, and it is
    not in this registry.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def for_tenant(self, tenant_id: str) -> AsyncSamlApi:
        """Address a different tenant than the client's own (§27.4 rule 3).

        Returns a new handle; the original is unchanged.
        """
        return AsyncSamlApi(self._client, self._scope.with_tenant(tenant_id))

    async def get_idp(self) -> models.SamlIdpInfo:
        """``GET /api/v1/tenants/{tenant_id}/saml/idp``"""
        raw = await send_management_async(
            self._client,
            _call_get_idp(self._client, self._scope),
        )
        return models.SamlIdpInfo.model_validate(raw)

    async def list_service_providers(
        self,
        page: PageRequest | None = None,
    ) -> Page[models.SamlServiceProvider]:
        """``GET /api/v1/tenants/{tenant_id}/saml/service-providers``"""
        raw = await send_management_async(
            self._client,
            _call_list_service_providers(self._client, self._scope, page),
        )
        return page_of(raw, models.SamlServiceProvider)

    async def list_service_providers_all(
        self,
        start: PageRequest | None = None,
    ) -> builtins.list[models.SamlServiceProvider]:
        """Walk ``saml.list_service_providers`` to exhaustion, concatenating
        every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return await collect_pages_async(start, lambda p: self.list_service_providers(p))

    async def create_service_provider(
        self,
        body: models.SamlServiceProviderInput,
    ) -> models.SamlServiceProvider:
        """``POST /api/v1/tenants/{tenant_id}/saml/service-providers``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_create_service_provider(self._client, self._scope, body),
        )
        return models.SamlServiceProvider.model_validate(raw)

    async def get_service_provider(self, sp_id: str) -> models.SamlServiceProvider:
        """``GET /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}``"""
        raw = await send_management_async(
            self._client,
            _call_get_service_provider(self._client, self._scope, sp_id),
        )
        return models.SamlServiceProvider.model_validate(raw)

    async def update_service_provider(
        self,
        sp_id: str,
        body: models.SamlServiceProviderInput,
    ) -> models.SamlServiceProvider:
        """``PUT /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}``

        **This is a replacement, not a patch** (§27.4 rule 5). Every field
        of the body is required, and what you do not carry over from a prior
        read is not preserved -- it is overwritten. Read first, change the
        field you mean, send the whole thing back.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_update_service_provider(self._client, self._scope, sp_id, body),
        )
        return models.SamlServiceProvider.model_validate(raw)

    async def delete_service_provider(self, sp_id: str) -> None:
        """``DELETE
        /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_delete_service_provider(self._client, self._scope, sp_id),
        )

    async def parse_sp_metadata(
        self,
        body: models.ParseSamlSpMetadata,
    ) -> models.SamlSpMetadataDraft:
        """``POST /api/v1/tenants/{tenant_id}/saml/parse-sp-metadata``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_parse_sp_metadata(self._client, self._scope, body),
        )
        return models.SamlSpMetadataDraft.model_validate(raw)

    async def list_idp_credentials(self) -> builtins.list[models.SamlIdpCredential]:
        """``GET /api/v1/tenants/{tenant_id}/saml/idp-credentials``"""
        raw = await send_management_async(
            self._client,
            _call_list_idp_credentials(self._client, self._scope),
        )
        return [models.SamlIdpCredential.model_validate(item) for item in raw or []]

    async def issue_idp_credential(
        self,
        body: models.IssueSamlIdpCredential,
    ) -> models.SamlIdpCredential:
        """``POST /api/v1/tenants/{tenant_id}/saml/idp-credentials``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_issue_idp_credential(self._client, self._scope, body),
        )
        return models.SamlIdpCredential.model_validate(raw)

    async def promote_idp_credential(self, credential_id: str) -> models.SamlIdpCredentialPromotion:
        """``POST
        /api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/promote``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_promote_idp_credential(self._client, self._scope, credential_id),
        )
        return models.SamlIdpCredentialPromotion.model_validate(raw)

    async def retire_idp_credential(self, credential_id: str) -> models.SamlIdpCredential:
        """``POST
        /api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/retire``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_retire_idp_credential(self._client, self._scope, credential_id),
        )
        return models.SamlIdpCredential.model_validate(raw)
