# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``scim_targets`` management namespace (CONTRACT §27.1).

A tenant's outbound SCIM targets (CONTRACT §31): the downstream SCIM 2.0
service providers AXIAM pushes the tenant's users and groups to, each with
its delivery state. The credential AXIAM pushes with is write-only. Deleting
a target does not deprovision anything downstream.
"""

from __future__ import annotations

import builtins
from typing import TYPE_CHECKING

from axiam_sdk.management import models
from axiam_sdk.management._page import (
    Page,
    PageRequest,
    collect_pages,
    collect_pages_async,
    page_of,
    page_query,
)
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
    require_uuid,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_list(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    page: PageRequest | None = None,
) -> ManagementCall:
    """Build the ``scim_targets.list`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="scim_targets.list",
        method="GET",
        path_template="/api/v1/scim-targets",
        path="/api/v1/scim-targets",
        query={**page_query(page)},
    )


def _call_create(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.ScimTargetInput,
) -> ManagementCall:
    """Build the ``scim_targets.create`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="scim_targets.create",
        method="POST",
        path_template="/api/v1/scim-targets",
        path="/api/v1/scim-targets",
        body=body.to_wire(),
    )


def _call_get(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    id: str,
) -> ManagementCall:
    """Build the ``scim_targets.get`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    id = require_uuid(id, "id", "scim_targets.get")
    return ManagementCall(
        operation="scim_targets.get",
        method="GET",
        path_template="/api/v1/scim-targets/{id}",
        path=f"/api/v1/scim-targets/{id}",
    )


def _call_update(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    id: str,
    body: models.ScimTargetInput,
) -> ManagementCall:
    """Build the ``scim_targets.update`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    id = require_uuid(id, "id", "scim_targets.update")
    return ManagementCall(
        operation="scim_targets.update",
        method="PUT",
        path_template="/api/v1/scim-targets/{id}",
        path=f"/api/v1/scim-targets/{id}",
        body=body.to_wire(),
    )


def _call_delete(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    id: str,
) -> ManagementCall:
    """Build the ``scim_targets.delete`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    id = require_uuid(id, "id", "scim_targets.delete")
    return ManagementCall(
        operation="scim_targets.delete",
        method="DELETE",
        path_template="/api/v1/scim-targets/{id}",
        path=f"/api/v1/scim-targets/{id}",
    )


def _call_reconcile(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    id: str,
) -> ManagementCall:
    """Build the ``scim_targets.reconcile`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    id = require_uuid(id, "id", "scim_targets.reconcile")
    return ManagementCall(
        operation="scim_targets.reconcile",
        method="POST",
        path_template="/api/v1/scim-targets/{id}/reconcile",
        path=f"/api/v1/scim-targets/{id}/reconcile",
    )


class ScimTargetsApi:
    """The ``scim_targets`` namespace handle.

    A tenant's outbound SCIM targets (CONTRACT §31): the downstream SCIM 2.0
    service providers AXIAM pushes the tenant's users and groups to, each
    with its delivery state. The credential AXIAM pushes with is write-only.
    Deleting a target does not deprovision anything downstream.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def list(self, page: PageRequest | None = None) -> Page[models.ScimTargetResponse]:
        """``GET /api/v1/scim-targets``"""
        raw = send_management(
            self._client,
            _call_list(self._client, self._scope, page),
        )
        return page_of(raw, models.ScimTargetResponse)

    def list_all(
        self,
        start: PageRequest | None = None,
    ) -> builtins.list[models.ScimTargetResponse]:
        """Walk ``scim_targets.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return collect_pages(start, lambda p: self.list(p))

    def create(self, body: models.ScimTargetInput) -> models.ScimTargetResponse:
        """``POST /api/v1/scim-targets``

        ``credential`` is required here (§31.3 rule 2). It is write-only: no
        response ever carries it, and the SDK keeps no copy. **The
        credential is bound to its URL** (§31.3 rule 2): a later ``update``
        that changes ``base_url`` of a bearer target, ``auth.token_url`` or
        ``base_url`` of a client-credentials target, or ``auth.type``, must
        carry ``credential`` again or is refused ``400`` -- so keep the
        credential where you can supply it; the SDK holds none to re-send.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_create(self._client, self._scope, body),
        )
        return models.ScimTargetResponse.model_validate(raw)

    def get(self, id: str) -> models.ScimTargetResponse:
        """``GET /api/v1/scim-targets/{id}``"""
        raw = send_management(
            self._client,
            _call_get(self._client, self._scope, id),
        )
        return models.ScimTargetResponse.model_validate(raw)

    def update(self, id: str, body: models.ScimTargetInput) -> models.ScimTargetResponse:
        """``PUT /api/v1/scim-targets/{id}``

        **The credential is bound to its URL** (§31.3 rule 2): absent
        ``credential`` keeps the stored one -- except that changing
        ``base_url`` of a bearer target, ``auth.token_url`` or ``base_url``
        of a client-credentials target, or ``auth.type``, without
        ``credential`` in the same write is refused ``400`` and changes
        nothing. The SDK holds no credential to re-send. Every other member
        left out takes its default
        (:func:`~axiam_sdk.management.scim_target_input` turns a read into
        this body). An update overtaken by another administrator's write is
        ``409`` (§31.3 rule 4): reload, then retry yourself.

        **This is a replacement, not a patch** (§27.4 rule 5). The body's
        type says which members are required; an optional member you leave
        out is not kept -- the server applies its default -- so what you do
        not carry over from a prior read is not preserved, it is overwritten
        (a write-only secret is the exception: absent keeps it). Read first,
        change the field you mean, send the whole thing back.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_update(self._client, self._scope, id, body),
        )
        return models.ScimTargetResponse.model_validate(raw)

    def delete(self, id: str) -> None:
        """``DELETE /api/v1/scim-targets/{id}``

        **Deprovisions nothing downstream** (§31.3 rule 8): the users and
        groups AXIAM created in the service provider stay there, and AXIAM
        no longer knows them. To remove them, set ``deprovision`` to
        ``delete``, let AXIAM push, and only then delete the target.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_delete(self._client, self._scope, id),
        )

    def reconcile(self, id: str) -> models.ScimReconcileAccepted:
        """``POST /api/v1/scim-targets/{id}/reconcile``

        Starts a reconciliation in the background and answers ``202``; its
        outcome is on the target's ``state`` (§31.3 rule 7). ``409`` while a
        run holds the claim, within five minutes of the last one, or for a
        disabled target.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_reconcile(self._client, self._scope, id),
        )
        return models.ScimReconcileAccepted.model_validate(raw)


class AsyncScimTargetsApi:
    """The ``scim_targets`` namespace handle, async form.

    A tenant's outbound SCIM targets (CONTRACT §31): the downstream SCIM 2.0
    service providers AXIAM pushes the tenant's users and groups to, each
    with its delivery state. The credential AXIAM pushes with is write-only.
    Deleting a target does not deprovision anything downstream.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    async def list(self, page: PageRequest | None = None) -> Page[models.ScimTargetResponse]:
        """``GET /api/v1/scim-targets``"""
        raw = await send_management_async(
            self._client,
            _call_list(self._client, self._scope, page),
        )
        return page_of(raw, models.ScimTargetResponse)

    async def list_all(
        self,
        start: PageRequest | None = None,
    ) -> builtins.list[models.ScimTargetResponse]:
        """Walk ``scim_targets.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return await collect_pages_async(start, lambda p: self.list(p))

    async def create(self, body: models.ScimTargetInput) -> models.ScimTargetResponse:
        """``POST /api/v1/scim-targets``

        ``credential`` is required here (§31.3 rule 2). It is write-only: no
        response ever carries it, and the SDK keeps no copy. **The
        credential is bound to its URL** (§31.3 rule 2): a later ``update``
        that changes ``base_url`` of a bearer target, ``auth.token_url`` or
        ``base_url`` of a client-credentials target, or ``auth.type``, must
        carry ``credential`` again or is refused ``400`` -- so keep the
        credential where you can supply it; the SDK holds none to re-send.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_create(self._client, self._scope, body),
        )
        return models.ScimTargetResponse.model_validate(raw)

    async def get(self, id: str) -> models.ScimTargetResponse:
        """``GET /api/v1/scim-targets/{id}``"""
        raw = await send_management_async(
            self._client,
            _call_get(self._client, self._scope, id),
        )
        return models.ScimTargetResponse.model_validate(raw)

    async def update(self, id: str, body: models.ScimTargetInput) -> models.ScimTargetResponse:
        """``PUT /api/v1/scim-targets/{id}``

        **The credential is bound to its URL** (§31.3 rule 2): absent
        ``credential`` keeps the stored one -- except that changing
        ``base_url`` of a bearer target, ``auth.token_url`` or ``base_url``
        of a client-credentials target, or ``auth.type``, without
        ``credential`` in the same write is refused ``400`` and changes
        nothing. The SDK holds no credential to re-send. Every other member
        left out takes its default
        (:func:`~axiam_sdk.management.scim_target_input` turns a read into
        this body). An update overtaken by another administrator's write is
        ``409`` (§31.3 rule 4): reload, then retry yourself.

        **This is a replacement, not a patch** (§27.4 rule 5). The body's
        type says which members are required; an optional member you leave
        out is not kept -- the server applies its default -- so what you do
        not carry over from a prior read is not preserved, it is overwritten
        (a write-only secret is the exception: absent keeps it). Read first,
        change the field you mean, send the whole thing back.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_update(self._client, self._scope, id, body),
        )
        return models.ScimTargetResponse.model_validate(raw)

    async def delete(self, id: str) -> None:
        """``DELETE /api/v1/scim-targets/{id}``

        **Deprovisions nothing downstream** (§31.3 rule 8): the users and
        groups AXIAM created in the service provider stay there, and AXIAM
        no longer knows them. To remove them, set ``deprovision`` to
        ``delete``, let AXIAM push, and only then delete the target.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_delete(self._client, self._scope, id),
        )

    async def reconcile(self, id: str) -> models.ScimReconcileAccepted:
        """``POST /api/v1/scim-targets/{id}/reconcile``

        Starts a reconciliation in the background and answers ``202``; its
        outcome is on the target's ``state`` (§31.3 rule 7). ``409`` while a
        run holds the claim, within five minutes of the last one, or for a
        disabled target.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_reconcile(self._client, self._scope, id),
        )
        return models.ScimReconcileAccepted.model_validate(raw)
