# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``scim_tokens`` management namespace (CONTRACT §27.1).

Bearer tokens for the SCIM 2.0 provisioning endpoint.
"""

from __future__ import annotations

import builtins
from typing import TYPE_CHECKING

from axiam_sdk.management import models
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
    require_uuid,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_list(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``scim_tokens.list`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="scim_tokens.list",
        method="GET",
        path_template="/api/v1/scim-tokens",
        path="/api/v1/scim-tokens",
    )


def _call_create(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.CreateScimTokenRequest,
) -> ManagementCall:
    """Build the ``scim_tokens.create`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="scim_tokens.create",
        method="POST",
        path_template="/api/v1/scim-tokens",
        path="/api/v1/scim-tokens",
        body=body.to_wire(),
    )


def _call_revoke(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    id: str,
) -> ManagementCall:
    """Build the ``scim_tokens.revoke`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    id = require_uuid(id, "id", "scim_tokens.revoke")
    return ManagementCall(
        operation="scim_tokens.revoke",
        method="DELETE",
        path_template="/api/v1/scim-tokens/{id}",
        path=f"/api/v1/scim-tokens/{id}",
    )


class ScimTokensApi:
    """The ``scim_tokens`` namespace handle.

    Bearer tokens for the SCIM 2.0 provisioning endpoint.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def list(self) -> builtins.list[models.ScimTokenResponse]:
        """``GET /api/v1/scim-tokens``"""
        raw = send_management(
            self._client,
            _call_list(self._client, self._scope),
        )
        return [models.ScimTokenResponse.model_validate(item) for item in raw or []]

    def create(self, body: models.CreateScimTokenRequest) -> models.CreateScimTokenResponse:
        """``POST /api/v1/scim-tokens``

        **Returns secret material, once.** ``provisioning_token`` is
        returned by this call and by no other; no later ``get`` will return
        it again, and the ``get`` projection has no field where it was.
        Discarding the result destroys the credential (§27.5 rule 3).

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_create(self._client, self._scope, body),
        )
        return models.CreateScimTokenResponse.model_validate(raw)

    def revoke(self, id: str) -> None:
        """``DELETE /api/v1/scim-tokens/{id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_revoke(self._client, self._scope, id),
        )


class AsyncScimTokensApi:
    """The ``scim_tokens`` namespace handle, async form.

    Bearer tokens for the SCIM 2.0 provisioning endpoint.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    async def list(self) -> builtins.list[models.ScimTokenResponse]:
        """``GET /api/v1/scim-tokens``"""
        raw = await send_management_async(
            self._client,
            _call_list(self._client, self._scope),
        )
        return [models.ScimTokenResponse.model_validate(item) for item in raw or []]

    async def create(self, body: models.CreateScimTokenRequest) -> models.CreateScimTokenResponse:
        """``POST /api/v1/scim-tokens``

        **Returns secret material, once.** ``provisioning_token`` is
        returned by this call and by no other; no later ``get`` will return
        it again, and the ``get`` projection has no field where it was.
        Discarding the result destroys the credential (§27.5 rule 3).

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_create(self._client, self._scope, body),
        )
        return models.CreateScimTokenResponse.model_validate(raw)

    async def revoke(self, id: str) -> None:
        """``DELETE /api/v1/scim-tokens/{id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_revoke(self._client, self._scope, id),
        )
