# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``scopes`` management namespace (CONTRACT §27.1).

Sub-resource granularity, always addressed under their resource.
"""

from __future__ import annotations

import builtins
from typing import TYPE_CHECKING

from axiam_sdk.management import models
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
    require_uuid,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_list(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    resource_id: str,
) -> ManagementCall:
    """Build the ``scopes.list`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    resource_id = require_uuid(resource_id, "resource_id", "scopes.list")
    return ManagementCall(
        operation="scopes.list",
        method="GET",
        path_template="/api/v1/resources/{resource_id}/scopes",
        path=f"/api/v1/resources/{resource_id}/scopes",
    )


def _call_create(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    resource_id: str,
    body: models.CreateScopeRequest,
) -> ManagementCall:
    """Build the ``scopes.create`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    resource_id = require_uuid(resource_id, "resource_id", "scopes.create")
    return ManagementCall(
        operation="scopes.create",
        method="POST",
        path_template="/api/v1/resources/{resource_id}/scopes",
        path=f"/api/v1/resources/{resource_id}/scopes",
        body=body.to_wire(),
    )


def _call_get(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    resource_id: str,
    scope_id: str,
) -> ManagementCall:
    """Build the ``scopes.get`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    resource_id = require_uuid(resource_id, "resource_id", "scopes.get")
    scope_id = require_uuid(scope_id, "scope_id", "scopes.get")
    return ManagementCall(
        operation="scopes.get",
        method="GET",
        path_template="/api/v1/resources/{resource_id}/scopes/{scope_id}",
        path=f"/api/v1/resources/{resource_id}/scopes/{scope_id}",
    )


def _call_update(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    resource_id: str,
    scope_id: str,
    body: models.UpdateScopeRequest,
) -> ManagementCall:
    """Build the ``scopes.update`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    resource_id = require_uuid(resource_id, "resource_id", "scopes.update")
    scope_id = require_uuid(scope_id, "scope_id", "scopes.update")
    return ManagementCall(
        operation="scopes.update",
        method="PUT",
        path_template="/api/v1/resources/{resource_id}/scopes/{scope_id}",
        path=f"/api/v1/resources/{resource_id}/scopes/{scope_id}",
        body=body.to_wire(),
    )


def _call_delete(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    resource_id: str,
    scope_id: str,
) -> ManagementCall:
    """Build the ``scopes.delete`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    resource_id = require_uuid(resource_id, "resource_id", "scopes.delete")
    scope_id = require_uuid(scope_id, "scope_id", "scopes.delete")
    return ManagementCall(
        operation="scopes.delete",
        method="DELETE",
        path_template="/api/v1/resources/{resource_id}/scopes/{scope_id}",
        path=f"/api/v1/resources/{resource_id}/scopes/{scope_id}",
    )


class ScopesApi:
    """The ``scopes`` namespace handle.

    Sub-resource granularity, always addressed under their resource.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def list(self, resource_id: str) -> builtins.list[models.Scope]:
        """``GET /api/v1/resources/{resource_id}/scopes``"""
        raw = send_management(
            self._client,
            _call_list(self._client, self._scope, resource_id),
        )
        return [models.Scope.model_validate(item) for item in raw or []]

    def create(self, resource_id: str, body: models.CreateScopeRequest) -> models.Scope:
        """``POST /api/v1/resources/{resource_id}/scopes``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_create(self._client, self._scope, resource_id, body),
        )
        return models.Scope.model_validate(raw)

    def get(self, resource_id: str, scope_id: str) -> models.Scope:
        """``GET /api/v1/resources/{resource_id}/scopes/{scope_id}``"""
        raw = send_management(
            self._client,
            _call_get(self._client, self._scope, resource_id, scope_id),
        )
        return models.Scope.model_validate(raw)

    def update(
        self,
        resource_id: str,
        scope_id: str,
        body: models.UpdateScopeRequest,
    ) -> models.Scope:
        """``PUT /api/v1/resources/{resource_id}/scopes/{scope_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_update(self._client, self._scope, resource_id, scope_id, body),
        )
        return models.Scope.model_validate(raw)

    def delete(self, resource_id: str, scope_id: str) -> None:
        """``DELETE /api/v1/resources/{resource_id}/scopes/{scope_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_delete(self._client, self._scope, resource_id, scope_id),
        )


class AsyncScopesApi:
    """The ``scopes`` namespace handle, async form.

    Sub-resource granularity, always addressed under their resource.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    async def list(self, resource_id: str) -> builtins.list[models.Scope]:
        """``GET /api/v1/resources/{resource_id}/scopes``"""
        raw = await send_management_async(
            self._client,
            _call_list(self._client, self._scope, resource_id),
        )
        return [models.Scope.model_validate(item) for item in raw or []]

    async def create(self, resource_id: str, body: models.CreateScopeRequest) -> models.Scope:
        """``POST /api/v1/resources/{resource_id}/scopes``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_create(self._client, self._scope, resource_id, body),
        )
        return models.Scope.model_validate(raw)

    async def get(self, resource_id: str, scope_id: str) -> models.Scope:
        """``GET /api/v1/resources/{resource_id}/scopes/{scope_id}``"""
        raw = await send_management_async(
            self._client,
            _call_get(self._client, self._scope, resource_id, scope_id),
        )
        return models.Scope.model_validate(raw)

    async def update(
        self,
        resource_id: str,
        scope_id: str,
        body: models.UpdateScopeRequest,
    ) -> models.Scope:
        """``PUT /api/v1/resources/{resource_id}/scopes/{scope_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_update(self._client, self._scope, resource_id, scope_id, body),
        )
        return models.Scope.model_validate(raw)

    async def delete(self, resource_id: str, scope_id: str) -> None:
        """``DELETE /api/v1/resources/{resource_id}/scopes/{scope_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_delete(self._client, self._scope, resource_id, scope_id),
        )
