# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``settings`` management namespace (CONTRACT §27.1).

Effective settings, and the organization/tenant layers they resolve from.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from axiam_sdk.management import models
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
    resolve_org,
    resolve_tenant,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_get_org(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``settings.get_org`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    org_id = resolve_org(client, scope, "settings.get_org")
    return ManagementCall(
        operation="settings.get_org",
        method="GET",
        path_template="/api/v1/organizations/{org_id}/settings",
        path=f"/api/v1/organizations/{org_id}/settings",
    )


def _call_set_org(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.SetOrgSettings,
) -> ManagementCall:
    """Build the ``settings.set_org`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    org_id = resolve_org(client, scope, "settings.set_org")
    return ManagementCall(
        operation="settings.set_org",
        method="PUT",
        path_template="/api/v1/organizations/{org_id}/settings",
        path=f"/api/v1/organizations/{org_id}/settings",
        body=body.to_wire(),
    )


def _call_get_effective(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``settings.get_effective`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="settings.get_effective",
        method="GET",
        path_template="/api/v1/settings",
        path="/api/v1/settings",
    )


def _call_set_effective(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.TenantSettingsOverride,
) -> ManagementCall:
    """Build the ``settings.set_effective`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="settings.set_effective",
        method="PUT",
        path_template="/api/v1/settings",
        path="/api/v1/settings",
        body=body.to_wire(),
    )


def _call_get_tenant_override(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``settings.get_tenant_override`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "settings.get_tenant_override")
    return ManagementCall(
        operation="settings.get_tenant_override",
        method="GET",
        path_template="/api/v1/tenants/{tenant_id}/settings",
        path=f"/api/v1/tenants/{tenant_id}/settings",
    )


def _call_set_tenant_override(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.TenantSettingsOverride,
) -> ManagementCall:
    """Build the ``settings.set_tenant_override`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "settings.set_tenant_override")
    return ManagementCall(
        operation="settings.set_tenant_override",
        method="PUT",
        path_template="/api/v1/tenants/{tenant_id}/settings",
        path=f"/api/v1/tenants/{tenant_id}/settings",
        body=body.to_wire(),
    )


def _call_delete_tenant_override(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``settings.delete_tenant_override`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "settings.delete_tenant_override")
    return ManagementCall(
        operation="settings.delete_tenant_override",
        method="DELETE",
        path_template="/api/v1/tenants/{tenant_id}/settings",
        path=f"/api/v1/tenants/{tenant_id}/settings",
    )


class SettingsApi:
    """The ``settings`` namespace handle.

    Effective settings, and the organization/tenant layers they resolve
    from.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def in_org(self, org_id: str) -> SettingsApi:
        """Address a different organization than the client's own.

        §27.4 rule 3: the client's ``org_id`` is the default, and a
        platform-admin token legitimately overrides it. Returns a new
        handle; the original is unchanged.
        """
        return SettingsApi(self._client, self._scope.with_org(org_id))

    def for_tenant(self, tenant_id: str) -> SettingsApi:
        """Address a different tenant than the client's own (§27.4 rule 3).

        Returns a new handle; the original is unchanged.
        """
        return SettingsApi(self._client, self._scope.with_tenant(tenant_id))

    def get_org(self) -> models.SecuritySettings:
        """``GET /api/v1/organizations/{org_id}/settings``"""
        raw = send_management(
            self._client,
            _call_get_org(self._client, self._scope),
        )
        return models.SecuritySettings.model_validate(raw)

    def set_org(self, body: models.SetOrgSettings) -> models.SecuritySettings:
        """``PUT /api/v1/organizations/{org_id}/settings``

        **This is a replacement, not a patch** (§27.4 rule 5). Every field
        of the body is required, and what you do not carry over from a prior
        read is not preserved -- it is overwritten. Read first, change the
        field you mean, send the whole thing back.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_set_org(self._client, self._scope, body),
        )
        return models.SecuritySettings.model_validate(raw)

    def get_effective(self) -> models.SecuritySettings:
        """``GET /api/v1/settings``"""
        raw = send_management(
            self._client,
            _call_get_effective(self._client, self._scope),
        )
        return models.SecuritySettings.model_validate(raw)

    def set_effective(self, body: models.TenantSettingsOverride) -> models.SecuritySettings:
        """``PUT /api/v1/settings``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_set_effective(self._client, self._scope, body),
        )
        return models.SecuritySettings.model_validate(raw)

    def get_tenant_override(self) -> models.TenantSettingsOverride:
        """``GET /api/v1/tenants/{tenant_id}/settings``"""
        raw = send_management(
            self._client,
            _call_get_tenant_override(self._client, self._scope),
        )
        return models.TenantSettingsOverride.model_validate(raw)

    def set_tenant_override(
        self,
        body: models.TenantSettingsOverride,
    ) -> models.TenantSettingsOverride:
        """``PUT /api/v1/tenants/{tenant_id}/settings``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_set_tenant_override(self._client, self._scope, body),
        )
        return models.TenantSettingsOverride.model_validate(raw)

    def delete_tenant_override(self) -> None:
        """``DELETE /api/v1/tenants/{tenant_id}/settings``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_delete_tenant_override(self._client, self._scope),
        )


class AsyncSettingsApi:
    """The ``settings`` namespace handle, async form.

    Effective settings, and the organization/tenant layers they resolve
    from.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def in_org(self, org_id: str) -> AsyncSettingsApi:
        """Address a different organization than the client's own.

        §27.4 rule 3: the client's ``org_id`` is the default, and a
        platform-admin token legitimately overrides it. Returns a new
        handle; the original is unchanged.
        """
        return AsyncSettingsApi(self._client, self._scope.with_org(org_id))

    def for_tenant(self, tenant_id: str) -> AsyncSettingsApi:
        """Address a different tenant than the client's own (§27.4 rule 3).

        Returns a new handle; the original is unchanged.
        """
        return AsyncSettingsApi(self._client, self._scope.with_tenant(tenant_id))

    async def get_org(self) -> models.SecuritySettings:
        """``GET /api/v1/organizations/{org_id}/settings``"""
        raw = await send_management_async(
            self._client,
            _call_get_org(self._client, self._scope),
        )
        return models.SecuritySettings.model_validate(raw)

    async def set_org(self, body: models.SetOrgSettings) -> models.SecuritySettings:
        """``PUT /api/v1/organizations/{org_id}/settings``

        **This is a replacement, not a patch** (§27.4 rule 5). Every field
        of the body is required, and what you do not carry over from a prior
        read is not preserved -- it is overwritten. Read first, change the
        field you mean, send the whole thing back.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_set_org(self._client, self._scope, body),
        )
        return models.SecuritySettings.model_validate(raw)

    async def get_effective(self) -> models.SecuritySettings:
        """``GET /api/v1/settings``"""
        raw = await send_management_async(
            self._client,
            _call_get_effective(self._client, self._scope),
        )
        return models.SecuritySettings.model_validate(raw)

    async def set_effective(self, body: models.TenantSettingsOverride) -> models.SecuritySettings:
        """``PUT /api/v1/settings``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_set_effective(self._client, self._scope, body),
        )
        return models.SecuritySettings.model_validate(raw)

    async def get_tenant_override(self) -> models.TenantSettingsOverride:
        """``GET /api/v1/tenants/{tenant_id}/settings``"""
        raw = await send_management_async(
            self._client,
            _call_get_tenant_override(self._client, self._scope),
        )
        return models.TenantSettingsOverride.model_validate(raw)

    async def set_tenant_override(
        self,
        body: models.TenantSettingsOverride,
    ) -> models.TenantSettingsOverride:
        """``PUT /api/v1/tenants/{tenant_id}/settings``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_set_tenant_override(self._client, self._scope, body),
        )
        return models.TenantSettingsOverride.model_validate(raw)

    async def delete_tenant_override(self) -> None:
        """``DELETE /api/v1/tenants/{tenant_id}/settings``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_delete_tenant_override(self._client, self._scope),
        )
