# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``users`` management namespace (CONTRACT §27.1).

Users within the client's tenant, and the administrative side of their
second factor and lockout state.
"""

from __future__ import annotations

import builtins
from typing import TYPE_CHECKING
from urllib.parse import quote

from axiam_sdk.management import models
from axiam_sdk.management._page import (
    Page,
    PageRequest,
    collect_pages,
    collect_pages_async,
    page_of,
    page_query,
)
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
    require_uuid,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_list(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    page: PageRequest | None = None,
) -> ManagementCall:
    """Build the ``users.list`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="users.list",
        method="GET",
        path_template="/api/v1/users",
        path="/api/v1/users",
        query={**page_query(page)},
    )


def _call_create(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.CreateUserRequest,
) -> ManagementCall:
    """Build the ``users.create`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    return ManagementCall(
        operation="users.create",
        method="POST",
        path_template="/api/v1/users",
        path="/api/v1/users",
        body=body.to_wire(),
    )


def _call_get(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    user_id: str,
) -> ManagementCall:
    """Build the ``users.get`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    user_id = require_uuid(user_id, "user_id", "users.get")
    return ManagementCall(
        operation="users.get",
        method="GET",
        path_template="/api/v1/users/{user_id}",
        path=f"/api/v1/users/{user_id}",
    )


def _call_update(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    user_id: str,
    body: models.UpdateUserRequest,
) -> ManagementCall:
    """Build the ``users.update`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    user_id = require_uuid(user_id, "user_id", "users.update")
    return ManagementCall(
        operation="users.update",
        method="PUT",
        path_template="/api/v1/users/{user_id}",
        path=f"/api/v1/users/{user_id}",
        body=body.to_wire(),
    )


def _call_delete(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    user_id: str,
) -> ManagementCall:
    """Build the ``users.delete`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    user_id = require_uuid(user_id, "user_id", "users.delete")
    return ManagementCall(
        operation="users.delete",
        method="DELETE",
        path_template="/api/v1/users/{user_id}",
        path=f"/api/v1/users/{user_id}",
    )


def _call_list_mfa_methods(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    user_id: str,
) -> ManagementCall:
    """Build the ``users.list_mfa_methods`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    user_id = require_uuid(user_id, "user_id", "users.list_mfa_methods")
    return ManagementCall(
        operation="users.list_mfa_methods",
        method="GET",
        path_template="/api/v1/users/{user_id}/mfa-methods",
        path=f"/api/v1/users/{user_id}/mfa-methods",
    )


def _call_delete_mfa_method(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    user_id: str,
    method_id: str,
) -> ManagementCall:
    """Build the ``users.delete_mfa_method`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    user_id = require_uuid(user_id, "user_id", "users.delete_mfa_method")
    method_id = quote(method_id, safe="")
    return ManagementCall(
        operation="users.delete_mfa_method",
        method="DELETE",
        path_template="/api/v1/users/{user_id}/mfa-methods/{method_id}",
        path=f"/api/v1/users/{user_id}/mfa-methods/{method_id}",
    )


def _call_reset_mfa(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    user_id: str,
) -> ManagementCall:
    """Build the ``users.reset_mfa`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    user_id = require_uuid(user_id, "user_id", "users.reset_mfa")
    return ManagementCall(
        operation="users.reset_mfa",
        method="POST",
        path_template="/api/v1/users/{user_id}/reset-mfa",
        path=f"/api/v1/users/{user_id}/reset-mfa",
    )


def _call_unlock(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    user_id: str,
) -> ManagementCall:
    """Build the ``users.unlock`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    user_id = require_uuid(user_id, "user_id", "users.unlock")
    return ManagementCall(
        operation="users.unlock",
        method="POST",
        path_template="/api/v1/users/{user_id}/unlock",
        path=f"/api/v1/users/{user_id}/unlock",
    )


def _call_list_roles(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    user_id: str,
) -> ManagementCall:
    """Build the ``users.list_roles`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    user_id = require_uuid(user_id, "user_id", "users.list_roles")
    return ManagementCall(
        operation="users.list_roles",
        method="GET",
        path_template="/api/v1/users/{user_id}/roles",
        path=f"/api/v1/users/{user_id}/roles",
    )


class UsersApi:
    """The ``users`` namespace handle.

    Users within the client's tenant, and the administrative side of their
    second factor and lockout state.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def list(self, page: PageRequest | None = None) -> Page[models.UserResponse]:
        """``GET /api/v1/users``"""
        raw = send_management(
            self._client,
            _call_list(self._client, self._scope, page),
        )
        return page_of(raw, models.UserResponse)

    def list_all(self, start: PageRequest | None = None) -> builtins.list[models.UserResponse]:
        """Walk ``users.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return collect_pages(start, lambda p: self.list(p))

    def create(self, body: models.CreateUserRequest) -> models.UserResponse:
        """``POST /api/v1/users``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_create(self._client, self._scope, body),
        )
        return models.UserResponse.model_validate(raw)

    def get(self, user_id: str) -> models.UserResponse:
        """``GET /api/v1/users/{user_id}``"""
        raw = send_management(
            self._client,
            _call_get(self._client, self._scope, user_id),
        )
        return models.UserResponse.model_validate(raw)

    def update(self, user_id: str, body: models.UpdateUserRequest) -> models.UserResponse:
        """``PUT /api/v1/users/{user_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_update(self._client, self._scope, user_id, body),
        )
        return models.UserResponse.model_validate(raw)

    def delete(self, user_id: str) -> None:
        """``DELETE /api/v1/users/{user_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_delete(self._client, self._scope, user_id),
        )

    def list_mfa_methods(self, user_id: str) -> builtins.list[models.MfaMethodResponse]:
        """``GET /api/v1/users/{user_id}/mfa-methods``"""
        raw = send_management(
            self._client,
            _call_list_mfa_methods(self._client, self._scope, user_id),
        )
        return [models.MfaMethodResponse.model_validate(item) for item in raw or []]

    def delete_mfa_method(self, user_id: str, method_id: str) -> None:
        """``DELETE /api/v1/users/{user_id}/mfa-methods/{method_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_delete_mfa_method(self._client, self._scope, user_id, method_id),
        )

    def reset_mfa(self, user_id: str) -> None:
        """``POST /api/v1/users/{user_id}/reset-mfa``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        send_management(
            self._client,
            _call_reset_mfa(self._client, self._scope, user_id),
        )

    def unlock(self, user_id: str) -> models.UserResponse:
        """``POST /api/v1/users/{user_id}/unlock``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_unlock(self._client, self._scope, user_id),
        )
        return models.UserResponse.model_validate(raw)

    def list_roles(self, user_id: str) -> builtins.list[models.RoleAssignment]:
        """``GET /api/v1/users/{user_id}/roles``"""
        raw = send_management(
            self._client,
            _call_list_roles(self._client, self._scope, user_id),
        )
        return [models.RoleAssignment.model_validate(item) for item in raw or []]


class AsyncUsersApi:
    """The ``users`` namespace handle, async form.

    Users within the client's tenant, and the administrative side of their
    second factor and lockout state.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    async def list(self, page: PageRequest | None = None) -> Page[models.UserResponse]:
        """``GET /api/v1/users``"""
        raw = await send_management_async(
            self._client,
            _call_list(self._client, self._scope, page),
        )
        return page_of(raw, models.UserResponse)

    async def list_all(
        self,
        start: PageRequest | None = None,
    ) -> builtins.list[models.UserResponse]:
        """Walk ``users.list`` to exhaustion, concatenating every page.

        The auto-paging form §27.4 rule 4 requires. It stops on an empty
        page even if ``total`` disagrees, so a misreporting server costs one
        wasted request rather than an unbounded loop.
        """
        return await collect_pages_async(start, lambda p: self.list(p))

    async def create(self, body: models.CreateUserRequest) -> models.UserResponse:
        """``POST /api/v1/users``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_create(self._client, self._scope, body),
        )
        return models.UserResponse.model_validate(raw)

    async def get(self, user_id: str) -> models.UserResponse:
        """``GET /api/v1/users/{user_id}``"""
        raw = await send_management_async(
            self._client,
            _call_get(self._client, self._scope, user_id),
        )
        return models.UserResponse.model_validate(raw)

    async def update(self, user_id: str, body: models.UpdateUserRequest) -> models.UserResponse:
        """``PUT /api/v1/users/{user_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_update(self._client, self._scope, user_id, body),
        )
        return models.UserResponse.model_validate(raw)

    async def delete(self, user_id: str) -> None:
        """``DELETE /api/v1/users/{user_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_delete(self._client, self._scope, user_id),
        )

    async def list_mfa_methods(self, user_id: str) -> builtins.list[models.MfaMethodResponse]:
        """``GET /api/v1/users/{user_id}/mfa-methods``"""
        raw = await send_management_async(
            self._client,
            _call_list_mfa_methods(self._client, self._scope, user_id),
        )
        return [models.MfaMethodResponse.model_validate(item) for item in raw or []]

    async def delete_mfa_method(self, user_id: str, method_id: str) -> None:
        """``DELETE /api/v1/users/{user_id}/mfa-methods/{method_id}``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_delete_mfa_method(self._client, self._scope, user_id, method_id),
        )

    async def reset_mfa(self, user_id: str) -> None:
        """``POST /api/v1/users/{user_id}/reset-mfa``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        await send_management_async(
            self._client,
            _call_reset_mfa(self._client, self._scope, user_id),
        )

    async def unlock(self, user_id: str) -> models.UserResponse:
        """``POST /api/v1/users/{user_id}/unlock``

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_unlock(self._client, self._scope, user_id),
        )
        return models.UserResponse.model_validate(raw)

    async def list_roles(self, user_id: str) -> builtins.list[models.RoleAssignment]:
        """``GET /api/v1/users/{user_id}/roles``"""
        raw = await send_management_async(
            self._client,
            _call_list_roles(self._client, self._scope, user_id),
        )
        return [models.RoleAssignment.model_validate(item) for item in raw or []]
