# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.

"""The ``webauthn_policy`` management namespace (CONTRACT §27.1).

Per-tenant attestation policy governing the §24 ceremonies, and the
compliance report over it.
"""

from __future__ import annotations

import builtins
from typing import TYPE_CHECKING

from axiam_sdk.management import models
from axiam_sdk.management._request import (
    ManagementCall,
    send_management,
    send_management_async,
)
from axiam_sdk.management._scope import (
    NamespaceScope,
    resolve_tenant,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from axiam_sdk._async_client import AsyncAxiamClient
    from axiam_sdk._client import AxiamClient, _AxiamClientBase


def _call_get(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``webauthn_policy.get`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "webauthn_policy.get")
    return ManagementCall(
        operation="webauthn_policy.get",
        method="GET",
        path_template="/api/v1/tenants/{tenant_id}/webauthn/attestation-policy",
        path=f"/api/v1/tenants/{tenant_id}/webauthn/attestation-policy",
    )


def _call_set(
    client: _AxiamClientBase,
    scope: NamespaceScope,
    body: models.WebauthnAttestationPolicy,
) -> ManagementCall:
    """Build the ``webauthn_policy.set`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "webauthn_policy.set")
    return ManagementCall(
        operation="webauthn_policy.set",
        method="PUT",
        path_template="/api/v1/tenants/{tenant_id}/webauthn/attestation-policy",
        path=f"/api/v1/tenants/{tenant_id}/webauthn/attestation-policy",
        body=body.to_wire(),
    )


def _call_compliance_report(
    client: _AxiamClientBase,
    scope: NamespaceScope,
) -> ManagementCall:
    """Build the ``webauthn_policy.compliance_report`` call.

    Shared by the sync and async handles so the path, query and body are
    decided in exactly one place.
    """
    tenant_id = resolve_tenant(client, scope, "webauthn_policy.compliance_report")
    return ManagementCall(
        operation="webauthn_policy.compliance_report",
        method="GET",
        path_template="/api/v1/tenants/{tenant_id}/webauthn/compliance-report",
        path=f"/api/v1/tenants/{tenant_id}/webauthn/compliance-report",
    )


class WebauthnPolicyApi:
    """The ``webauthn_policy`` namespace handle.

    Per-tenant attestation policy governing the §24 ceremonies, and the
    compliance report over it.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def for_tenant(self, tenant_id: str) -> WebauthnPolicyApi:
        """Address a different tenant than the client's own (§27.4 rule 3).

        Returns a new handle; the original is unchanged.
        """
        return WebauthnPolicyApi(self._client, self._scope.with_tenant(tenant_id))

    def get(self) -> models.PolicyResponse:
        """``GET /api/v1/tenants/{tenant_id}/webauthn/attestation-policy``"""
        raw = send_management(
            self._client,
            _call_get(self._client, self._scope),
        )
        return models.PolicyResponse.model_validate(raw)

    def set(self, body: models.WebauthnAttestationPolicy) -> models.WebauthnAttestationPolicy:
        """``PUT /api/v1/tenants/{tenant_id}/webauthn/attestation-policy``

        **This is a replacement, not a patch** (§27.4 rule 5). Every field
        of the body is required, and what you do not carry over from a prior
        read is not preserved -- it is overwritten. Read first, change the
        field you mean, send the whole thing back.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = send_management(
            self._client,
            _call_set(self._client, self._scope, body),
        )
        return models.WebauthnAttestationPolicy.model_validate(raw)

    def compliance_report(self) -> builtins.list[models.ComplianceReportEntry]:
        """``GET /api/v1/tenants/{tenant_id}/webauthn/compliance-report``"""
        raw = send_management(
            self._client,
            _call_compliance_report(self._client, self._scope),
        )
        return [models.ComplianceReportEntry.model_validate(item) for item in raw or []]


class AsyncWebauthnPolicyApi:
    """The ``webauthn_policy`` namespace handle, async form.

    Per-tenant attestation policy governing the §24 ceremonies, and the
    compliance report over it.

    Acquiring one performs no I/O and allocates nothing meaningful (§27.2
    rule 1); it holds the client and cannot be constructed without one.
    """

    def __init__(self, client: AsyncAxiamClient, scope: NamespaceScope | None = None) -> None:
        """Bind the handle to ``client``; reached as a client property."""
        self._client = client
        self._scope = scope or NamespaceScope()

    def for_tenant(self, tenant_id: str) -> AsyncWebauthnPolicyApi:
        """Address a different tenant than the client's own (§27.4 rule 3).

        Returns a new handle; the original is unchanged.
        """
        return AsyncWebauthnPolicyApi(self._client, self._scope.with_tenant(tenant_id))

    async def get(self) -> models.PolicyResponse:
        """``GET /api/v1/tenants/{tenant_id}/webauthn/attestation-policy``"""
        raw = await send_management_async(
            self._client,
            _call_get(self._client, self._scope),
        )
        return models.PolicyResponse.model_validate(raw)

    async def set(self, body: models.WebauthnAttestationPolicy) -> models.WebauthnAttestationPolicy:
        """``PUT /api/v1/tenants/{tenant_id}/webauthn/attestation-policy``

        **This is a replacement, not a patch** (§27.4 rule 5). Every field
        of the body is required, and what you do not carry over from a prior
        read is not preserved -- it is overwritten. Read first, change the
        field you mean, send the whole thing back.

        Not retried on failure (§27.4 rule 8): every write on this surface
        is issued exactly once, including the ones that look idempotent.
        """
        raw = await send_management_async(
            self._client,
            _call_set(self._client, self._scope, body),
        )
        return models.WebauthnAttestationPolicy.model_validate(raw)

    async def compliance_report(self) -> builtins.list[models.ComplianceReportEntry]:
        """``GET /api/v1/tenants/{tenant_id}/webauthn/compliance-report``"""
        raw = await send_management_async(
            self._client,
            _call_compliance_report(self._client, self._scope),
        )
        return [models.ComplianceReportEntry.model_validate(item) for item in raw or []]
