"""The reactor wire protocol — the signed event and the signed reply (§22.1–§22.4).

Mirror, never import. These shapes reproduce the field order and ``serde``
behaviour of the server's ``ReactorEventMessage`` / ``ReactorReply``
(``crates/axiam-amqp/src/reactor/protocol.rs``) byte-for-byte using only the
standard library. ``testdata/reactor_v2_reference_vectors.json`` — generated by
the server's own sign path — is what pins them.

Both directions are signed with the same §8 v2 primitives and the same tenant
subkey: the server signs the event, the reactor signs the reply. A reply is an
instruction to change a token or refuse a login, so an unsigned reply is not a
weak reply — it is not a reply at all, and the server discards it as though the
reactor had never answered.

Three ways to produce a MAC that never verifies, with no other symptom
=====================================================================

**1. ``hmac_signature`` is serialized as ``null``, not omitted.** §8's own two
message types (``AuthzRequest``, ``AuditEventMessage`` — see ``_hmac.py``) sign
a body with the field ABSENT. A reactor event and a reactor reply sign it
PRESENT and ``null``::

    {"correlation_id":"…","tenant_id":"…", … ,"hmac_signature":null}
                                                               ^^^^ present

**2. ``ensure_ascii`` must be off.** ``json.dumps`` escapes every non-ASCII
character into a ``\\uXXXX`` sequence by default; ``serde_json`` escapes none of
them and emits UTF-8 directly. A deny reason containing an accented character
would otherwise produce bytes the server never reconstructs, for a message that
was otherwise perfectly well formed.

**3. ``issued_at`` is chrono's RFC 3339, not Python's.**
``datetime.isoformat()`` renders UTC as ``+00:00`` and always carries six
fractional digits once ``microsecond`` is non-zero. The server's
``chrono::DateTime<Utc>`` serializes with ``SecondsFormat::AutoSi`` and a ``Z``
suffix: no fractional part at all on a whole second, otherwise three or six
digits. :func:`to_chrono_rfc3339` is the fix and it is not optional.

Everything else about §8 v2 is unchanged: the HKDF-derived per-tenant subkey,
HMAC-SHA256 hex-encoded and compared in constant time, ``key_version = 2`` as a
hard floor, a ±300 s freshness window checked in BOTH directions, and a fresh
UUIDv4 ``nonce`` inside the signed bytes.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Literal

from axiam_sdk.amqp._reactor_registry import (
    LOGIN_POST_AUTH,
    ReactorEventSpec,
    event_spec,
)

__all__ = [
    "REACTOR_KEY_VERSION",
    "REACTOR_FRESHNESS_SKEW_SECONDS",
    "REACTOR_CHAIN_PATCH_KEY",
    "REACTOR_DEFAULT_DENY_REASON",
    "ReplyDecision",
    "EventRejection",
    "ReplyRejection",
    "ReactorEvent",
    "ReactorDecision",
    "allow",
    "require_step_up",
    "deny",
    "mutate",
    "abstain",
    "to_chrono_rfc3339",
    "is_fresh",
    "canonical_event_bytes",
    "verify_event",
    "build_reactor_reply",
    "canonical_reply_bytes",
    "reactor_reply_bytes",
    "sign_reactor_reply",
    "reactor_reply_signature_valid",
    "signing_key_fingerprint",
]

#: Envelope key version this SDK emits, and the floor it accepts (§22.2). A body
#: carrying less than this is refused before anything else about it is
#: considered.
REACTOR_KEY_VERSION = 2

#: Freshness window for ``issued_at``, in seconds, in BOTH directions (§22.2). A
#: future timestamp is not "extra fresh" — it is the shape of a captured message
#: held for later.
REACTOR_FRESHNESS_SKEW_SECONDS = 300.0

#: Payload key under which the server inserts the patch accumulated by earlier
#: reactors in the chain (§22.3), so a later reactor decides against the state
#: that will actually be committed. It is READ-ONLY context: echoing it back
#: inside one's own patch is not how a field is preserved — the server merges
#: (§22.6).
REACTOR_CHAIN_PATCH_KEY = "_reactor_patch"

#: What the server substitutes when a deny carries no reason (§22.4). Stated
#: here so a caller reading a deny answer back sees the same string the audit
#: record will.
REACTOR_DEFAULT_DENY_REASON = "denied by reactor"

#: The closed set of decision values (§22.4). Lowercase on the wire.
ReplyDecision = Literal["allow", "deny", "mutate"]

#: Why a delivered event was not usable, in the order §22.3 requires the checks
#: to run: the body is not a decodable reactor event (``malformed``);
#: ``key_version`` is below the §8 v2 floor, refused BEFORE the signature is
#: even computed (``key_version_too_old``); the MAC is missing or wrong
#: (``bad_signature``); ``issued_at`` is outside ±skew in either direction
#: (``stale``); the nonce was already seen inside the freshness window
#: (``replayed_nonce``); or the event names another tenant
#: (``tenant_mismatch``).
EventRejection = Literal[
    "malformed",
    "key_version_too_old",
    "bad_signature",
    "stale",
    "replayed_nonce",
    "tenant_mismatch",
]

#: Why the server would not use a reply (§22.4), in its fixed validation order:
#: identity, then freshness, then signature, then semantics.
#:
#: Every member resolves to the registration's ``failure_policy`` and every
#: member is audited — a rejected reply is NOT a softer failure than no reply at
#: all. This SDK exposes the taxonomy so a reactor author can assert against it
#: and read it in a log line, and refuses locally only what it can detect
#: without guessing.
ReplyRejection = Literal[
    "wrong_correlation",
    "tenant_mismatch",
    "event_mismatch",
    "key_version_too_old",
    "stale",
    "bad_signature",
    "require_mfa_not_supported",
    "not_mutable",
    "forbidden_patch_field",
    "malformed_mutation",
]


def to_chrono_rfc3339(moment: datetime) -> str:
    """Render ``moment`` the way the server's ``chrono::DateTime<Utc>`` does.

    RFC 3339, UTC, ``Z``-suffixed, with **no** fractional part when the
    microseconds are zero, three digits when they are a whole number of
    milliseconds, and six otherwise — ``chrono``'s ``SecondsFormat::AutoSi``.

    This is not cosmetic. The server verifies a reply by re-serializing the body
    it parsed, so a timestamp this SDK wrote as ``…T12:00:00.000000+00:00`` comes
    back out as ``…T12:00:00Z`` — different bytes, different MAC, and a
    ``bad_signature`` rejection with nothing in the payload to explain it.

    A naive datetime is read as UTC; an aware one is converted.
    """
    if moment.tzinfo is None:
        moment = moment.replace(tzinfo=timezone.utc)
    moment = moment.astimezone(timezone.utc)
    stem = moment.strftime("%Y-%m-%dT%H:%M:%S")
    micros = moment.microsecond
    if micros == 0:
        return f"{stem}Z"
    if micros % 1000 == 0:
        return f"{stem}.{micros // 1000:03d}Z"
    return f"{stem}.{micros:06d}Z"


def _parse_rfc3339(value: str) -> datetime:
    """Parse an RFC 3339 timestamp, accepting a trailing ``Z``.

    ``datetime.fromisoformat`` rejects a bare ``Z`` suffix before Python 3.11,
    so it is normalized first — this SDK supports 3.10. Raises ``ValueError``
    for anything unparseable, matching ``fromisoformat``'s own contract.
    """
    normalized = value.strip()
    if normalized.endswith(("Z", "z")):
        normalized = normalized[:-1] + "+00:00"
    parsed = datetime.fromisoformat(normalized)
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed


def is_fresh(issued_at: datetime, now: datetime, skew_seconds: float) -> bool:
    """Report whether ``issued_at`` lies within ``±skew_seconds`` of ``now``.

    Both directions (§22.2). A timestamp ahead of the verifier's clock is
    rejected exactly like one behind it.
    """
    return abs((now - issued_at).total_seconds()) <= skew_seconds


def _canonical_json(body: dict[str, Any]) -> bytes:
    """Serialize ``body`` the way ``serde_json`` does: compact, insertion order,
    and WITHOUT ``json.dumps``'s default non-ASCII escaping.

    ``json.dumps`` turns every non-ASCII character into a ``\\uXXXX`` sequence
    unless told not to; ``serde_json`` emits UTF-8 directly. A deny reason
    carrying an accented character would otherwise be signed over bytes the
    server never reconstructs.
    """
    return json.dumps(body, separators=(",", ":"), ensure_ascii=False).encode("utf-8")


def _sign(signing_key: bytes, canonical: bytes) -> str:
    """Return the hex-encoded HMAC-SHA256 of ``canonical`` under ``signing_key``.

    ``signing_key`` is the tenant's HKDF-derived AMQP subkey (§8, §22.2). There
    is no second key and no asymmetric variant in v1.
    """
    return hmac.new(signing_key, canonical, hashlib.sha256).hexdigest()


def _verify(signing_key: bytes, canonical: bytes, signature_hex: str) -> bool:
    """Constant-time-compare ``signature_hex`` against the MAC of ``canonical``.

    ``hmac.compare_digest``, never ``==`` on the hex strings. Never raises:
    non-hex input is a mismatch, not an exception.
    """
    try:
        received = bytes.fromhex(signature_hex)
    except ValueError:
        return False
    expected = hmac.new(signing_key, canonical, hashlib.sha256).digest()
    return hmac.compare_digest(received, expected)


def signing_key_fingerprint(signing_key: bytes) -> str:
    """Return eight hex characters identifying ``signing_key`` without printing it.

    HKDF-SHA256 derivation is **not** performed by this SDK: §8.1 assumes the
    per-tenant subkey is provisioned out of band, and ``reactor_serve`` takes
    that already-derived key. This helper exists only so a caller can
    fingerprint the key they were handed for an operational log — eight hex
    characters of a SHA-256 digest is enough to tell two keys apart in a log
    line and far too little to attack (§22.12).
    """
    return hashlib.sha256(signing_key).hexdigest()[:8]


@dataclass(frozen=True)
class ReactorEvent:
    """One hook firing, delivered to a reactor and already verified (§22.3).

    By the time a handler sees one of these, its ``key_version``, MAC, freshness
    and nonce have all been checked. A runtime that hands an unverified payload
    to user code has already lost — the handler will act on it, and "we checked
    afterwards" is not a check.
    """

    #: The tenant this firing belongs to. The signing subkey is derived from it,
    #: so an event cannot be replayed into another tenant.
    tenant_id: str
    #: A registry name (§22.5) — also the second half of the routing key.
    event: str
    #: The single-use handle for this dispatch. The runtime echoes it into the
    #: reply BODY; copying it only into the AMQP property produces a reply the
    #: server discards.
    correlation_id: str
    #: Event-specific body. Never carries a credential, a token or a signing key
    #: — a reactor is told *what is being decided*, not handed the means to act
    #: on it elsewhere. It is tenant business data: readable by design (§22.12),
    #: but not something to log at info level.
    payload: dict[str, Any]
    #: How long the server will actually wait for THIS dispatch, in
    #: milliseconds. Inside the signed body, so it cannot be widened in transit.
    timeout_ms: int
    #: §8 v2 envelope key version. Always ``2`` or higher.
    key_version: int
    #: Fresh UUIDv4 per message, inside the signed bytes. Not a secret.
    nonce: str
    #: Producer-side send time, RFC 3339, for the freshness gate.
    issued_at: str

    @property
    def timeout_seconds(self) -> float:
        """``timeout_ms`` as seconds, for ``asyncio.wait_for``."""
        return self.timeout_ms / 1000.0

    @property
    def spec(self) -> ReactorEventSpec | None:
        """This event's registry entry (§22.5), or ``None`` for a name outside it."""
        return event_spec(self.event)

    @property
    def chain_patch(self) -> dict[str, Any] | None:
        """The patch an earlier reactor in the chain already returned (§22.3).

        ``None`` on a first-in-chain dispatch. It is READ-ONLY context, provided
        so a later reactor decides against the state that will actually be
        committed. Echoing it back inside this reactor's own patch is not how a
        field is preserved: the server merges the chain itself, as a union with
        last-write-wins per key (§22.6).
        """
        value = self.payload.get(REACTOR_CHAIN_PATCH_KEY)
        return value if isinstance(value, dict) else None


@dataclass(frozen=True)
class ReactorDecision:
    """What a handler decided about one event (CONTRACT.md §22.10).

    Three answers plus one absence. ``allow``, ``deny`` and ``mutate`` are the
    three the wire carries; ``abstain`` is the ABSENCE of a reply, which the
    server resolves through the registration's ``failure_policy`` (§22.8)
    exactly as it resolves a timeout.

    Build one with :func:`allow`, :func:`require_step_up`, :func:`deny`,
    :func:`mutate` or :func:`abstain` rather than by hand — the constructors are
    what make §22.4's rules structural. There is no way to spell ``allow`` +
    ``patch``, because the allow constructors take no patch.
    """

    #: ``"allow"``, ``"deny"``, ``"mutate"`` or ``"abstain"``.
    kind: Literal["allow", "deny", "mutate", "abstain"]
    #: Audited reason on a ``deny``. A deny with no reason still denies; the
    #: server substitutes :data:`REACTOR_DEFAULT_DENY_REASON`.
    reason: str | None = None
    #: The fields to set on a ``mutate`` — a flat ``str -> str`` map, published
    #: UNFILTERED (§22.4 rule 1).
    patch: dict[str, str] | None = None
    #: Proceed only after step-up authentication. ``login.post_auth`` ONLY — it
    #: is not a separate decision value, and sending it on any other event is
    #: refused (§22.4 rule 3).
    require_mfa: bool = False


def allow() -> ReactorDecision:
    """Proceed unchanged."""
    return ReactorDecision(kind="allow")


def require_step_up() -> ReactorDecision:
    """Proceed, but demand step-up authentication first — ``allow`` + ``require_mfa``.

    ``login.post_auth`` ONLY. The runtime refuses it on any other event rather
    than putting a reply on the wire the server will reject as
    ``require_mfa_not_supported``.

    On the federated sign-in paths (SAML ACS, OIDC callback) there is no step-up
    branch to take, so a ``require_mfa`` answer FAILS the sign-in rather than
    being silently dropped. A reactor that needs step-up there should answer
    :func:`deny` and drive enrolment out of band (§22.5).
    """
    return ReactorDecision(kind="allow", require_mfa=True)


def deny(reason: str | None = None) -> ReactorDecision:
    """Refuse the operation.

    The reason is audited; omitting it still denies, and the audit record reads
    :data:`REACTOR_DEFAULT_DENY_REASON`. A deny short-circuits the chain: no
    later reactor is consulted (§22.6).
    """
    return ReactorDecision(kind="deny", reason=reason)


def mutate(patch: dict[str, str]) -> ReactorDecision:
    """Proceed, applying ``patch`` — a flat ``str -> str`` map, mutable events only.

    The patch is sent UNFILTERED (§22.4 rule 1, §22.10 rule 3). One forbidden
    key rejects the whole patch server-side, including the fields that would
    have been fine, and this SDK does NOT quietly drop the offender to rescue
    the rest: doing so would leave the reactor author believing a field was set
    when it was dropped, which is the exact failure the server refuses to
    produce. Check yourself with
    :func:`axiam_sdk.amqp.patch_field_allowed` if you want to know before you
    send.

    The caller's mapping is copied, so mutating it afterwards cannot change what
    was signed.
    """
    return ReactorDecision(kind="mutate", patch=dict(patch))


def abstain() -> ReactorDecision:
    """Publish nothing at all; let the registration's ``failure_policy`` decide.

    The right answer when the window has already closed (§22.3: shed load rather
    than answer into a closed window) or when the handler cannot decide. It is
    NOT a quiet ``allow``: the server applies the registration's
    ``failure_policy``, which for every event except ``token.pre_issue``
    defaults to ``fail_closed``.
    """
    return ReactorDecision(kind="abstain")


def canonical_event_bytes(body: dict[str, Any]) -> bytes | None:
    """Return the canonical signed bytes of a delivered event (§22.2).

    The body exactly as it arrived, with ``hmac_signature`` set to ``None`` **in
    place** — setting the value rather than deleting the key is the whole
    difference from §8's own two message types. Re-serializing the *parsed* body
    rather than a rebuilt struct is what makes the payload's own key order and
    nesting reproduce byte-for-byte: ``json.loads`` preserves insertion order
    (PEP 468 / CPython 3.7+), and assigning to an existing key keeps its
    position.

    ``None`` when the body carries no ``hmac_signature`` key at all: an unsigned
    event is not a weak event, it is not an event, and inserting the key here
    would put it in the wrong position anyway.
    """
    if "hmac_signature" not in body:
        return None
    canonical = dict(body)
    canonical["hmac_signature"] = None
    return _canonical_json(canonical)


def verify_event(
    body: dict[str, Any],
    signing_key: bytes,
    now: datetime | None = None,
    skew_seconds: float = REACTOR_FRESHNESS_SKEW_SECONDS,
) -> tuple[ReactorEvent, None] | tuple[None, EventRejection]:
    """Verify a delivered event and decode it, in the order §22.3 fixes.

    ``key_version`` first — before anything else about the body is considered —
    then the MAC, then freshness. The fourth check, the nonce seen-set, is the
    runtime's rather than this function's, because it is state rather than a
    property of the message.

    Returns ``(event, None)`` on success and ``(None, rejection)`` otherwise. A
    runtime that hands an unverified payload to user code has already lost: the
    handler will act on it, and "we checked afterwards" is not a check.
    """
    # 1. key_version, before anything else about the body is considered. A body
    #    whose version is not an integer at all is malformed rather than old:
    #    "2" is not 2, and the floor comparison is only meaningful once the
    #    field is a number.
    key_version = body.get("key_version")
    if not isinstance(key_version, int) or isinstance(key_version, bool):
        return None, "malformed"
    if key_version < REACTOR_KEY_VERSION:
        return None, "key_version_too_old"

    # 2. the MAC, over the body with hmac_signature serialized as null.
    signature = body.get("hmac_signature")
    if not isinstance(signature, str):
        return None, "bad_signature"
    canonical = canonical_event_bytes(body)
    if canonical is None or not _verify(signing_key, canonical, signature):
        return None, "bad_signature"

    # Only now is the body's shape trusted enough to read. A signature attests
    # to who wrote the bytes, not to what they mean, so this is the one class of
    # rejection a valid MAC cannot rescue.
    tenant_id = body.get("tenant_id")
    event_name = body.get("event")
    correlation_id = body.get("correlation_id")
    nonce = body.get("nonce")
    issued_at_raw = body.get("issued_at")
    timeout_ms = body.get("timeout_ms")
    payload = body.get("payload")
    if (
        not isinstance(tenant_id, str)
        or not isinstance(event_name, str)
        or not isinstance(correlation_id, str)
        or not isinstance(nonce, str)
        or not isinstance(issued_at_raw, str)
        or not isinstance(timeout_ms, int)
        or isinstance(timeout_ms, bool)
        or not isinstance(payload, dict)
    ):
        return None, "malformed"

    # 3. freshness, in both directions.
    try:
        issued_at = _parse_rfc3339(issued_at_raw)
    except ValueError:
        return None, "stale"
    reference = now if now is not None else datetime.now(timezone.utc)
    if not is_fresh(issued_at, reference, skew_seconds):
        return None, "stale"

    return (
        ReactorEvent(
            tenant_id=tenant_id,
            event=event_name,
            correlation_id=correlation_id,
            payload=payload,
            timeout_ms=timeout_ms,
            key_version=key_version,
            nonce=nonce,
            issued_at=issued_at_raw,
        ),
        None,
    )


def build_reactor_reply(
    correlation_id: str,
    tenant_id: str,
    event: str,
    decision: ReplyDecision,
    *,
    reason: str | None = None,
    patch: dict[str, str] | None = None,
    require_mfa: bool = False,
    nonce: str | None = None,
    issued_at: datetime | None = None,
) -> dict[str, Any]:
    """Build an UNSIGNED reply body in the server's field order (§22.4).

    ``correlation_id``, ``tenant_id`` and ``event`` are copied from the event
    being answered (§22.1) — the ``correlation_id`` inside the signed body is
    the single-use handle the server authenticates, and copying it only into the
    AMQP property produces a reply the server discards.

    Field order is ``correlation_id``, ``tenant_id``, ``event``, ``decision``,
    ``reason`` (omitted when absent), ``patch`` (omitted when absent),
    ``require_mfa`` (**omitted when false**), ``key_version``, ``nonce``,
    ``issued_at``, ``hmac_signature`` (``null`` while signing). The three
    conditional omissions are load-bearing: a reply that serializes
    ``"require_mfa": false`` rather than omitting it produces different
    canonical bytes and therefore a different MAC.

    The patch's keys are emitted in sorted order, because the server's ``patch``
    is a ``BTreeMap`` and the signed bytes are the sorted rendering.

    ``nonce`` defaults to a **fresh UUIDv4 per reply**. The server keeps no
    durable nonce-dedup store for replies — its protection is the freshness
    window plus the ``correlation_id`` binding — but the nonce is inside the
    signed bytes, and a unique one is the only thing that keeps two replies from
    being byte-identical. Emitting a constant nonce removes the sole uniqueness
    a reply body carries beyond its timestamp. Both overrides exist so a test
    can reproduce a committed vector.
    """
    # Assembled by assignment, in declaration order, because json.dumps
    # serializes a dict in insertion order and that order IS the wire format.
    reply: dict[str, Any] = {
        "correlation_id": correlation_id,
        "tenant_id": tenant_id,
        "event": event,
        "decision": decision,
    }
    # `reason` and `patch` are omitted when absent — not emitted as null.
    if reason is not None:
        reply["reason"] = reason
    if patch is not None:
        reply["patch"] = {key: patch[key] for key in sorted(patch)}
    # `require_mfa` is omitted when false. A reply carrying `false` explicitly
    # signs different bytes and its MAC will not verify.
    if require_mfa:
        reply["require_mfa"] = True
    reply["key_version"] = REACTOR_KEY_VERSION
    reply["nonce"] = nonce if nonce is not None else str(uuid.uuid4())
    reply["issued_at"] = to_chrono_rfc3339(
        issued_at if issued_at is not None else datetime.now(timezone.utc)
    )
    reply["hmac_signature"] = None
    return reply


def canonical_reply_bytes(reply: dict[str, Any]) -> bytes:
    """Return the exact bytes a reply is signed over (§22.2).

    Itself, in declaration order, with ``hmac_signature`` set to ``None``.
    Clearing the field here rather than asking the caller to remember is what
    makes it impossible to sign over a body that already contains a signature.
    """
    unsigned = dict(reply)
    unsigned["hmac_signature"] = None
    return _canonical_json(unsigned)


def reactor_reply_bytes(reply: dict[str, Any]) -> bytes:
    """Serialize a SIGNED reply for the wire.

    The same canonicalization as :func:`canonical_reply_bytes`, but with
    ``hmac_signature`` left as whatever :func:`sign_reactor_reply` put there —
    the only difference between the bytes that were signed and the bytes that
    are sent. Assigning to the existing ``hmac_signature`` key keeps its
    position, so the two renderings differ in that one value and nowhere else.
    """
    return _canonical_json(reply)


def sign_reactor_reply(reply: dict[str, Any], signing_key: bytes) -> dict[str, Any]:
    """Sign ``reply`` with the tenant's derived AMQP subkey.

    Returns a new mapping carrying the MAC; the input is not mutated.
    """
    signed = dict(reply)
    signed["hmac_signature"] = _sign(signing_key, canonical_reply_bytes(reply))
    return signed


def reactor_reply_signature_valid(reply: dict[str, Any], signing_key: bytes) -> bool:
    """Verify a reply's own signature — the check the server performs.

    Exposed so an SDK test (or a proxy) can run it locally. An unsigned reply is
    ``False``: it is not a weak reply, it is not a reply.
    """
    signature = reply.get("hmac_signature")
    if not isinstance(signature, str):
        return False
    return _verify(signing_key, canonical_reply_bytes(reply), signature)


def _require_mfa_allowed(event: str) -> bool:
    """Report whether ``require_mfa`` may ride on a reply for ``event`` (§22.4 rule 3).

    ``login.post_auth`` and nowhere else. Kept as a named predicate so the rule
    reads the same in the runtime as it does in the contract.
    """
    return event == LOGIN_POST_AUTH
