"""The SSF receiver helper — CONTRACT §32.8's eight helper tests.

Every key is an Ed25519 key generated by the test, and every SET is signed
here: no key literal, no captured token. Failure messages print fixed text.
"""

from __future__ import annotations

import asyncio
import base64
import json
import secrets
import uuid
from collections.abc import Iterator
from typing import Any

import httpx
import pytest
import respx
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from jwt.algorithms import OKPAlgorithm
from pydantic import SecretStr

from axiam_sdk import AsyncAxiamClient, AuthError, AxiamClient, NetworkError, SsfUnjudged
from axiam_sdk._telemetry import TelemetryEvent
from axiam_sdk.management import NotFoundError, ValidationError
from axiam_sdk.ssf import (
    ACCOUNT_DISABLED,
    ACCOUNT_PURGED,
    MIN_REPLAY_WINDOW_SECONDS,
    SESSION_REVOKED,
    AsyncSsfReceiver,
    MemoryReplayStore,
    RefusedSet,
    SetErr,
    SetFailureReason,
    SetVerificationError,
    SsfReceiver,
)

BASE = "https://iam.example.test"
ISSUER = f"{BASE}/t/22222222-2222-4222-8222-222222222222"
AUDIENCE = "https://rp.example.test"
JWKS = f"{BASE}/oauth2/jwks"


def b64(data: bytes) -> str:
    """Unpadded base64url."""
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


class Key:
    """A fresh Ed25519 signing key with a random ``kid``."""

    def __init__(self, kid: str | None = None) -> None:
        """Generate the key."""
        self.kid = kid or f"k-{uuid.uuid4().hex}"
        self.private = Ed25519PrivateKey.generate()

    def jwk(self) -> dict[str, Any]:
        """The public JWK."""
        jwk = json.loads(OKPAlgorithm.to_jwk(self.private.public_key()))
        jwk.update({"kid": self.kid, "alg": "EdDSA", "use": "sig"})
        return dict(jwk)

    def sign(self, header: dict[str, Any], claims: dict[str, Any]) -> str:
        """A compact JWS over ``header`` and ``claims``."""
        signing_input = f"{b64(json.dumps(header).encode())}.{b64(json.dumps(claims).encode())}"
        return f"{signing_input}.{b64(self.private.sign(signing_input.encode()))}"

    def sign_set(self, claims: dict[str, Any]) -> str:
        """A SET with the transmitter's header."""
        return self.sign({"alg": "EdDSA", "typ": "secevent+jwt", "kid": self.kid}, claims)


def claims(**changes: Any) -> dict[str, Any]:
    """A valid SET claim set; ``None`` in ``changes`` removes a member."""
    body: dict[str, Any] = {
        "iss": ISSUER,
        "aud": AUDIENCE,
        "iat": 1_791_500_000,
        "jti": uuid.uuid4().hex,
        "txn": "t-1",
        "sub_id": {"format": "iss_sub", "iss": ISSUER, "sub": str(uuid.uuid4())},
        "events": {SESSION_REVOKED: {"event_timestamp": 1_791_500_000}},
    }
    for k, v in changes.items():
        if v is None:
            body.pop(k, None)
        else:
            body[k] = v
    return body


@pytest.fixture
def router() -> Iterator[respx.MockRouter]:
    """A respx router over every request of the test."""
    with respx.mock(assert_all_called=False) as mock:
        yield mock


def serve_jwks(router: respx.MockRouter, *keys: Key) -> respx.Route:
    """Serve ``keys`` at the JWKS URL; the route counts the fetches."""
    return router.get(JWKS).mock(
        return_value=httpx.Response(200, json={"keys": [k.jwk() for k in keys]})
    )


def receiver(events: list[TelemetryEvent] | None = None, **overrides: Any) -> SsfReceiver:
    """A receiver over a fresh client, with a run-time poll bearer; ``events``
    collects the client's §19 telemetry when given."""
    token = f"cc-{secrets.token_urlsafe(16)}"
    options: dict[str, Any] = {
        "issuer": ISSUER,
        "audience": AUDIENCE,
        "jwks_uri": JWKS,
        "access_token_provider": lambda: SecretStr(token),
    }
    options.update(overrides)
    hook = events.append if events is not None else None
    return SsfReceiver(
        AxiamClient(base_url=BASE, tenant_slug="acme", telemetry_hook=hook), **options
    )


def unjudged_events(events: list[TelemetryEvent]) -> list[SsfUnjudged]:
    """The §19.1 ``ssf_unjudged`` events among ``events``."""
    return [e for e in events if isinstance(e, SsfUnjudged)]


def reason(r: SsfReceiver, set_token: str) -> SetFailureReason:
    """The refusal's reason; it is an ``AuthError``."""
    with pytest.raises(SetVerificationError) as excinfo:
        r.verify_set(set_token)
    assert isinstance(excinfo.value, AuthError)
    assert excinfo.value.reason == excinfo.value.set_failure_reason.value
    return excinfo.value.set_failure_reason


# ── 1 ──


def test_a_set_signed_by_the_jwks_key_verifies_into_its_claims(router: respx.MockRouter) -> None:
    """Every field of the result is the claim's; array ``aud`` and the media type too."""
    key = Key()
    serve_jwks(router, key)
    c = claims()
    event = receiver().verify_set(key.sign_set(c))
    assert event.jti == c["jti"]
    assert event.iat == 1_791_500_000
    assert event.iss == ISSUER
    assert event.aud == AUDIENCE
    assert event.txn == "t-1"
    assert event.event_type == SESSION_REVOKED
    assert event.event == c["events"][SESSION_REVOKED]
    assert event.sub_id == c["sub_id"]

    array = claims(aud=["other", AUDIENCE])
    header = {"alg": "EdDSA", "typ": "Application/SecEvent+JWT", "kid": key.kid}
    assert receiver().verify_set(key.sign(header, array)).aud == ["other", AUDIENCE]


# ── 2 ──


def test_a_wrong_typ_or_alg_is_refused_in_that_order(router: respx.MockRouter) -> None:
    """``typ`` absent or ``JWT`` -> invalid_type; ``none`` / ``HS256`` -> invalid_key."""
    key = Key()
    serve_jwks(router, key)
    r = receiver()
    c = claims()
    for header in (
        {"alg": "EdDSA", "kid": key.kid},
        {"alg": "EdDSA", "typ": "JWT", "kid": key.kid},
    ):
        assert reason(r, key.sign(header, c)) is SetFailureReason.INVALID_TYPE
    payload = b64(json.dumps(c).encode())
    none = f"{b64(json.dumps({'alg': 'none', 'typ': 'secevent+jwt'}).encode())}.{payload}."
    assert reason(r, none) is SetFailureReason.INVALID_KEY
    import jwt as pyjwt

    hs = pyjwt.encode(
        c,
        secrets.token_bytes(32),
        algorithm="HS256",
        headers={"typ": "secevent+jwt", "kid": key.kid},
    )
    assert reason(r, hs) is SetFailureReason.INVALID_KEY
    no_kid = key.sign({"alg": "EdDSA", "typ": "secevent+jwt"}, c)
    assert reason(r, no_kid) is SetFailureReason.INVALID_KEY
    for malformed in ("a.b", "!!.@@.##", f"!!.{payload}.c2ln", f"{payload}.@@.", "x.y.z!", 42):
        assert reason(r, malformed) is SetFailureReason.MALFORMED  # type: ignore[arg-type]
    array_header = f"{b64(b'[1]')}.{payload}.{b64(b'sig')}"
    assert reason(r, array_header) is SetFailureReason.MALFORMED


# ── 3 ──


def test_another_key_or_a_tampered_payload_is_invalid_key(router: respx.MockRouter) -> None:
    """Same ``kid``, other key; and a payload changed after signing."""
    key = Key()
    rogue = Key(kid=key.kid)
    serve_jwks(router, key)
    r = receiver()
    assert reason(r, rogue.sign_set(claims())) is SetFailureReason.INVALID_KEY
    good = key.sign_set(claims()).split(".")
    good[1] = b64(json.dumps(claims(txn="x")).encode())
    assert reason(r, ".".join(good)) is SetFailureReason.INVALID_KEY


# ── 4 ──


def test_another_issuer_or_audience_is_refused(router: respx.MockRouter) -> None:
    """``iss`` exact; ``aud`` a string or an array containing it."""
    key = Key()
    serve_jwks(router, key)
    r = receiver()
    assert reason(r, key.sign_set(claims(iss=BASE))) is SetFailureReason.INVALID_ISSUER
    for aud in (["https://elsewhere.test"], "https://elsewhere.test", 7):
        assert reason(r, key.sign_set(claims(aud=aud))) is SetFailureReason.INVALID_AUDIENCE


# ── 5 ──


def test_exp_sub_two_events_or_missing_members_are_invalid_request(
    router: respx.MockRouter,
) -> None:
    """Step 8, every way."""
    key = Key()
    serve_jwks(router, key)
    r = receiver()
    for c in (
        claims(exp=1_891_500_000),
        claims(sub="u"),
        claims(events={ACCOUNT_DISABLED: {}, ACCOUNT_PURGED: {}}),
        claims(events={}),
        claims(jti=None),
        claims(jti=""),
        claims(iat=None),
        claims(iat="1791500000"),
        claims(iat=True),
        claims(sub_id=None),
        claims(sub_id="u"),
    ):
        assert reason(r, key.sign_set(c)) is SetFailureReason.INVALID_REQUEST


# ── 6 ──


def test_a_replay_is_refused_and_a_short_window_is_refused_at_configuration(
    router: respx.MockRouter,
) -> None:
    """The second sighting is ``replayed``; six days is refused before any I/O."""
    key = Key()
    jwks = serve_jwks(router, key)
    r = receiver()
    set_token = key.sign_set(claims())
    r.verify_set(set_token)
    assert reason(r, set_token) is SetFailureReason.REPLAYED
    with pytest.raises(ValidationError):
        receiver(replay_window_seconds=6 * 24 * 60 * 60)
    assert jwks.call_count == 1
    for bad in ({"issuer": ""}, {"jwks_uri": None}, {"discovery_url": f"{BASE}/d"}):
        with pytest.raises(ValidationError):
            receiver(**bad)


def test_the_memory_store_forgets_after_the_window() -> None:
    """Atomic check-and-record with expiry."""
    now = [0.0]
    store = MemoryReplayStore(clock=lambda: now[0])
    assert store.check_and_record("a", 60)
    assert not store.check_and_record("a", 60)
    now[0] = 61.0
    assert store.check_and_record("a", 60), "expired, so new again"
    assert MIN_REPLAY_WINDOW_SECONDS == 7 * 24 * 60 * 60


# ── 7 ──


def test_an_unknown_kid_costs_one_refetch_and_a_second_one_none(router: respx.MockRouter) -> None:
    """Prime (1), unknown kid -> 2, another unknown kid within the minute -> 2."""
    key = Key()
    jwks = serve_jwks(router, key)
    now = [1000.0]
    r = receiver(clock=lambda: now[0])
    r.verify_set(key.sign_set(claims()))
    assert jwks.call_count == 1
    assert reason(r, Key().sign_set(claims())) is SetFailureReason.INVALID_KEY
    assert jwks.call_count == 2, "exactly one refetch"
    assert reason(r, Key().sign_set(claims())) is SetFailureReason.INVALID_KEY
    assert jwks.call_count == 2, "no refetch within the minute"
    now[0] += 61
    assert reason(r, Key().sign_set(claims())) is SetFailureReason.INVALID_KEY
    assert jwks.call_count == 3, "a minute later, one more"
    now[0] += 400
    r.verify_set(key.sign_set(claims()))
    assert jwks.call_count == 4, "past its lifespan the JWKS is fetched again"


def test_a_failed_cold_cache_fill_counts_toward_the_once_a_minute_limit(
    router: respx.MockRouter,
) -> None:
    """§32.8 helper test 7, contract 1.60 (§34.2 P6, row A3): a fill that fails
    counts, so the next SET within the minute makes no fetch and is left
    unjudged -- a no-verdict ``NetworkError``, never a refusal -- and a minute
    later one fetch is made again."""
    key = Key()
    jwks = router.get(JWKS).mock(
        side_effect=[
            httpx.Response(503),
            httpx.Response(200, json={"keys": [key.jwk()]}),
        ]
    )
    now = [1000.0]
    r = receiver(clock=lambda: now[0])
    for _ in range(3):
        with pytest.raises(NetworkError) as failed:
            r.verify_set(key.sign_set(claims()))
        assert not isinstance(failed.value, SetVerificationError)
    assert jwks.call_count == 1, "the failed fill is the only fetch within the minute"
    now[0] += 61
    r.verify_set(key.sign_set(claims()))
    assert jwks.call_count == 2, "a minute later, the fill is tried again"


def test_the_key_cache_expires_within_ten_minutes_and_a_failed_refresh_counts(
    router: respx.MockRouter,
) -> None:
    """§34.2 P6 (contract 1.60, C-5): the key cache expires no later than 10
    minutes after the fill (300 s here) and the next SET fetches again; a
    **failed** refresh of the expired cache counts toward the once-a-minute
    limit, so a SET within the minute makes no fetch and raises ``NetworkError``
    -- no verdict -- and a minute later one fetch is made again."""
    from axiam_sdk.ssf._receiver import _JWKS_LIFESPAN_SECONDS

    assert _JWKS_LIFESPAN_SECONDS <= 600
    key = Key()
    jwks = router.get(JWKS).mock(
        side_effect=[
            httpx.Response(200, json={"keys": [key.jwk()]}),
            httpx.Response(503),
            httpx.Response(200, json={"keys": [key.jwk()]}),
        ]
    )
    now = [1000.0]
    r = receiver(clock=lambda: now[0])
    r.verify_set(key.sign_set(claims()))
    now[0] += _JWKS_LIFESPAN_SECONDS - 1
    r.verify_set(key.sign_set(claims()))
    assert jwks.call_count == 1, "within its lifespan the cache serves"
    now[0] += 1
    for _ in range(2):
        with pytest.raises(NetworkError) as failed:
            r.verify_set(key.sign_set(claims()))
        assert not isinstance(failed.value, SetVerificationError)
    assert jwks.call_count == 2, "expired: one refresh, which failed and counts"
    now[0] += 61
    r.verify_set(key.sign_set(claims()))
    assert jwks.call_count == 3


def test_a_failed_fill_that_never_reached_the_wire_counts_too(router: respx.MockRouter) -> None:
    """A transport failure and an unparseable body are failed fills as well."""
    key = Key()
    jwks = router.get(JWKS).mock(side_effect=httpx.ConnectError("refused"))
    r = receiver()
    for _ in range(2):
        with pytest.raises(NetworkError):
            r.verify_set(key.sign_set(claims()))
    assert jwks.call_count == 1


def test_a_successful_fill_is_not_a_refetch(router: respx.MockRouter) -> None:
    """The other half of P6 (§32.8 test 7): an unknown ``kid`` right after a
    fill that succeeded is refetched once."""
    key = Key()
    jwks = serve_jwks(router, key)
    r = receiver()
    assert reason(r, Key().sign_set(claims())) is SetFailureReason.INVALID_KEY
    assert jwks.call_count == 2, "the fill, then the one refetch"
    assert reason(r, Key().sign_set(claims())) is SetFailureReason.INVALID_KEY
    assert jwks.call_count == 2


# ── 8 ──


def test_poll_passes_ack_and_set_errs_through_and_sorts_the_answer(
    router: respx.MockRouter,
) -> None:
    """Exact body, verified and refused apart, and ``{}`` with no options."""
    key = Key()
    serve_jwks(router, key)
    stream = str(uuid.uuid4())
    good, bad = claims(), claims(iss="https://impostor.test")
    mismatched = claims()
    reply = {
        "sets": {
            good["jti"]: key.sign_set(good),
            bad["jti"]: key.sign_set(bad),
            "not-its-jti": key.sign_set(mismatched),
            "not-a-string": 42,
        },
        "moreAvailable": True,
    }
    poll = router.post(f"{BASE}/ssf/v1/poll/{stream}").mock(
        return_value=httpx.Response(200, json=reply)
    )
    r = receiver()
    result = r.poll(
        stream,
        max_events=10,
        return_immediately=True,
        ack=["done-1", "done-2"],
        set_errs={"old-1": SetErr.from_reason(SetFailureReason.REPLAYED)},
    )
    assert result.more_available is True
    assert [e.jti for e in result.events] == [good["jti"]]
    refused = {x.jti: x.reason for x in result.refused}
    assert refused == {
        bad["jti"]: SetFailureReason.INVALID_ISSUER,
        "not-its-jti": SetFailureReason.INVALID_REQUEST,
        "not-a-string": SetFailureReason.MALFORMED,
    }
    request = poll.calls[0].request
    assert json.loads(request.content) == {
        "maxEvents": 10,
        "returnImmediately": True,
        "ack": ["done-1", "done-2"],
        "setErrs": {"old-1": {"err": "invalid_request"}},
    }, "exactly as given, and nothing acknowledged on the caller's behalf"
    if not request.headers["authorization"].startswith("Bearer cc-"):
        pytest.fail("the poll did not carry the provider's bearer")
    assert "cookie" not in request.headers

    router.routes.clear()
    second = router.post(f"{BASE}/ssf/v1/poll/{stream}").mock(
        return_value=httpx.Response(200, json={"sets": {}})
    )
    empty = r.poll(stream)
    assert json.loads(second.calls[0].request.content) == {}
    assert empty.events == [] and empty.refused == [] and empty.more_available is False


def test_poll_is_not_retried_on_400_and_is_on_503(router: respx.MockRouter) -> None:
    """A retry-enabled client: 400 once (``ValidationError``), 503 retried."""
    r = receiver()
    assert r._client._retry_enabled
    refused = router.post(f"{BASE}/ssf/v1/poll/s-1").mock(
        return_value=httpx.Response(400, json={"error": "push stream"})
    )
    with pytest.raises(ValidationError):
        r.poll("s-1")
    assert refused.call_count == 1
    flaky = router.post(f"{BASE}/ssf/v1/poll/s-2").mock(
        side_effect=[httpx.Response(503), httpx.Response(200, json={"sets": {}})]
    )
    r.poll("s-2")
    assert flaky.call_count == 2
    router.post(f"{BASE}/ssf/v1/poll/s-3").mock(return_value=httpx.Response(404))
    with pytest.raises(NotFoundError):
        r.poll("s-3")


class RecordingStore:
    """A replay store whose held ``jti`` values the test reads, and which can be
    told to fail -- a store that cannot answer -- on one ``jti``."""

    def __init__(self, fail_on: str | None = None) -> None:
        """Empty; ``fail_on`` names the ``jti`` it cannot answer for."""
        self.held: set[str] = set()
        self.fail_on = fail_on
        self.asked: list[str] = []

    def check_and_record(self, jti: str, window_seconds: float) -> bool:
        """Record a new ``jti``; raise for ``fail_on``."""
        self.asked.append(jti)
        if jti == self.fail_on:
            raise RuntimeError("the replay store cannot answer")
        if jti in self.held:
            return False
        self.held.add(jti)
        return True


def test_poll_never_keeps_a_jti_it_does_not_return_when_a_later_key_fetch_fails(
    router: respx.MockRouter,
) -> None:
    """§32.8 helper test 8's two-SET batch (contract 1.59, §34.2 P1): the second
    SET names an unknown ``kid`` while the refetch fails. The first SET's ``jti``
    is not in the store, or the first SET is returned -- here, returned; the
    second is unjudged: neither returned nor refused, and not recorded."""
    key, rotated = Key(), Key()
    jwks = router.get(JWKS).mock(
        side_effect=[
            httpx.Response(200, json={"keys": [key.jwk()]}),
            httpx.Response(500),
            httpx.Response(200, json={"keys": [key.jwk(), rotated.jwk()]}),
        ]
    )
    store = RecordingStore()
    now = [1000.0]
    events: list[TelemetryEvent] = []
    r = receiver(events, replay_store=store, clock=lambda: now[0])
    first, second = claims(), claims()
    poll = router.post(f"{BASE}/ssf/v1/poll/s").mock(
        return_value=httpx.Response(
            200,
            json={
                "sets": {
                    first["jti"]: key.sign_set(first),
                    second["jti"]: rotated.sign_set(second),
                }
            },
        )
    )
    result = r.poll("s")
    assert jwks.call_count == 2, "the fill, then the failed refetch"
    returned = [e.jti for e in result.events]
    assert first["jti"] not in store.held or returned == [first["jti"]], (
        "a jti recorded but not returned is an event lost"
    )
    assert returned == [first["jti"]], "this SDK returns what it judged (P1, second form)"
    assert result.refused == [], "a failed key fetch is no verdict (P3)"
    assert result.unjudged == [second["jti"]]
    assert second["jti"] not in store.held
    assert isinstance(result.unjudged_error, NetworkError)
    assert not isinstance(result.unjudged_error, SetVerificationError)
    assert unjudged_events(events) == [
        SsfUnjudged(operation="ssf.poll", unjudged=1, category="key_fetch")
    ]

    # Re-offered once the JWKS answers again, the second SET verifies: nothing lost.
    now[0] += 61
    poll.mock(
        return_value=httpx.Response(200, json={"sets": {second["jti"]: rotated.sign_set(second)}})
    )
    again = r.poll("s", ack=[first["jti"]])
    assert [e.jti for e in again.events] == [second["jti"]]
    assert again.unjudged == [] and again.unjudged_error is None
    assert len(unjudged_events(events)) == 1, "a poll that judged everything emits none"


def test_poll_leaves_the_rest_of_a_batch_unjudged_when_the_store_cannot_answer(
    router: respx.MockRouter,
) -> None:
    """A store that cannot answer is no verdict either (P3, P4), and in a batch
    (§34.2 P1, contract 1.60) the store is asked nothing more after it: the SETs
    recorded before it are returned, it and every later SET that passes steps
    1-8 are unjudged and unrecorded, a later SET that fails them is refused as
    usual, and the poll returns normally, emitting ``ssf_unjudged``."""
    key = Key()
    serve_jwks(router, key)
    first, second, third, forged = claims(), claims(), claims(), claims(iss=f"{BASE}/other")
    store = RecordingStore(fail_on=second["jti"])
    router.post(f"{BASE}/ssf/v1/poll/s").mock(
        return_value=httpx.Response(
            200,
            json={
                "sets": {c["jti"]: key.sign_set(c) for c in (first, second, third, forged)}
                | {"m": 7}
            },
        )
    )
    events: list[TelemetryEvent] = []
    result = receiver(events, replay_store=store).poll("s")
    assert [e.jti for e in result.events] == [first["jti"]]
    assert result.refused == [
        RefusedSet(forged["jti"], SetFailureReason.INVALID_ISSUER),
        RefusedSet("m", SetFailureReason.MALFORMED),
    ]
    assert result.unjudged == [second["jti"], third["jti"]]
    assert store.held == {first["jti"]}, "every recorded jti is a returned one"
    assert store.asked == [first["jti"], second["jti"]], "nothing asked after the failure"
    assert isinstance(result.unjudged_error, NetworkError)
    assert isinstance(result.unjudged_error.__cause__, RuntimeError)
    assert unjudged_events(events) == [
        SsfUnjudged(operation="ssf.poll", unjudged=2, category="replay_store")
    ]
    rendered = repr(unjudged_events(events)[0])
    assert all(c["jti"] not in rendered for c in (first, second, third)), "no jti"


def test_a_store_failure_on_the_first_set_returns_with_nothing_recorded(
    router: respx.MockRouter,
) -> None:
    """When the store fails on the first SET that reaches it, this SDK takes
    P1's second form: ``poll`` returns normally, that SET and every later
    verified one unjudged, nothing recorded."""
    key = Key()
    serve_jwks(router, key)
    first, second = claims(), claims()
    store = RecordingStore(fail_on=first["jti"])
    router.post(f"{BASE}/ssf/v1/poll/s").mock(
        return_value=httpx.Response(
            200, json={"sets": {c["jti"]: key.sign_set(c) for c in (first, second)}}
        )
    )
    result = receiver(replay_store=store).poll("s")
    assert result.events == [] and result.refused == []
    assert result.unjudged == [first["jti"], second["jti"]]
    assert store.held == set() and store.asked == [first["jti"]]


class SdkErrorStore:
    """A store that fails with one of this SDK's own errors."""

    def __init__(self, failure: Exception) -> None:
        """Hold the error to raise."""
        self.failure = failure

    def check_and_record(self, jti: str, window_seconds: float) -> bool:
        """Raise the held error."""
        raise self.failure


def test_a_store_failure_is_a_network_error_with_its_cause_chained(
    router: respx.MockRouter,
) -> None:
    """§34.2 P3 (contract 1.60, C-1): a store failure that is not a §2 error is
    wrapped in ``NetworkError`` with the failure as its cause and no reason
    code; the SDK's own §2 error passes through unchanged; the SDK's own SET
    refusal raised by a store is wrapped too, so it carries no reason code."""
    key = Key()
    serve_jwks(router, key)
    store_down = OSError("connection reset by the cache")
    with pytest.raises(NetworkError) as wrapped:
        receiver(replay_store=SdkErrorStore(store_down)).verify_set(key.sign_set(claims()))
    assert wrapped.value.__cause__ is store_down
    assert not isinstance(wrapped.value, SetVerificationError | AuthError)

    own = NetworkError("the store's backend timed out")
    with pytest.raises(NetworkError) as passed:
        receiver(replay_store=SdkErrorStore(own)).verify_set(key.sign_set(claims()))
    assert passed.value is own

    refusal = SetVerificationError(SetFailureReason.REPLAYED, "not the store's to say")
    with pytest.raises(NetworkError) as no_reason:
        receiver(replay_store=SdkErrorStore(refusal)).verify_set(key.sign_set(claims()))
    assert not isinstance(no_reason.value, SetVerificationError)
    assert no_reason.value.__cause__ is refusal


def test_a_jwks_failure_leaves_the_poll_unjudged_and_is_not_a_verdict(
    router: respx.MockRouter,
) -> None:
    """A JWKS fetch failure is a ``NetworkError``, never a refusal: ``poll``
    leaves the SET unjudged and unrecorded (§34.2 P1, P3)."""
    key = Key()
    router.get(JWKS).mock(return_value=httpx.Response(500))
    router.post(f"{BASE}/ssf/v1/poll/s").mock(
        return_value=httpx.Response(200, json={"sets": {"j": key.sign_set(claims(jti="j"))}})
    )
    store = RecordingStore()
    result = receiver(replay_store=store).poll("s")
    assert result.events == [] and result.refused == [] and result.unjudged == ["j"]
    assert isinstance(result.unjudged_error, NetworkError)
    assert not isinstance(result.unjudged_error, SetVerificationError)
    assert store.held == set()
    for body in ("not json", json.dumps({"no": "keys"})):
        router.routes.clear()
        router.get(JWKS).mock(return_value=httpx.Response(200, text=body))
        with pytest.raises(NetworkError):
            receiver().verify_set(key.sign_set(claims()))
    router.routes.clear()
    router.get(JWKS).mock(side_effect=httpx.ConnectError("refused"))
    with pytest.raises(NetworkError):
        receiver().verify_set(key.sign_set(claims()))


def test_a_store_that_cannot_answer_is_no_verdict_for_verify_set(
    router: respx.MockRouter,
) -> None:
    """§32.8 helper test 6, contract 1.60 (§34.2 P4, row B1 *verify*): a store
    that raises is never read as ``replayed``. ``verify_set`` raises ``NetworkError``
    chaining the store's failure -- no ``SetVerificationError``, no reason code
    (P3, contract 1.60) -- the ``jti`` is
    not recorded, and the same SET verifies once the store answers again."""
    key = Key()
    serve_jwks(router, key)
    set_claims = claims()
    set_token = key.sign_set(set_claims)
    store = RecordingStore(fail_on=set_claims["jti"])
    r = receiver(replay_store=store)
    with pytest.raises(NetworkError) as failed:
        r.verify_set(set_token)
    assert not isinstance(failed.value, SetVerificationError | AuthError)
    assert isinstance(failed.value.__cause__, RuntimeError)
    assert store.held == set()
    store.fail_on = None
    assert r.verify_set(set_token).jti == set_claims["jti"], "never accepted, never refused"
    assert reason(r, set_token) is SetFailureReason.REPLAYED


def test_discovery_supplies_the_jwks_uri_and_must_name_the_issuer(
    router: respx.MockRouter,
) -> None:
    """The document's ``issuer`` must be the configured one."""
    key = Key()
    serve_jwks(router, key)
    discovery = f"{BASE}/.well-known/ssf-configuration"
    router.get(discovery).mock(
        return_value=httpx.Response(200, json={"issuer": ISSUER, "jwks_uri": JWKS})
    )
    r = receiver(jwks_uri=None, discovery_url=discovery)
    r.verify_set(key.sign_set(claims()))
    wrong = receiver(issuer="https://someone-else.test", jwks_uri=None, discovery_url=discovery)
    with pytest.raises(NetworkError) as excinfo:
        wrong.verify_set(key.sign_set(claims()))
    assert not isinstance(excinfo.value, SetVerificationError)
    for answer in (
        httpx.Response(500),
        httpx.Response(200, text="<html/>"),
        httpx.Response(200, json={"issuer": ISSUER}),
        httpx.Response(200, json={"issuer": ISSUER, "jwks_uri": "http://evil.test/jwks"}),
        httpx.Response(200, json={"issuer": ISSUER, "jwks_uri": "https://[::1/x"}),
    ):
        router.routes.clear()
        router.get(discovery).mock(return_value=answer)
        with pytest.raises(NetworkError):
            receiver(jwks_uri=None, discovery_url=discovery).verify_set(key.sign_set(claims()))


def test_poll_without_a_provider_is_refused_locally_and_repr_hides_the_provider() -> None:
    """No provider: ``AuthError`` before any request."""
    r = receiver(access_token_provider=None)
    with pytest.raises(AuthError):
        r.poll("s")
    assert "SsfReceiver" in repr(r) and "cc-" not in repr(r)
    assert "discovery_url" in repr(receiver(jwks_uri=None, discovery_url=f"{BASE}/d"))


def test_push_error_codes_are_rfc_8935_codes() -> None:
    """``malformed``, ``invalid_type`` and ``replayed`` answer ``invalid_request``."""
    expected = {
        SetFailureReason.MALFORMED: "invalid_request",
        SetFailureReason.INVALID_TYPE: "invalid_request",
        SetFailureReason.REPLAYED: "invalid_request",
        SetFailureReason.INVALID_KEY: "invalid_key",
        SetFailureReason.INVALID_ISSUER: "invalid_issuer",
        SetFailureReason.INVALID_AUDIENCE: "invalid_audience",
        SetFailureReason.INVALID_REQUEST: "invalid_request",
    }
    for r, code in expected.items():
        assert r.push_error_code() == code
        assert SetErr.from_reason(r).to_wire() == {"err": code}
    assert SetErr("invalid_key", "rotated").to_wire() == {
        "err": "invalid_key",
        "description": "rotated",
    }


def test_a_jwk_of_another_type_under_the_kid_is_invalid_key(router: respx.MockRouter) -> None:
    """An EC key published under the SET's ``kid`` cannot verify an EdDSA SET."""
    from cryptography.hazmat.primitives.asymmetric import ec
    from jwt.algorithms import ECAlgorithm

    key = Key()
    ec_jwk = json.loads(ECAlgorithm.to_jwk(ec.generate_private_key(ec.SECP256R1()).public_key()))
    ec_jwk["kid"] = key.kid
    router.get(JWKS).mock(return_value=httpx.Response(200, json={"keys": [ec_jwk]}))
    assert reason(receiver(), key.sign_set(claims())) is SetFailureReason.INVALID_KEY


def test_a_poll_survives_a_transport_failure_and_refuses_a_bad_reply(
    router: respx.MockRouter,
) -> None:
    """Transport failure retried; a reply that is not the RFC 8936 object refused."""
    r = receiver()
    flaky = router.post(f"{BASE}/ssf/v1/poll/f").mock(
        side_effect=[httpx.ConnectError("reset"), httpx.Response(200, json={"sets": {}})]
    )
    r.poll("f")
    assert flaky.call_count == 2
    for answer in (httpx.Response(200, text="nope"), httpx.Response(200, json=["sets"])):
        router.routes.clear()
        router.post(f"{BASE}/ssf/v1/poll/b").mock(return_value=answer)
        with pytest.raises(NetworkError):
            r.poll("b")


def test_an_unusable_jwk_is_a_missing_key_and_http_jwks_is_refused(
    router: respx.MockRouter,
) -> None:
    """A JWK PyJWT cannot load is skipped; a cleartext ``jwks_uri`` is refused."""
    key = Key()
    router.get(JWKS).mock(
        return_value=httpx.Response(
            200,
            json={"keys": [{"kid": key.kid, "kty": "nonsense"}, "junk", {"no": "kid"}]},
        )
    )
    assert reason(receiver(), key.sign_set(claims())) is SetFailureReason.INVALID_KEY
    for uri in ("http://jwks.example.test/k", "https://[::1/k"):
        with pytest.raises(NetworkError):
            receiver(jwks_uri=uri).verify_set(key.sign_set(claims()))


# ── The async receiver ───────────────────────────────────────────────────────


@pytest.mark.asyncio
async def test_the_async_receiver_verifies_polls_and_refuses_alike(
    router: respx.MockRouter,
) -> None:
    """Verify, replay, unknown kid, poll (async provider), 400 not retried."""
    key = Key()
    jwks = serve_jwks(router, key)
    discovery = f"{BASE}/.well-known/ssf-configuration"
    router.get(discovery).mock(
        return_value=httpx.Response(200, json={"issuer": ISSUER, "jwks_uri": JWKS})
    )
    token = f"cc-{secrets.token_urlsafe(16)}"

    async def provider() -> str:
        """An async bearer source."""
        return token

    client = AsyncAxiamClient(base_url=BASE, tenant_slug="acme")
    r = AsyncSsfReceiver(
        client,
        issuer=ISSUER,
        audience=AUDIENCE,
        discovery_url=discovery,
        access_token_provider=provider,
    )
    assert "AsyncSsfReceiver" in repr(r)
    set_token = key.sign_set(claims())
    assert (await r.verify_set(set_token)).event_type == SESSION_REVOKED
    with pytest.raises(SetVerificationError) as replayed:
        await r.verify_set(set_token)
    assert replayed.value.set_failure_reason is SetFailureReason.REPLAYED
    with pytest.raises(SetVerificationError):
        await r.verify_set(Key().sign_set(claims()))
    assert jwks.call_count == 2

    good = claims()
    poll = router.post(f"{BASE}/ssf/v1/poll/s").mock(
        return_value=httpx.Response(
            200,
            json={
                "sets": {good["jti"]: key.sign_set(good), "x": None, "y": key.sign_set(claims())},
                "moreAvailable": False,
            },
        )
    )
    result = await r.poll("s", ack=["a"])
    assert [e.jti for e in result.events] == [good["jti"]]
    assert {x.reason for x in result.refused} == {
        SetFailureReason.MALFORMED,
        SetFailureReason.INVALID_REQUEST,
    }
    if poll.calls[0].request.headers["authorization"] != f"Bearer {token}":
        pytest.fail("the poll did not carry the provider's bearer")

    refused = router.post(f"{BASE}/ssf/v1/poll/bad").mock(return_value=httpx.Response(400))
    with pytest.raises(ValidationError):
        await r.poll("bad")
    assert refused.call_count == 1
    flaky = router.post(f"{BASE}/ssf/v1/poll/flaky").mock(
        side_effect=[
            httpx.ConnectError("reset"),
            httpx.Response(503),
            httpx.Response(200, json={"sets": {}}),
        ]
    )
    await r.poll("flaky")
    assert flaky.call_count == 3

    router.post(f"{BASE}/ssf/v1/poll/ok").mock(return_value=httpx.Response(200, json={}))
    sync_provider = AsyncSsfReceiver(
        client, issuer=ISSUER, audience=AUDIENCE, jwks_uri=JWKS, access_token_provider=lambda: token
    )
    assert (await sync_provider.poll("ok")).events == []
    with pytest.raises(AuthError):
        await AsyncSsfReceiver(client, issuer=ISSUER, audience=AUDIENCE, jwks_uri=JWKS).poll("s")
    with pytest.raises(ValidationError):
        AsyncSsfReceiver(
            client, issuer=ISSUER, audience=AUDIENCE, jwks_uri=JWKS, replay_window_seconds=1
        )
    router.routes.clear()
    router.get(JWKS).mock(side_effect=httpx.ConnectError("refused"))
    with pytest.raises(NetworkError):
        await AsyncSsfReceiver(client, issuer=ISSUER, audience=AUDIENCE, jwks_uri=JWKS).verify_set(
            key.sign_set(claims())
        )
    await client.aclose()


@pytest.mark.asyncio
async def test_the_async_poll_never_keeps_a_jti_it_does_not_return(
    router: respx.MockRouter,
) -> None:
    """§32.8 helper test 8's two-SET batch over ``AsyncSsfReceiver`` (P1)."""
    key = Key()
    router.get(JWKS).mock(
        side_effect=[httpx.Response(200, json={"keys": [key.jwk()]}), httpx.Response(503)]
    )
    store = RecordingStore()
    first, second = claims(), claims()
    router.post(f"{BASE}/ssf/v1/poll/s").mock(
        return_value=httpx.Response(
            200,
            json={
                "sets": {first["jti"]: key.sign_set(first), second["jti"]: Key().sign_set(second)}
            },
        )
    )
    client = AsyncAxiamClient(base_url=BASE, tenant_slug="acme")
    r = AsyncSsfReceiver(
        client,
        issuer=ISSUER,
        audience=AUDIENCE,
        jwks_uri=JWKS,
        access_token_provider=lambda: f"cc-{secrets.token_urlsafe(16)}",
        replay_store=store,
    )
    result = await r.poll("s")
    assert first["jti"] not in store.held or [e.jti for e in result.events] == [first["jti"]]
    assert [e.jti for e in result.events] == [first["jti"]]
    assert result.refused == [] and result.unjudged == [second["jti"]]
    assert second["jti"] not in store.held
    assert isinstance(result.unjudged_error, NetworkError)
    await client.aclose()


class AsyncRecordingStore:
    """An asynchronous replay store, as a shared store over an async driver is."""

    def __init__(self) -> None:
        """Empty."""
        self.held: set[str] = set()
        self.calls = 0

    async def check_and_record(self, jti: str, window_seconds: float) -> bool:
        """Record a new ``jti`` after yielding to the loop."""
        self.calls += 1
        await asyncio.sleep(0)
        if jti in self.held:
            return False
        self.held.add(jti)
        return True


@pytest.mark.asyncio
async def test_the_async_receiver_awaits_an_async_replay_store(router: respx.MockRouter) -> None:
    """``AsyncSsfReceiver`` takes a store whose ``check_and_record`` is a
    coroutine, awaits it, and refuses the second sighting as ``replayed``."""
    key = Key()
    serve_jwks(router, key)
    store = AsyncRecordingStore()
    client = AsyncAxiamClient(base_url=BASE, tenant_slug="acme")
    r = AsyncSsfReceiver(
        client, issuer=ISSUER, audience=AUDIENCE, jwks_uri=JWKS, replay_store=store
    )
    set_token = key.sign_set(claims())
    event = await r.verify_set(set_token)
    assert store.held == {event.jti} and store.calls == 1
    with pytest.raises(SetVerificationError) as replayed:
        await r.verify_set(set_token)
    assert replayed.value.set_failure_reason is SetFailureReason.REPLAYED
    assert store.calls == 2
    await client.aclose()


class FailingAsyncStore:
    """An asynchronous store that cannot answer for one ``jti``."""

    def __init__(self, fail_on: str) -> None:
        """Name the ``jti`` it cannot answer for."""
        self.held: set[str] = set()
        self.fail_on: str | None = fail_on

    async def check_and_record(self, jti: str, window_seconds: float) -> bool:
        """Record a new ``jti``; raise for ``fail_on``."""
        await asyncio.sleep(0)
        if jti == self.fail_on:
            raise RuntimeError("the replay store cannot answer")
        if jti in self.held:
            return False
        self.held.add(jti)
        return True


@pytest.mark.asyncio
async def test_the_async_store_that_cannot_answer_is_no_verdict(router: respx.MockRouter) -> None:
    """§32.8 helper test 6, store-failure case, under ``AsyncSsfReceiver``:
    ``verify_set`` raises ``NetworkError`` chaining the store's failure (never
    ``replayed``) and ``poll``
    returns the SET in neither ``events`` nor ``refused``, unrecorded."""
    key = Key()
    serve_jwks(router, key)
    first, second = claims(), claims()
    store = FailingAsyncStore(fail_on=second["jti"])
    client = AsyncAxiamClient(base_url=BASE, tenant_slug="acme")
    r = AsyncSsfReceiver(
        client, issuer=ISSUER, audience=AUDIENCE, jwks_uri=JWKS, replay_store=store
    )
    with pytest.raises(NetworkError) as failed:
        await r.verify_set(key.sign_set(second))
    assert not isinstance(failed.value, SetVerificationError | AuthError)
    assert isinstance(failed.value.__cause__, RuntimeError)
    assert store.held == set()

    token = f"cc-{secrets.token_urlsafe(8)}"
    r2 = AsyncSsfReceiver(
        client,
        issuer=ISSUER,
        audience=AUDIENCE,
        jwks_uri=JWKS,
        replay_store=store,
        access_token_provider=lambda: SecretStr(token),
    )
    router.post(f"{BASE}/ssf/v1/poll/s").mock(
        return_value=httpx.Response(
            200, json={"sets": {c["jti"]: key.sign_set(c) for c in (first, second)}}
        )
    )
    result = await r2.poll("s")
    assert [e.jti for e in result.events] == [first["jti"]]
    assert result.refused == []
    assert result.unjudged == [second["jti"]]
    assert store.held == {first["jti"]}
    assert isinstance(result.unjudged_error, NetworkError)
    assert isinstance(result.unjudged_error.__cause__, RuntimeError)
    await client.aclose()


@pytest.mark.asyncio
async def test_the_async_failed_cold_cache_fill_counts(router: respx.MockRouter) -> None:
    """Row A3 under ``AsyncSsfReceiver``: a failed fill counts toward the limit."""
    key = Key()
    jwks = router.get(JWKS).mock(
        side_effect=[httpx.Response(503), httpx.Response(200, json={"keys": [key.jwk()]})]
    )
    now = [1000.0]
    client = AsyncAxiamClient(base_url=BASE, tenant_slug="acme")
    r = AsyncSsfReceiver(
        client, issuer=ISSUER, audience=AUDIENCE, jwks_uri=JWKS, clock=lambda: now[0]
    )
    for _ in range(2):
        with pytest.raises(NetworkError) as failed:
            await r.verify_set(key.sign_set(claims()))
        assert not isinstance(failed.value, SetVerificationError)
    assert jwks.call_count == 1
    now[0] += 61
    await r.verify_set(key.sign_set(claims()))
    assert jwks.call_count == 2
    await client.aclose()
