"""NEW-4 AMQP v2 replay-protection tests.

Ground truth: ``testdata/v2_reference_vectors.json`` (CONTRACT.md §8)
— server-generated (Rust ``axiam-amqp`` signer) canonical bytes and HMAC for
the v2 ``AuthzRequest``/``AuditEventMessage`` wire shape. v2 adds
``key_version``, ``nonce``, ``issued_at`` to the signed body in declaration
order, after the message's existing fields and before ``hmac_signature``.

``axiam_sdk.amqp._hmac.verify_hmac`` is schema-agnostic (it re-serializes
whatever keys arrived, minus ``hmac_signature``, in received order) so it
needs NO change to cover the new fields — the tests below prove that
byte-for-byte against the real server vectors for BOTH message types, then
exercise the NEW-4 validation this plan adds on top:
``axiam_sdk.amqp._replay.validate_freshness`` (key_version >= 2, issued_at
within an allowed clock-skew window, nonce not replayed) and its wiring
into ``axiam_sdk.amqp._consumer._on_message``.

The HMAC key used throughout is the fixture's ``hkdf.derived_subkey_hex`` —
the SDK's HMAC layer takes a pre-derived per-tenant subkey as an opaque
``bytes`` value (see ``_hmac.py``'s docstring); HKDF derivation of that
subkey from a tenant's master key is a management-plane concern, not part
of the message-verification path this SDK implements.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import logging
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

import pytest

from axiam_sdk.amqp._consumer import _on_message
from axiam_sdk.amqp._hmac import verify_hmac
from axiam_sdk.amqp._replay import NonceStore, validate_freshness

# Vendored from the server monorepo's ground-truth location,
# crates/axiam-amqp/tests/fixtures/v2_reference_vectors.json — generated by the
# Rust server's sign path. This SDK ships in its own repository and has no
# crates/ tree to read from, so the vectors are vendored at testdata/ (see
# CONTRACT.md §8). Refresh them from the server repo whenever the v2 wire shape
# changes; the tests below are what catch the drift.
FIXTURES_PATH = Path(__file__).resolve().parents[1] / "testdata" / "v2_reference_vectors.json"


def _load_reference() -> dict[str, Any]:
    with FIXTURES_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


REFERENCE = _load_reference()
SUBKEY = bytes.fromhex(REFERENCE["hkdf"]["derived_subkey_hex"])
MESSAGE_KEYS = ["authz_request", "audit_event"]


def _wire_body(vector: dict[str, Any]) -> bytes:
    """Reconstruct the exact bytes that went over the wire for a reference
    vector: ``canonical_signed_json`` (the signed body, with
    ``hmac_signature`` ABSENT) plus ``hmac_signature`` appended as the
    final field. The fixture's ``field_order`` confirms ``hmac_signature``
    is always last (it does not exist until after signing), so this
    reconstruction is exact, not an approximation."""
    canonical = vector["canonical_signed_json"]
    assert canonical.endswith("}"), "canonical_signed_json must be a JSON object"
    body_str = canonical[:-1] + f',"hmac_signature":"{vector["hmac_signature_hex"]}"' + "}"
    return body_str.encode("utf-8")


def _issued_at(vector: dict[str, Any]) -> datetime:
    return datetime.fromisoformat(vector["message"]["issued_at"].replace("Z", "+00:00"))


class _RecordingProcessContext:
    async def __aenter__(self) -> _RecordingProcessContext:
        return self

    async def __aexit__(self, *exc_info: object) -> bool:
        return False


class RecordingMessage:
    """Minimal recording fake ``AbstractIncomingMessage`` double (see
    ``test_amqp_consumer.py`` for the canonical version of this fake)."""

    def __init__(self, body: bytes) -> None:
        self.body = body
        self.acked = False
        self.nacked: bool | None = None

    def process(self, ignore_processed: bool = False) -> _RecordingProcessContext:
        return _RecordingProcessContext()

    async def ack(self, multiple: bool = False) -> None:
        self.acked = True

    async def nack(self, multiple: bool = False, requeue: bool = True) -> None:
        self.nacked = requeue


# --- Fixture byte-parity: verify_hmac / canonicalization need no change ---


@pytest.mark.parametrize("message_key", MESSAGE_KEYS)
def test_reference_vector_hmac_reproduces_expected_signature(message_key: str) -> None:
    """HMAC-SHA256(derived_subkey, canonical_signed_json) reproduces
    hmac_signature_hex byte-for-byte for both message types."""
    vector = REFERENCE[message_key]
    canonical_bytes = vector["canonical_signed_json"].encode("utf-8")
    computed = hmac.new(SUBKEY, canonical_bytes, hashlib.sha256).hexdigest()
    assert computed == vector["hmac_signature_hex"]


@pytest.mark.parametrize("message_key", MESSAGE_KEYS)
def test_reference_vector_verify_hmac_accepts(message_key: str) -> None:
    """The Python verifier ACCEPTS the server-signed v2 message body as-is
    — no schema/canonicalization change was needed for key_version/nonce/
    issued_at."""
    vector = REFERENCE[message_key]
    assert verify_hmac(SUBKEY, _wire_body(vector)) is True


@pytest.mark.parametrize("message_key", MESSAGE_KEYS)
def test_reference_vector_round_trip_reproduces_canonical_bytes(message_key: str) -> None:
    """parse -> pop(hmac_signature) -> dumps reproduces
    canonical_signed_json exactly, proving the fields ride along as
    ordinary (order-preserved) object keys with no special-casing."""
    vector = REFERENCE[message_key]
    parsed = json.loads(_wire_body(vector))
    parsed.pop("hmac_signature")
    reproduced = json.dumps(parsed, separators=(",", ":"))
    assert reproduced == vector["canonical_signed_json"]


@pytest.mark.parametrize("message_key", MESSAGE_KEYS)
def test_reference_vector_passes_freshness_checks_near_issuance(message_key: str) -> None:
    """key_version/issued_at/nonce as actually issued pass NEW-4's checks
    when evaluated shortly after issuance (well within the default skew)."""
    vector = REFERENCE[message_key]
    event = json.loads(_wire_body(vector))
    event.pop("hmac_signature")
    now = _issued_at(vector) + timedelta(minutes=2)
    store = NonceStore(ttl_seconds=600)
    assert validate_freshness(event, store, skew_seconds=300, now=now) is None


# --- Full accept path through _on_message ---


async def test_on_message_accepts_reference_vector_end_to_end() -> None:
    vector = REFERENCE["authz_request"]
    message = RecordingMessage(_wire_body(vector))
    now = _issued_at(vector) + timedelta(minutes=2)
    store = NonceStore(ttl_seconds=600)
    logger = logging.getLogger("test.axiam_sdk.amqp.v2_replay")
    handler_events: list[dict[str, Any]] = []

    async def handler(event: dict[str, Any]) -> None:
        handler_events.append(event)

    await _on_message(
        message, SUBKEY, handler, logger, nonce_store=store, skew_seconds=300, now=now
    )

    assert message.acked is True
    assert message.nacked is None
    assert len(handler_events) == 1
    assert "hmac_signature" not in handler_events[0]
    assert handler_events[0]["nonce"] == vector["message"]["nonce"]
    assert handler_events[0]["key_version"] == 2


# --- REJECT: key_version < 2 ---


async def test_on_message_rejects_key_version_1() -> None:
    """A message downgraded to key_version=1 (and re-signed with the same
    subkey, so the signature itself is valid) MUST still be rejected —
    the v2 replay-protection floor is enforced independently of the HMAC
    outcome."""
    vector = REFERENCE["authz_request"]
    event = json.loads(_wire_body(vector))
    event.pop("hmac_signature")
    event["key_version"] = 1

    canonical = json.dumps(event, separators=(",", ":")).encode("utf-8")
    resigned = hmac.new(SUBKEY, canonical, hashlib.sha256).hexdigest()
    event["hmac_signature"] = resigned
    body = json.dumps(event, separators=(",", ":")).encode("utf-8")

    # Sanity: the re-signed downgraded body DOES verify_hmac successfully
    # — proves key_version rejection is a separate check, not a side
    # effect of a broken signature.
    assert verify_hmac(SUBKEY, body) is True

    message = RecordingMessage(body)
    now = _issued_at(vector) + timedelta(minutes=2)
    logger = logging.getLogger("test.axiam_sdk.amqp.v2_replay")
    handler_calls = 0

    async def handler(_event: dict[str, Any]) -> None:
        nonlocal handler_calls
        handler_calls += 1

    await _on_message(
        message,
        SUBKEY,
        handler,
        logger,
        nonce_store=NonceStore(ttl_seconds=600),
        skew_seconds=300,
        now=now,
    )

    assert message.acked is False
    assert message.nacked is False  # requeue=False, same as an HMAC failure
    assert handler_calls == 0


# --- REJECT: stale issued_at ---


async def test_on_message_rejects_stale_issued_at() -> None:
    """A validly-signed, non-replayed v2 message is still rejected if
    issued_at falls outside the allowed clock-skew window."""
    vector = REFERENCE["audit_event"]
    message = RecordingMessage(_wire_body(vector))
    # 20 minutes after issuance, well outside the default 5-minute skew.
    now = _issued_at(vector) + timedelta(minutes=20)
    logger = logging.getLogger("test.axiam_sdk.amqp.v2_replay")
    handler_calls = 0

    async def handler(_event: dict[str, Any]) -> None:
        nonlocal handler_calls
        handler_calls += 1

    await _on_message(
        message,
        SUBKEY,
        handler,
        logger,
        nonce_store=NonceStore(ttl_seconds=600),
        skew_seconds=300,
        now=now,
    )

    assert message.acked is False
    assert message.nacked is False  # requeue=False
    assert handler_calls == 0


# --- REJECT: replayed nonce ---


async def test_on_message_rejects_replayed_nonce() -> None:
    """The SAME wire body delivered twice through the SAME NonceStore is
    accepted once and rejected the second time — the store must persist
    across deliveries (as it does across a real consume() loop) for
    replay detection to mean anything."""
    vector = REFERENCE["authz_request"]
    body = _wire_body(vector)
    now = _issued_at(vector) + timedelta(minutes=1)
    store = NonceStore(ttl_seconds=600)
    logger = logging.getLogger("test.axiam_sdk.amqp.v2_replay")
    handler_calls = 0

    async def handler(_event: dict[str, Any]) -> None:
        nonlocal handler_calls
        handler_calls += 1

    first = RecordingMessage(body)
    await _on_message(first, SUBKEY, handler, logger, nonce_store=store, skew_seconds=300, now=now)
    assert first.acked is True
    assert handler_calls == 1

    second = RecordingMessage(body)  # identical body -> identical nonce
    await _on_message(second, SUBKEY, handler, logger, nonce_store=store, skew_seconds=300, now=now)
    assert second.acked is False
    assert second.nacked is False  # requeue=False
    assert handler_calls == 1  # handler NOT invoked a second time
