#!/usr/bin/env python3
"""Generate the CONTRACT §27 management surface for the Python SDK.

Reads ``management-registry.json`` (the 146 operations across 24 namespaces,
maintained in ``ilpanich/axiam`` and vendored here) plus ``openapi.json`` for the
schemas those operations carry, and writes:

- ``src/axiam_sdk/management/models.py`` — every request and response type;
- ``src/axiam_sdk/management/ops/<namespace>.py`` — one namespace handle per
  namespace, in a sync and an async form;
- ``src/axiam_sdk/management/ops/__init__.py`` — the accessors the clients mix in;
- ``tests/test_management_surface_generated.py`` — one conformance case per
  operation, plus the §27.9 assertion that all 146 are reached.

Run with ``--check`` to verify the committed output is current; that is what CI
runs, so a registry change that is not regenerated fails the build rather than
shipping a surface that disagrees with the contract.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
REGISTRY: dict[str, Any] = json.loads((ROOT / "management-registry.json").read_text())
SPEC: dict[str, Any] = json.loads((ROOT / "openapi.json").read_text())
SCHEMAS: dict[str, Any] = SPEC["components"]["schemas"]

BANNER = """# @generated by scripts/gen_management.py from management-registry.json and
# openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
# `python scripts/gen_management.py`; CI verifies the committed output is current.
"""

# §27.4 rule 3: `{org_id}` always defaults from the client. `{tenant_id}`
# defaults from the client only where it names the *context*; in `tenants` and
# the signing-CA routes it names the object being acted on.
IMPLICIT_TENANT_NAMESPACES = {"email_config", "settings", "webauthn_policy"}

# Schema names that would collide with a type this SDK already exports from its
# package root. The generated surface is re-exported, so a duplicate name makes
# one of the two unreachable.
RENAMED_SCHEMAS = {
    # §23's `OpaqueEnrollment` (axiam_sdk._models) is the enrolment *result* a
    # caller receives; this is the registration payload a caller *sends* when
    # creating a user. Different shapes, same server-side vocabulary.
    "OpaqueEnrollment": "OpaqueEnrollmentPayload",
}

PY_KEYWORDS = {
    "and",
    "as",
    "assert",
    "async",
    "await",
    "break",
    "class",
    "continue",
    "def",
    "del",
    "elif",
    "else",
    "except",
    "finally",
    "for",
    "from",
    "global",
    "if",
    "import",
    "in",
    "is",
    "lambda",
    "none",
    "nonlocal",
    "not",
    "or",
    "pass",
    "raise",
    "return",
    "try",
    "while",
    "with",
    "yield",
}

EXAMPLE_UUID = "11111111-1111-4111-8111-111111111111"
EXAMPLE_TIME = "2026-08-26T00:00:00Z"


# ---------------------------------------------------------------------------
# Naming
# ---------------------------------------------------------------------------


def pascal(text: str) -> str:
    """``service_accounts`` -> ``ServiceAccounts``, with the rename map applied."""
    parts = [p for p in text.replace("-", "_").replace(" ", "_").split("_") if p]
    joined = "".join(p[0].upper() + p[1:] for p in parts)
    return RENAMED_SCHEMAS.get(joined, joined)


def snake(text: str) -> str:
    """``ServiceAccounts`` -> ``service_accounts``; already-snake input is kept."""
    out: list[str] = []
    for i, ch in enumerate(text):
        boundary = not text[i - 1].isupper() or (i + 1 < len(text) and text[i + 1].islower())
        if ch.isupper() and i and boundary:
            out.append("_")
        out.append(ch.lower())
    return "".join(out).replace("-", "_").replace("__", "_")


def safe(name: str) -> str:
    """A Python-legal identifier for ``name``, keywords suffixed."""
    ident = snake(name)
    return f"{ident}_" if ident in PY_KEYWORDS else ident


def wrap(text: str, width: int = 76) -> list[str]:
    """Reflow ``text`` into paragraph-preserving lines; ruff does not reflow docstrings."""
    out: list[str] = []
    for para in str(text).strip().split("\n\n"):
        words = para.split()
        if not words:
            continue
        line = ""
        for word in words:
            if line and len(line) + 1 + len(word) > width:
                out.append(line)
                line = word
            else:
                line = f"{line} {word}" if line else word
        if line:
            out.append(line)
        out.append("")
    while out and out[-1] == "":
        out.pop()
    return out


def docstring(text: str, indent: str = "") -> list[str]:
    """A PEP 257 docstring block for ``text`` at ``indent``."""
    lines = wrap(text, 76 - len(indent))
    if not lines:
        return [f'{indent}"""Undocumented."""']
    if len(lines) == 1 and len(indent) + len(lines[0]) + 6 <= 96 and not lines[0].endswith('"'):
        return [f'{indent}"""{lines[0]}"""']
    body = [f'{indent}"""{lines[0]}']
    for line in lines[1:]:
        body.append(f"{indent}{line}" if line else "")
    body.append(f'{indent}"""')
    return body


def field_doc(text: str, indent: str = "    ") -> list[str]:
    """An attribute docstring, the Sphinx-recognised form for a field."""
    lines = wrap(text, 76 - len(indent))
    if not lines:
        return []
    if len(lines) == 1:
        return [f'{indent}"""{lines[0]}"""']
    rest = [f"{indent}{x}" if x else "" for x in lines[1:]]
    return [f'{indent}"""{lines[0]}', "", *rest, f'{indent}"""']


# ---------------------------------------------------------------------------
# Schema analysis
# ---------------------------------------------------------------------------


def resolve_ref(schema: Any) -> Any:
    """Follow ``$ref`` chains to the schema they name."""
    node = schema
    while isinstance(node, dict) and "$ref" in node:
        node = SCHEMAS.get(node["$ref"].split("/")[-1], {})
    return node


def nullable_ref(schema: Any) -> str | None:
    """``{oneOf: [{type: null}, {$ref: X}]}`` -- utoipa's optional-enum shape."""
    variants = schema.get("oneOf") if isinstance(schema, dict) else None
    if not isinstance(variants, list) or len(variants) != 2:
        return None
    nulls = [v for v in variants if v.get("type") == "null"]
    refs = [v for v in variants if "$ref" in v]
    return refs[0]["$ref"].split("/")[-1] if len(nulls) == 1 and len(refs) == 1 else None


def py_type(schema: Any) -> str:
    """The Python annotation for ``schema``."""
    if not schema:
        return "Any"
    if "$ref" in schema:
        return pascal(schema["$ref"].split("/")[-1])
    inner = nullable_ref(schema)
    if inner:
        return f"{pascal(inner)} | None"
    if "oneOf" in schema or "anyOf" in schema:
        return "Any"

    kind = schema.get("type")
    nullable = False
    if isinstance(kind, list):
        nullable = "null" in kind
        kind = next((k for k in kind if k != "null"), None)

    if "enum" in schema:
        base = "Literal[" + ", ".join(json.dumps(v) for v in schema["enum"]) + "]"
    elif kind == "string":
        base = "str"
    elif kind == "integer":
        base = "int"
    elif kind == "number":
        base = "float"
    elif kind == "boolean":
        base = "bool"
    elif kind == "array":
        base = f"list[{py_type(schema.get('items') or {})}]"
    elif kind == "object":
        base = "dict[str, Any]"
    else:
        base = "Any"
    return f"{base} | None" if nullable else base


def flatten(name: str) -> tuple[dict[str, Any], set[str], str | None]:
    """Properties, required set and description of ``name``, ``allOf`` resolved."""
    props: dict[str, Any] = {}
    required: set[str] = set()

    def absorb(node: Any) -> None:
        """Merge one ``allOf`` member's properties into the accumulator."""
        resolved = resolve_ref(node) if "$ref" in node else node
        props.update(resolved.get("properties") or {})
        required.update(resolved.get("required") or [])
        for sub in resolved.get("allOf") or []:
            absorb(sub)

    schema = SCHEMAS.get(name, {})
    absorb(schema)
    return props, required, schema.get("description")


def discriminated(schema: Any) -> tuple[str, list[tuple[str, Any]]] | None:
    """Detect an internally-tagged union and return ``(tag, [(value, payload)])``."""
    variants = schema.get("oneOf")
    if not isinstance(variants, list) or len(variants) < 2:
        return None
    tag: str | None = None
    arms: list[tuple[str, Any]] = []
    for variant in variants:
        parts = variant.get("allOf") or [variant]
        value: str | None = None
        payload: Any = None
        leftovers: dict[str, Any] = {"type": "object", "properties": {}, "required": []}
        for part in parts:
            if "$ref" in part:
                payload = part
                continue
            for pname, prop in (part.get("properties") or {}).items():
                enum = prop.get("enum")
                if prop.get("type") == "string" and isinstance(enum, list) and len(enum) == 1:
                    if tag and tag != pname:
                        return None
                    tag = pname
                    value = enum[0]
                else:
                    leftovers["properties"][pname] = prop
                    if pname in (part.get("required") or []):
                        leftovers["required"].append(pname)
        if value is None:
            return None
        arms.append((value, payload if payload is not None else leftovers))
    return (tag or "", arms)


def sensitive_map() -> dict[str, set[str]]:
    """Which fields of which schemas carry a secret, per the registry."""
    out: dict[str, set[str]] = {}
    for ns in REGISTRY["namespaces"].values():
        for op in ns["operations"].values():
            if op["request_schema"] and op["sensitive_request_fields"]:
                key = op["request_schema"].lstrip("[]")
                out.setdefault(key, set()).update(op["sensitive_request_fields"])
            if op["response"]["schema"] and op["sensitive_response_fields"]:
                key = op["response"]["schema"].lstrip("[]")
                out.setdefault(key, set()).update(op["sensitive_response_fields"])
    return out


def schema_closure() -> list[str]:
    """Every schema reachable from an operation, transitively, sorted."""
    seeds: set[str] = set()
    for ns in REGISTRY["namespaces"].values():
        for op in ns["operations"].values():
            if op["request_schema"]:
                seeds.add(op["request_schema"].lstrip("[]"))
            if op["response"]["schema"]:
                seeds.add(op["response"]["schema"].lstrip("[]"))

    def refs_in(node: Any, found: set[str]) -> None:
        """Collect every ``$ref`` target name appearing anywhere under ``node``."""
        if isinstance(node, list):
            for item in node:
                refs_in(item, found)
        elif isinstance(node, dict):
            if "$ref" in node:
                found.add(node["$ref"].split("/")[-1])
            for value in node.values():
                refs_in(value, found)

    seen: set[str] = set()
    frontier = list(seeds)
    while frontier:
        name = frontier.pop()
        if name in seen or name not in SCHEMAS:
            continue
        seen.add(name)
        found: set[str] = set()
        refs_in(SCHEMAS[name], found)
        frontier.extend(f for f in found if f not in seen)
    return sorted(seen)


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

MODELS_HEADER = '''"""Request and response types for the CONTRACT §27 management surface.

Three shapes recur and are worth knowing before reading:

- **Sparse update bodies.** Every field is optional, and a field you never set
  is *absent from the wire body* rather than sent as ``null`` -- so a body
  carrying one field changes one field (§27.4 rule 5). Setting a field to
  ``None`` explicitly is a different statement and does send ``null``.
- **Replacement bodies.** ``SetOrgSettings``, the organization email config,
  ``WebauthnAttestationPolicy`` and ``SetMtlsTrustAnchor`` have required fields,
  because a ``PUT`` on those routes replaces rather than patches. Pydantic
  refuses to build one half-filled, which is the point.
- **Types carrying a secret.** These hold a :class:`~pydantic.SecretStr`, so the
  value is redacted from every ``repr``, log line and JSON rendering; call
  ``.get_secret_value()`` to read it. :meth:`~axiam_sdk.management._wire.ManagementModel.to_wire`
  is the one place they are unwrapped for the socket.
"""
'''


def field_lines(
    name: str,
    schema: Any,
    *,
    required: bool,
    secret: bool,
) -> list[str]:
    """One model field: its annotation, default and attribute docstring."""
    annotation = "SecretStr" if secret else py_type(schema)
    ident = safe(name)
    alias = f'Field(alias="{name}")' if ident != name else None

    if required:
        default = f" = {alias}" if alias else ""
    elif annotation.endswith("| None"):
        default = f' = Field(default=None, alias="{name}")' if alias else " = None"
    else:
        annotation = f"{annotation} | None"
        default = f' = Field(default=None, alias="{name}")' if alias else " = None"

    text = schema.get("description") or f"``{name}``."
    if secret:
        text += (
            "\n\n**Secret.** Redacted from every string, log and JSON rendering; "
            "call ``.get_secret_value()`` to read it."
        )
    return [f"    {ident}: {annotation}{default}", *field_doc(text)]


def emit_model_class(
    class_name: str,
    props: dict[str, Any],
    required: set[str],
    description: str | None,
    secrets: set[str],
    extra: list[str],
) -> list[str]:
    """A pydantic model class for ``class_name`` over ``props``."""
    all_optional = bool(props) and not required
    text = description or f"``{class_name}`` (generated from openapi.json)."
    if all_optional:
        text += (
            "\n\nEvery field is optional, so this is a **sparse** body: what you leave "
            "out is left unchanged, and is omitted from the wire request entirely rather "
            "than sent as ``null`` (§27.4 rule 5)."
        )
    lines = [f"class {class_name}(ManagementModel):", *docstring(text, "    "), ""]
    lines.extend(extra)
    body_written = bool(extra)
    for pname in sorted(props):
        lines.extend(
            field_lines(
                pname,
                props[pname],
                required=pname in required,
                secret=pname in secrets,
            )
        )
        lines.append("")
        body_written = True
    if not body_written:
        lines.append("    # The server documents no fields on this schema.")
        lines.append("")
    return lines


def emit_models() -> str:
    """The whole ``models.py`` module."""
    secrets = sensitive_map()
    projections = projection_map()
    classes: list[str] = []
    out: list[str] = [
        BANNER,
        MODELS_HEADER,
        "from __future__ import annotations",
        "",
        "from typing import Annotated, Any, Literal",
        "",
        "from pydantic import Field, SecretStr, TypeAdapter",
        "",
        "from axiam_sdk.management._wire import ManagementModel",
    ]
    # isort (ruff I001) wants a single blank line between the import block and a
    # following assignment, and two before a `class`. Which one comes first here
    # depends on where the alphabet puts the schema, so decide it rather than assume.
    first = SCHEMAS[schema_closure()[0]]
    out.append("")
    if not ("enum" in first or discriminated(first)):
        out.append("")

    for name in schema_closure():
        schema = SCHEMAS[name]
        rname = pascal(name)
        if "enum" in schema:
            text = schema.get("description") or f"``{rname}`` (generated from openapi.json)."
            text += (
                "\n\nAn **open** enum. The trailing ``| str`` is what makes a value this "
                "SDK's copy of the spec does not list validate instead of raising -- "
                "CONTRACT §27.11 rule 1. A bare ``Literal`` is validated strictly by "
                "pydantic, so the next value the server adds would fail the *whole* "
                "response it arrived in, taking down every record on the page over one "
                "field of one of them. The listed members stay in the annotation because "
                "they are what a reader needs; what the widening removes is the claim "
                "that nothing else can occur."
            )
            members = [json.dumps(v) for v in schema["enum"]]
            oneline = f"{rname} = Literal[" + ", ".join(members) + "] | str"
            if len(oneline) <= 100:
                out.append(oneline)
            else:
                out.append(f"{rname} = (")
                out.append("    Literal[")
                out.extend(f"        {m}," for m in members)
                out.append("    ]")
                out.append("    | str")
                out.append(")")
            out.extend(field_doc(text, ""))
            out.append("")
            out.append("")
            continue

        union = discriminated(schema)
        if union:
            tag, arms = union
            arm_names: list[str] = []
            for value, payload in arms:
                arm = f"{rname}{pascal(value)}"
                arm_names.append(arm)
                if "$ref" in payload:
                    props, req, desc = flatten(payload["$ref"].split("/")[-1])
                else:
                    props = payload.get("properties") or {}
                    req = set(payload.get("required") or [])
                    desc = payload.get("description")
                tag_lines = [
                    f"    {safe(tag)}: Literal[{json.dumps(value)}]",
                    *field_doc(f"Discriminator: always ``{value}``."),
                    "",
                ]
                out.extend(
                    emit_model_class(
                        arm,
                        {k: v for k, v in props.items() if k != tag},
                        req - {tag},
                        desc or f"The ``{value}`` arm of :data:`{rname}`.",
                        set(),
                        tag_lines,
                    )
                )
                out.append("")
                classes.append(arm)
            text = schema.get("description") or (
                f"``{rname}`` -- a union discriminated by ``{tag}``."
            )
            out.append(f"{rname} = Annotated[")
            joined = "    " + " | ".join(arm_names) + ","
            if len(joined) <= 100:
                out.append(joined)
            else:
                for i, arm in enumerate(arm_names):
                    lead = "    " if i == 0 else "    | "
                    tail = "," if i == len(arm_names) - 1 else ""
                    out.append(f"{lead}{arm}{tail}")
            out.append(f'    Field(discriminator="{safe(tag)}"),')
            out.append("]")
            out.extend(field_doc(text, ""))
            out.append("")
            out.append(f"{rname}Adapter: TypeAdapter[{rname}] = TypeAdapter({rname})")
            out.extend(
                field_doc(
                    f"Validates a :data:`{rname}` payload.\n\nAn ``Annotated`` union alias "
                    f"has no ``model_validate`` of its own; this is built once at import "
                    f"rather than per call.",
                    "",
                )
            )
            out.append("")
            out.append("")
            continue

        props, required, description = flatten(name)
        props = dict(props)
        for add in projections.get(name, []):
            if add["name"] in props:
                continue
            required.discard(add["name"])
            props[add["name"]] = {
                "type": add.get("type"),
                "format": add.get("format"),
                "description": (
                    "Resolved by the list projection only.\n\n"
                    "The server resolves this for a whole page in one query, so it is "
                    "populated by the ``list`` operation and is ``None`` on ``get`` "
                    '(CONTRACT §27.11 rule 4). ``None`` there means "this read does not '
                    'carry it", not "there is nothing bound" -- the SDK does not issue '
                    "a second request to fill it in."
                ),
            }
        out.extend(
            emit_model_class(rname, props, required, description, secrets.get(name, set()), [])
        )
        out.append("")
        classes.append(rname)

    out.append("# Every annotation in this module is a string (`from __future__ import")
    out.append("# annotations`), so the forward references between these models are resolved")
    out.append("# here rather than lazily on first validation -- a broken reference should")
    out.append("# fail at import, where it names itself, not inside an unrelated request.")
    out.append("for _model in (")
    for cls in classes:
        out.append(f"    {cls},")
    out.append("):")
    out.append("    _model.model_rebuild()")
    out.append("")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Operations
# ---------------------------------------------------------------------------


def implicit_params(namespace: str, op: dict[str, Any]) -> set[str]:
    """Which of this operation's path params default from the client (§27.4 rule 3)."""
    names = {p["name"] for p in op["path_params"]}
    out: set[str] = set()
    if "org_id" in names:
        out.add("org_id")
    if "tenant_id" in names and namespace in IMPLICIT_TENANT_NAMESPACES:
        out.add("tenant_id")
    return out


def split_query(op: dict[str, Any]) -> tuple[list[Any], list[Any]]:
    """This operation's non-paging query params, split required / optional."""
    extra = extra_query_params(op)
    return [q for q in extra if q["required"]], [q for q in extra if not q["required"]]


def extra_query_params(op: dict[str, Any]) -> list[dict[str, Any]]:
    """Query parameters that become method arguments, rather than ``PageRequest``.

    ``offset`` and ``limit`` have always come from ``PageRequest``. ``search``
    joins them on paginated operations (CONTRACT §27.4 rule 4): the term is part
    of which page this is, and putting it on the page request rather than on each
    of the twenty generated ``list`` methods is what makes ``collect_pages`` carry
    it across the whole walk instead of filtering only the first request.

    The ``paginated`` guard matters. A *non*-paginated operation that grew a
    ``search`` parameter would have no ``PageRequest`` to carry it, so it keeps
    its own argument -- none exists in the registry today, and this is what keeps
    that from silently dropping the parameter if one ever does.
    """
    owned = ("offset", "limit", "search") if op["paginated"] else ("offset", "limit")
    return [q for q in op["query_params"] if q["name"] not in owned]


def projection_map() -> dict[str, list[dict[str, Any]]]:
    """Schema name -> the fields a list projection adds on top of it.

    ``certificates.list`` answers ``Certificate`` plus ``bound_service_account_id``,
    a graph edge the server resolves for the whole page in one query. CONTRACT
    §27.11 rule 4 lets an SDK carry that as an optional field on the base type,
    which is what this does: the field is ``None`` on ``get``, and the SDK never
    synthesizes it there with a second request.
    """
    out: dict[str, list[dict[str, Any]]] = {}
    for nsdef in REGISTRY["namespaces"].values():
        for op in nsdef["operations"].values():
            adds = op["response"].get("projected_fields")
            if not adds or not op["response"].get("schema"):
                continue
            base = op["response"]["schema"].removeprefix("[]")
            out.setdefault(base, []).extend(adds)
    return out


def filter_name(namespace: str, opname: str, optional: list[Any]) -> str | None:
    """The filter dataclass name for an operation with more than two filters."""
    return f"{pascal(namespace)}{pascal(opname)}Filter" if len(optional) > 2 else None


def is_union(name: str) -> bool:
    """Whether ``name`` is one of the internally-tagged unions on this surface."""
    return bool(discriminated(SCHEMAS.get(name, {})))


def response_expr(op: dict[str, Any], raw: str) -> tuple[str, str]:
    """The declared return type and the expression producing it from ``raw``."""
    kind, schema = op["response"]["kind"], op["response"]["schema"]
    if kind == "none":
        return "None", ""
    model = f"models.{pascal(schema)}"
    if is_union(schema):
        # A discriminated union is an `Annotated` alias, not a class: it has no
        # `.model_validate`, so pydantic validates it through a TypeAdapter,
        # built once at import in models.py rather than per call.
        adapter = f"models.{pascal(schema)}Adapter"
        if kind == "array":
            return (
                f"builtins.list[{model}]",
                f"[{adapter}.validate_python(item) for item in {raw} or []]",
            )
        if kind == "page":
            raise NotImplementedError(
                f"{op['summary']}: a paginated response whose item schema is a discriminated "
                f"union needs a page parser this generator does not emit. Add one to "
                f"_page.py and teach response_expr about it rather than shipping a call "
                f"to a helper that is not there."
            )
        return model, f"{adapter}.validate_python({raw})"
    if kind == "array":
        return (
            f"builtins.list[{model}]",
            f"[{model}.model_validate(item) for item in {raw} or []]",
        )
    if kind == "page":
        return f"Page[{model}]", f"page_of({raw}, {model})"
    return model, f"{model}.model_validate({raw})"


def operation_signature(
    namespace: str, opname: str, op: dict[str, Any]
) -> list[tuple[str, str, str]]:
    """This operation's caller-facing parameters as ``(name, annotation, default)``.

    Ordered so every parameter carrying a default follows every one that does
    not, which TypeScript tolerates and Python does not.
    """
    implicit = implicit_params(namespace, op)
    args: list[tuple[str, str, str]] = []
    for p in op["path_params"]:
        if p["name"] not in implicit:
            args.append((safe(p["name"]), "str", ""))
    required_q, optional_q = split_query(op)
    for q in required_q:
        args.append((safe(q["name"]), "str", ""))
    if op["request_body"] == "schema":
        args.append(("body", f"models.{pascal(op['request_schema'])}", ""))
    elif op["request_body"] == "untyped":
        args.append(("body", "Any", ""))
    fname = filter_name(namespace, opname, optional_q)
    if fname:
        args.append(("filter", f"{fname} | None", "None"))
    else:
        for q in optional_q:
            args.append((safe(q["name"]), "str | None", "None"))
    if op["paginated"]:
        args.append(("page", "PageRequest | None", "None"))
    return args


def emit_call_builder(namespace: str, opname: str, op: dict[str, Any]) -> list[str]:
    """The shared ``ManagementCall`` builder both handles use for one operation."""
    canonical = f"{namespace}.{opname}"
    implicit = implicit_params(namespace, op)
    args = operation_signature(namespace, opname, op)
    params = ["client: _AxiamClientBase", "scope: NamespaceScope"]
    params += [f"{n}: {t}" + (f" = {d}" if d else "") for n, t, d in args]

    prelude: list[str] = []
    route = op["path"]
    for p in op["path_params"]:
        name = p["name"]
        if name in implicit:
            fn = "resolve_org" if name == "org_id" else "resolve_tenant"
            prelude.append(f'    {safe(name)} = {fn}(client, scope, "{canonical}")')
            route = route.replace(f"{{{name}}}", f"{{{safe(name)}}}")
        elif p.get("format") == "uuid":
            prelude.append(
                f'    {safe(name)} = require_uuid({safe(name)}, "{name}", "{canonical}")'
            )
            route = route.replace(f"{{{name}}}", f"{{{safe(name)}}}")
        else:
            prelude.append(f'    {safe(name)} = quote({safe(name)}, safe="")')
            route = route.replace(f"{{{name}}}", f"{{{safe(name)}}}")

    required_q, optional_q = split_query(op)
    fname = filter_name(namespace, opname, optional_q)
    query: list[str] = []
    if op["paginated"]:
        query.append("**page_query(page)")
    for q in required_q:
        query.append(f'"{q["name"]}": {safe(q["name"])}')
    for q in optional_q:
        src = f"(filter.{safe(q['name'])} if filter else None)" if fname else safe(q["name"])
        query.append(f'"{q["name"]}": {src}')

    if op["request_body"] == "schema":
        body_expr = "body.to_wire()"
    elif op["request_body"] == "untyped":
        body_expr = "body"
    else:
        body_expr = None

    lines = [f"def _call_{safe(opname)}(", *[f"    {p}," for p in params], ") -> ManagementCall:"]
    lines.extend(
        docstring(
            f"Build the ``{canonical}`` call.\n\nShared by the sync and async handles so the "
            f"path, query and body are decided in exactly one place.",
            "    ",
        )
    )
    lines.extend(prelude)
    lines.append("    return ManagementCall(")
    lines.append(f'        operation="{canonical}",')
    lines.append(f'        method="{op["method"]}",')
    lines.append(f'        path_template="{op["path"]}",')
    lines.append(f'        path=f"{route}",' if "{" in route else f'        path="{route}",')
    if query:
        oneline = "        query={" + ", ".join(query) + "},"
        if len(oneline) <= 100:
            lines.append(oneline)
        else:
            lines.append("        query={")
            lines.extend(f"            {entry}," for entry in query)
            lines.append("        },")
    if body_expr:
        lines.append(f"        body={body_expr},")
    lines.append("    )")
    lines.append("")
    lines.append("")
    return lines


def operation_doc(op: dict[str, Any]) -> str:
    """The docstring for one generated operation method."""
    text = f"``{op['method']} {op['path']}``"
    if op["update_style"] == "replace":
        text += (
            "\n\n**This is a replacement, not a patch** (§27.4 rule 5). Every field of the "
            "body is required, and what you do not carry over from a prior read is not "
            "preserved -- it is overwritten. Read first, change the field you mean, send "
            "the whole thing back."
        )
    if op["sensitive_response_fields"]:
        joined = ", ".join(f"``{f}``" for f in op["sensitive_response_fields"])
        text += (
            f"\n\n**Returns secret material, once.** {joined} is returned by this call and "
            f"by no other; no later ``get`` will return it again, and the ``get`` projection "
            f"has no field where it was. Discarding the result destroys the credential "
            f"(§27.5 rule 3)."
        )
    if op["method"] != "GET":
        text += (
            "\n\nNot retried on failure (§27.4 rule 8): every write on this surface is "
            "issued exactly once, including the ones that look idempotent."
        )
    return text


def signature_lines(
    adef: str, method: str, args: list[tuple[str, str, str]], ret: str
) -> list[str]:
    """A ``def`` line for ``method``, wrapped across lines when it will not fit."""
    rendered = [f"{n}: {t}" + (f" = {d}" if d else "") for n, t, d in args]
    oneline = f"    {adef} {method}(self" + "".join(f", {r}" for r in rendered) + f") -> {ret}:"
    if len(oneline) <= 100:
        return [oneline]
    return [
        f"    {adef} {method}(",
        "        self,",
        *[f"        {r}," for r in rendered],
        f"    ) -> {ret}:",
    ]


def emit_handle(namespace: str, nsdef: dict[str, Any], *, is_async: bool) -> list[str]:
    """One namespace handle class, in its sync or async form."""
    cls = ("Async" if is_async else "") + f"{pascal(namespace)}Api"
    client_type = "AsyncAxiamClient" if is_async else "AxiamClient"
    ops = nsdef["operations"]
    has_org = any("org_id" in implicit_params(namespace, o) for o in ops.values())
    has_tenant = any("tenant_id" in implicit_params(namespace, o) for o in ops.values())
    adef, aw = ("async def", "await ") if is_async else ("def", "")
    send = "send_management_async" if is_async else "send_management"
    collect = "collect_pages_async" if is_async else "collect_pages"

    lines = [f"class {cls}:"]
    lines.extend(
        docstring(
            f"The ``{namespace}`` namespace handle"
            + (", async form." if is_async else ".")
            + f"\n\n{nsdef['doc']}\n\nAcquiring one performs no I/O and allocates nothing "
            f"meaningful (§27.2 rule 1); it holds the client and cannot be constructed "
            f"without one.",
            "    ",
        )
    )
    lines.append("")
    lines.append(
        f"    def __init__("
        f"self, client: {client_type}, scope: NamespaceScope | None = None"
        f") -> None:"
    )
    lines.extend(
        docstring("Bind the handle to ``client``; reached as a client property.", "        ")
    )
    lines.append("        self._client = client")
    lines.append("        self._scope = scope or NamespaceScope()")
    lines.append("")

    if has_org:
        lines.append(f"    def in_org(self, org_id: str) -> {cls}:")
        lines.extend(
            docstring(
                "Address a different organization than the client's own.\n\n§27.4 rule 3: the "
                "client's ``org_id`` is the default, and a platform-admin token legitimately "
                "overrides it. Returns a new handle; the original is unchanged.",
                "        ",
            )
        )
        lines.append(f"        return {cls}(self._client, self._scope.with_org(org_id))")
        lines.append("")
    if has_tenant:
        lines.append(f"    def for_tenant(self, tenant_id: str) -> {cls}:")
        lines.extend(
            docstring(
                "Address a different tenant than the client's own (§27.4 rule 3).\n\nReturns a "
                "new handle; the original is unchanged.",
                "        ",
            )
        )
        lines.append(f"        return {cls}(self._client, self._scope.with_tenant(tenant_id))")
        lines.append("")

    for opname, op in ops.items():
        args = operation_signature(namespace, opname, op)
        method = safe(opname)
        ret, expr = response_expr(op, "raw")
        forward = ", ".join(n for n, _, _ in args)
        call = f"_call_{method}(self._client, self._scope{', ' + forward if forward else ''})"

        lines.extend(signature_lines(adef, method, args, ret))
        lines.extend(docstring(operation_doc(op), "        "))
        assign = "" if ret == "None" else "raw = "
        lines.append(f"        {assign}{aw}{send}(")
        lines.append("            self._client,")
        lines.append(f"            {call},")
        lines.append("        )")
        if ret != "None":
            lines.append(f"        return {expr}")
        lines.append("")

        if op["paginated"]:
            lead = [(n, t, d) for n, t, d in args if n != "page"]
            lead_fwd = "".join(f"{n}, " for n, _, _ in lead)
            inner = ret[len("Page[") : -1]
            # Same shadowing as the array case above: `list` is a method here.
            lines.extend(
                signature_lines(
                    adef,
                    f"{method}_all",
                    [*lead, ("start", "PageRequest | None", "None")],
                    f"builtins.list[{inner}]",
                )
            )
            lines.extend(
                docstring(
                    f"Walk ``{namespace}.{opname}`` to exhaustion, concatenating every page."
                    "\n\nThe auto-paging form §27.4 rule 4 requires. It stops on an empty page "
                    "even if ``total`` disagrees, so a misreporting server costs one wasted "
                    "request rather than an unbounded loop.",
                    "        ",
                )
            )
            lines.append(
                f"        return {aw}{collect}(start, lambda p: self.{method}({lead_fwd}p))"
            )
            lines.append("")
    return lines


def emit_filters(namespace: str, nsdef: dict[str, Any]) -> list[str]:
    """Filter dataclasses for the operations carrying more than two optional filters."""
    out: list[str] = []
    for opname, op in nsdef["operations"].items():
        _, optional = split_query(op)
        name = filter_name(namespace, opname, optional)
        if not name:
            continue
        out.append("@dataclass(frozen=True)")
        out.append(f"class {name}:")
        out.extend(
            docstring(
                f"Optional filters for ``{namespace}.{opname}``.\n\nSix loose optional "
                f"arguments is a call site a reader cannot check and a refactor silently "
                f"reorders, so they travel as one object.",
                "    ",
            )
        )
        out.append("")
        for q in optional:
            out.append(f"    {safe(q['name'])}: str | None = None")
            out.extend(field_doc(f"Filter on ``{q['name']}``."))
            out.append("")
        out.append("")
    return out


def emit_namespace(namespace: str, nsdef: dict[str, Any]) -> str:
    """The whole ``ops/<namespace>.py`` module."""
    body: list[str] = []
    body.extend(emit_filters(namespace, nsdef))
    for opname, op in nsdef["operations"].items():
        body.extend(emit_call_builder(namespace, opname, op))
    body.extend(emit_handle(namespace, nsdef, is_async=False))
    body.append("")
    body.extend(emit_handle(namespace, nsdef, is_async=True))
    rendered = "\n".join(body)

    page_names = [
        n
        for n in ("collect_pages_async", "collect_pages", "page_of", "page_query")
        if n in rendered
    ]
    page_types = [n for n in ("PageRequest", "Page") if n in rendered]
    scope_names = [n for n in ("require_uuid", "resolve_org", "resolve_tenant") if n in rendered]

    imports = ["from __future__ import annotations", ""]
    typing_names = [n for n in ("Any",) if f": {n}" in rendered or f"[{n}]" in rendered]
    plain: list[str] = []
    stdlib: list[str] = []
    if "builtins." in rendered:
        # Every namespace handle whose canonical operation set includes `list`
        # shadows the builtin inside its own class body, so an annotation like
        # `list[Resource]` would resolve to the method rather than the type.
        # Qualifying it is the fix that keeps the operation named what §27.1
        # names it.
        plain.append("import builtins")
    if "@dataclass" in rendered:
        stdlib.append("from dataclasses import dataclass")
    if typing_names:
        stdlib.append("from typing import TYPE_CHECKING, " + ", ".join(typing_names))
    else:
        stdlib.append("from typing import TYPE_CHECKING")
    if "quote(" in rendered:
        stdlib.append("from urllib.parse import quote")
    # isort puts every `import x` above every `from x import y`, so the two
    # groups are sorted separately rather than as one list of strings.
    imports.extend(sorted(plain))
    imports.extend(sorted(stdlib))
    imports.append("")
    if "models." in rendered:
        imports.append("from axiam_sdk.management import models")
    if page_types or page_names:
        merged = sorted(page_types + page_names)
        imports.append(
            "from axiam_sdk.management._page import (\n"
            + "".join(f"    {n},\n" for n in merged)
            + ")"
        )
    imports.append(
        "from axiam_sdk.management._request import (\n"
        "    ManagementCall,\n"
        "    send_management,\n"
        "    send_management_async,\n"
        ")"
    )
    scope_import = ["NamespaceScope", *scope_names]
    imports.append(
        "from axiam_sdk.management._scope import (\n"
        + "".join(f"    {n},\n" for n in sorted(scope_import))
        + ")"
    )
    imports.append("")
    imports.append("if TYPE_CHECKING:  # pragma: no cover - typing only")
    imports.append("    from axiam_sdk._async_client import AsyncAxiamClient")
    imports.append("    from axiam_sdk._client import AxiamClient, _AxiamClientBase")
    imports.append("")

    header = [BANNER.rstrip("\n"), ""]
    header.extend(
        docstring(f"The ``{namespace}`` management namespace (CONTRACT §27.1).\n\n{nsdef['doc']}")
    )
    header.append("")
    return "\n".join([*header, *imports, "", rendered]).rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# The namespace index, and the accessors the clients mix in
# ---------------------------------------------------------------------------

INDEX_DOC = '''"""One handle per §27 namespace, and the accessors that reach them.

§27.2 makes this namespacing normative rather than stylistic: twenty namespaces
have a ``list`` and fourteen a ``get``, so flattening 146 operations onto the
client would need a disambiguating prefix invented once per operation -- and
would bury the eight §1 methods most callers actually want under five times as
many they do not.
"""
'''


def emit_ops_index() -> str:
    """The whole ``ops/__init__.py`` module."""
    names = list(REGISTRY["namespaces"].keys())
    out = [
        BANNER.rstrip("\n"),
        "",
        INDEX_DOC.rstrip("\n"),
        "",
        "from __future__ import annotations",
        "",
        "from typing import TYPE_CHECKING, cast",
        "",
    ]
    for ns in sorted(names):
        line = f"from axiam_sdk.management.ops.{ns} import Async{pascal(ns)}Api, {pascal(ns)}Api"
        if len(line) <= 100:
            out.append(line)
        else:
            out.append(f"from axiam_sdk.management.ops.{ns} import (")
            out.append(f"    Async{pascal(ns)}Api,")
            out.append(f"    {pascal(ns)}Api,")
            out.append(")")
    out.append("")
    out.append("if TYPE_CHECKING:  # pragma: no cover - typing only")
    out.append("    from axiam_sdk._async_client import AsyncAxiamClient")
    out.append("    from axiam_sdk._client import AxiamClient")
    out.append("    from axiam_sdk.management.manifest import AsyncManifestApi, ManifestApi")
    out.append("")
    out.append("__all__ = [")
    for ns in names:
        out.append(f'    "Async{pascal(ns)}Api",')
        out.append(f'    "{pascal(ns)}Api",')
    out.append('    "AsyncManagementApi",')
    out.append('    "AsyncManagementNamespaces",')
    out.append('    "ManagementApi",')
    out.append('    "ManagementNamespaces",')
    out.append("]")
    out.append("")
    out.append("")

    for is_async in (False, True):
        prefix = "Async" if is_async else ""
        client = "AsyncAxiamClient" if is_async else "AxiamClient"
        out.append(f"class {prefix}ManagementApi:")
        out.extend(
            docstring(
                f"The §27 management surface{', async form' if is_async else ''}, grouped by "
                f"namespace.\n\nReached as ``client.management``. Every namespace is also "
                f"reachable directly on the client -- ``client.users`` and "
                f"``client.management.users`` are the same handle.",
                "    ",
            )
        )
        out.append("")
        out.append(f"    def __init__(self, client: {client}) -> None:")
        out.extend(docstring("Bind the surface to ``client``.", "        "))
        out.append("        self._client = client")
        out.append("")
        for ns in names:
            out.append("    @property")
            out.append(f"    def {ns}(self) -> {prefix}{pascal(ns)}Api:")
            out.extend(docstring(REGISTRY["namespaces"][ns]["doc"], "        "))
            out.append(f"        return {prefix}{pascal(ns)}Api(self._client)")
            out.append("")
        out.append("    @property")
        out.append(f"    def manifest(self) -> {prefix}ManifestApi:")
        out.extend(
            docstring(
                "The declarative layer (§27.6): ``plan`` what a manifest would change, "
                "``apply`` it.",
                "        ",
            )
        )
        out.append(f"        from axiam_sdk.management.manifest import {prefix}ManifestApi")
        out.append("")
        out.append(f"        return {prefix}ManifestApi(self._client)")
        out.append("")
        out.append("")

        out.append(f"class {prefix}ManagementNamespaces:")
        out.extend(
            docstring(
                f"The §27 accessors mixed into :class:`~axiam_sdk.{client}`.\n\nEach property "
                f"builds its handle on access and performs no I/O (§27.2 rule 1), so holding "
                f"one costs nothing and none of them runs at construction.",
                "    ",
            )
        )
        out.append("")
        out.append("    @property")
        out.append(f"    def management(self) -> {prefix}ManagementApi:")
        out.extend(docstring("The whole §27 surface, grouped by namespace.", "        "))
        out.append(f'        return {prefix}ManagementApi(cast("{client}", self))')
        out.append("")
        out.append("    @property")
        out.append(f"    def manifest(self) -> {prefix}ManifestApi:")
        out.extend(
            docstring(
                "The declarative layer (§27.6): ``plan`` what a manifest would change, "
                "``apply`` it.",
                "        ",
            )
        )
        out.append("        return self.management.manifest")
        out.append("")
        for ns in names:
            out.append("    @property")
            out.append(f"    def {ns}(self) -> {prefix}{pascal(ns)}Api:")
            out.extend(docstring(REGISTRY["namespaces"][ns]["doc"], "        "))
            out.append(f"        return self.management.{ns}")
            out.append("")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# Example instances, and the generated conformance test
# ---------------------------------------------------------------------------


def example_json(schema: Any, depth: int = 0) -> Any:
    """A minimal server response body satisfying ``schema``."""
    if depth > 6 or not schema:
        return None
    if "$ref" in schema:
        return example_json(resolve_ref(schema), depth + 1)
    inner = nullable_ref(schema)
    if inner:
        return example_json(SCHEMAS.get(inner, {}), depth + 1)
    if "enum" in schema:
        return schema["enum"][0]
    variants = schema.get("oneOf") or schema.get("anyOf")
    if variants:
        first = next((v for v in variants if v.get("type") != "null"), None)
        return example_json(first, depth + 1) if first else None
    if "allOf" in schema:
        merged: dict[str, Any] = {}
        for part in schema["allOf"]:
            got = example_json(part, depth + 1)
            if isinstance(got, dict):
                merged.update(got)
        return merged
    kind = schema.get("type")
    if isinstance(kind, list):
        kind = next((k for k in kind if k != "null"), None)
    if kind == "object" or (not kind and "properties" in schema):
        required = set(schema.get("required") or [])
        return {
            name: example_json(prop, depth + 1)
            for name, prop in (schema.get("properties") or {}).items()
            if name in required
        }
    if kind == "array":
        return []
    if kind in ("integer", "number"):
        return 1
    if kind == "boolean":
        return True
    if kind == "string":
        if schema.get("format") == "uuid":
            return EXAMPLE_UUID
        if schema.get("format") == "date-time":
            return EXAMPLE_TIME
        return "example"
    return {}


def example_response(op: dict[str, Any]) -> str:
    """A Python literal for the response body the conformance test mounts."""
    kind, schema = op["response"]["kind"], op["response"]["schema"]
    if kind == "none":
        return "None"
    # `repr`, not `json.dumps`: this literal is pasted into a Python test module,
    # where JSON's `true`/`null` are NameErrors.
    one = example_json(SCHEMAS.get(schema, {}))
    if kind == "array":
        return repr([one])
    if kind == "page":
        return repr({"items": [one], "total": 1, "offset": 0, "limit": 50})
    return repr(one)


def py_literal(schema: Any, secrets: set[str], fieldname: str | None = None, depth: int = 0) -> str:
    """A Python expression building a minimal valid value for ``schema``."""
    if depth > 6:
        return "None"
    if fieldname and fieldname in secrets:
        return 'SecretStr("example")'
    if "$ref" in schema:
        return literal_for(schema["$ref"].split("/")[-1], secrets, depth + 1)
    if nullable_ref(schema) or "oneOf" in schema or "anyOf" in schema:
        return "None"
    kind = schema.get("type")
    if isinstance(kind, list):
        if "null" in kind:
            return "None"
        kind = next(iter(kind), None)
    if "enum" in schema:
        return json.dumps(schema["enum"][0])
    if kind == "array":
        return "[]"
    if kind in ("integer", "number"):
        return "1"
    if kind == "boolean":
        return "True"
    if kind == "string":
        if schema.get("format") == "uuid":
            return f'"{EXAMPLE_UUID}"'
        if schema.get("format") == "date-time":
            return f'"{EXAMPLE_TIME}"'
        return '"example"'
    if kind == "object" or not schema:
        return "{}"
    return "None"


def literal_for(name: str, secrets: set[str], depth: int = 0) -> str:
    """A Python expression constructing a minimal valid ``name``."""
    schema = SCHEMAS.get(name, {})
    if "enum" in schema:
        return json.dumps(schema["enum"][0])
    union = discriminated(schema)
    if union:
        tag, arms = union
        value, payload = arms[0]
        arm = f"{pascal(name)}{pascal(value)}"
        if "$ref" in payload:
            props, required, _ = flatten(payload["$ref"].split("/")[-1])
        else:
            props = payload.get("properties") or {}
            required = set(payload.get("required") or [])
        parts = [f'{safe(tag)}="{value}"']
        parts += [
            f"{safe(p)}={py_literal(props[p], set(), p, depth + 1)}"
            for p in sorted(props)
            if p in required and p != tag
        ]
        return f"models.{arm}({', '.join(parts)})"
    if "oneOf" in schema:
        return "None"
    props, required, _ = flatten(name)
    own = secrets if depth == 0 else set()
    parts = [
        f"{safe(p)}={py_literal(props[p], own, p, depth + 1)}"
        for p in sorted(props)
        if p in required
    ]
    return f"models.{pascal(name)}({', '.join(parts)})"


def call_arguments(
    namespace: str, opname: str, op: dict[str, Any], secrets: dict[str, set[str]]
) -> tuple[list[str], str]:
    """The conformance test's positional arguments, and the route it mounts."""
    implicit = implicit_params(namespace, op)
    args: list[str] = []
    route = op["path"]
    for p in op["path_params"]:
        name = p["name"]
        if name in implicit:
            route = route.replace(f"{{{name}}}", "{ORG_ID}" if name == "org_id" else "{TENANT_ID}")
            continue
        if p.get("format") == "uuid":
            args.append("EXAMPLE_ID")
            route = route.replace(f"{{{name}}}", "{EXAMPLE_ID}")
        else:
            args.append('"example"')
            route = route.replace(f"{{{name}}}", "example")
    required_q, optional_q = split_query(op)
    args.extend('"example"' for _ in required_q)
    if op["request_body"] == "schema":
        args.append(literal_for(op["request_schema"], secrets.get(op["request_schema"], set())))
    elif op["request_body"] == "untyped":
        args.append("{}")
    if filter_name(namespace, opname, optional_q):
        args.append("None")
    else:
        args.extend("None" for _ in optional_q)
    if op["paginated"]:
        args.append("PageRequest(limit=50)")
    return args, route


TEST_DOC = '''"""Generated §27 surface conformance: every operation is reached once.

Per operation: the SDK issues the registry's method against the registry's path
and parses the response shape ``openapi.json`` declares -- through the sync
handle and the async one, because those are two distinct code paths and testing
one leaves half the generated surface unexercised.

Semantics that are not per-operation -- sparse-update key sets, secret
redaction, error mapping, pagination walks, the manifest -- are tested by hand
in ``tests/management/``.
"""
'''


def emit_test() -> str:
    """The whole generated conformance-test module."""
    secrets = sensitive_map()
    canonical_all: list[str] = []
    out = [
        BANNER.rstrip("\n"),
        "",
        TEST_DOC.rstrip("\n"),
        "",
        "from __future__ import annotations",
        "",
        "import pytest",
        "from pydantic import SecretStr",
        "",
        "from axiam_sdk.management import PageRequest, models",
        "from tests.management_support import (",
        "    EXAMPLE_ID,",
        "    ORG_ID,",
        "    TENANT_ID,",
        "    expected_surface,",
        "    mount_json,",
        "    with_async_client,",
        "    with_client,",
        ")",
        "",
        "",
    ]

    for namespace, nsdef in REGISTRY["namespaces"].items():
        for opname, op in nsdef["operations"].items():
            canonical = f"{namespace}.{opname}"
            canonical_all.append(canonical)
            args, route = call_arguments(namespace, opname, op, secrets)
            body = example_response(op)
            method = safe(opname)
            joined = ", ".join(args)
            lead = ", ".join(a for a in args if a != "PageRequest(limit=50)")
            test_name = f"test_{namespace}_{method}"

            out.append(f"def {test_name}() -> None:")
            out.extend(docstring(f"``{canonical}`` -- {op['method']} {op['path']}.", "    "))
            out.append("    with with_client() as (router, client):")
            mounted = f'f"{route}"' if "{" in route else f'"{route}"'
            out.append(
                f'        mount_json(router, "{op["method"]}", {mounted}, '
                f"{op['response']['status']}, {body})"
            )
            out.append(f"        client.{namespace}.{method}({joined})")
            if op["paginated"]:
                tail = f"{lead}, " if lead else ""
                out.append(f"        client.{namespace}.{method}_all({tail}PageRequest(limit=50))")
            out.append("")
            out.append("")

            out.append("@pytest.mark.asyncio")
            out.append(f"async def {test_name}_async() -> None:")
            out.extend(docstring(f"``{canonical}`` through the async handle.", "    "))
            out.append("    async with with_async_client() as (router, client):")
            out.append(
                f'        mount_json(router, "{op["method"]}", {mounted}, '
                f"{op['response']['status']}, {body})"
            )
            out.append(f"        await client.{namespace}.{method}({joined})")
            if op["paginated"]:
                tail = f"{lead}, " if lead else ""
                out.append(
                    f"        await client.{namespace}.{method}_all({tail}PageRequest(limit=50))"
                )
            out.append("")
            out.append("")

    out.append("EXERCISED = [")
    for name in sorted(canonical_all):
        out.append(f'    "{name}",')
    out.append("]")
    out.extend(field_doc("Every operation the cases above reach, in registry order.", ""))
    out.append("")
    out.append("")
    out.append("def test_generated_surface_covers_the_registry() -> None:")
    out.extend(
        docstring(
            "§27.9: a partial regeneration must fail here, not ship 140 of 146.\n\nAsserting "
            "the whole set rather than the count catches a regeneration that dropped one "
            "operation and gained another.",
            "    ",
        )
    )
    out.append("    assert EXERCISED == expected_surface()")
    out.append(f"    assert len(EXERCISED) == {REGISTRY['operation_count']}")
    out.append("")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def ruff_format(path: Path, source: str) -> str:
    """Run ``ruff format`` over generated ``source``, as ``gofmt`` would.

    CI runs ``ruff format --check .`` over the whole repository, so generated
    output has to satisfy the formatter exactly. Reproducing a formatter's line
    breaking inside an emitter is a losing game -- the response-body literals in
    the conformance suite alone would need most of one -- so the emitter aims for
    correct code and the formatter decides the layout. ``ruff`` is already a dev
    dependency, pinned in ``pyproject.toml``, and both this script and
    ``ruff format --check`` run in the same CI job off that pin.

    Raises:
        SystemExit: if ``ruff`` is not on PATH, or rejects the emitted source.
            Silently skipping would make ``--check`` depend on who ran it.
    """
    try:
        done = subprocess.run(
            ["ruff", "format", "--stdin-filename", str(path), "-"],
            input=source,
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        raise SystemExit(
            "ruff is not on PATH; this generator formats its output with it. "
            "Install the dev extras: pip install -e '.[dev]'"
        ) from None
    if done.returncode != 0:
        raise SystemExit(f"ruff format rejected generated {path.name}:\n{done.stderr.strip()}")
    return done.stdout


def build() -> dict[Path, str]:
    """Every file this generator owns, mapped to its current content."""
    files: dict[Path, str] = {
        ROOT / "src/axiam_sdk/management/models.py": emit_models(),
        ROOT / "src/axiam_sdk/management/ops/__init__.py": emit_ops_index(),
        ROOT / "tests/test_management_surface_generated.py": emit_test(),
    }
    for ns, nsdef in REGISTRY["namespaces"].items():
        files[ROOT / f"src/axiam_sdk/management/ops/{ns}.py"] = emit_namespace(ns, nsdef)
    return {path: ruff_format(path, body) for path, body in files.items()}


def main() -> int:
    """Write the generated surface, or verify it is current under ``--check``."""
    files = build()
    if "--check" in sys.argv:
        stale = [
            path
            for path, body in files.items()
            if not path.exists()
            or path.read_text() != (body if body.endswith("\n") else body + "\n")
        ]
        if stale:
            for path in stale:
                print(f"FAIL: {path.relative_to(ROOT)} is stale", file=sys.stderr)
            print("run `python scripts/gen_management.py`", file=sys.stderr)
            return 1
        print(
            f"OK: {len(files)} generated files are current "
            f"({REGISTRY['operation_count']} operations)"
        )
        return 0
    for path, body in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body if body.endswith("\n") else body + "\n")
    print(
        f"wrote {len(files)} files: {REGISTRY['operation_count']} operations across "
        f"{REGISTRY['namespace_count']} namespaces"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
